### ISSUE TITLE
processingPipeline.Process fails for developer accounts on openshift without the service binding operator

### ISSUE THREAD

**Issue by mik-dass** [redhat-developer/service-binding-operator#1003]
### What is the environment (Minikube, Openshift)?

Openshift (developer account)

### What is the SBO version used?

v0.9.0

### What are the steps to reproduce this issue?

  1. Remove the service binding operator from the cluster
  2. Login to a developer account on openshift
  3. Call `processingPipeline.Process(<&service--binding-resource>)` 

### What is the expected behaviour?

`processingPipeline.Process(<&service--binding-resource>)` doesn't throw any errors.

### What is the actual behaviour?

`customresourcedefinitions.apiextensions.k8s.io "redisclusters.redis.redis.opstreelabs.in" is forbidden: User "<user-name>" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
`

### Additional Information (Screenshots, etc)

The pipeline is initialized like
```
mgr, err := ctrl.NewManager(client.KubeClientConfig, ctrl.Options{
		Scheme: runtime.NewScheme(),
		// disable the health probes to prevent binding to them
		HealthProbeBindAddress: "0",
		// disable the prometheus metrics
		MetricsBindAddress: "0",
	})
	if err != nil {
		return nil, err
	}

	return builder.DefaultBuilder.WithContextProvider(context.Provider(client.DynamicClient, context.ResourceLookup(mgr.GetRESTMapper()))).Build(), nil
```

The service binding definition
```      apiVersion: binding.operators.coreos.com/v1alpha1
      kind: ServiceBinding
      metadata:
        creationTimestamp: null
        name: nodejs-project-ukgq-rediscluster-rediscluster
      spec:
        application:
          group: apps
          name: nodejs-project-ukgq-app
          resource: deployments
          version: v1
        bindAsFiles: false
        detectBindingResources: true
        services:
        - group: redis.redis.opstreelabs.in
          kind: RedisCluster
          name: rediscluster
          version: v1beta1
      status:
        secret: ""
  name: nodejs-project-ukgq-rediscluster-rediscluster
```

**Comment by kadel** [comment]
It looks like service binding library is trying to get cluster-wide resources.

This is especially problematic on OpenShift as  normal cluster users usually don't have permissions to do so.

**Comment by slemeur** [comment]
linking to: https://github.com/redhat-developer/service-binding-operator/issues/810

**Comment by kadel** [comment]
created a small example to verify this issue: https://github.com/kadel/service-binding-perm-issue

**Comment by pedjak** [comment]
> If the code base is supposed to be useful as a library it should avoid calls that require special privileges.

binding process requires access to CRDs in order to figure out if there are some annotations there. if you do not want to use annotations you can exclude that stage from the pipeline, but otherwise the account you use for accessing the cluster must have appropriate rights (SBO service account does)

**Comment by kadel** [comment]
> There is also another option: the current architecture is very flexible and you can provide your own [`Context`](https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/reconcile/pipeline/api.go#L94) implementation and plugin it into the pipeline. Such implementation can mask access to CRD and do not talk to k8s api our alternatively read CRDs from a custom source. Anything is possible.

I'm going through the code to check how it can be done, but so far I can't see a way how to do that :-(
Can someone provide some pointers or examples how to achieve that?

**Comment by slemeur** [comment]
cc @baijum : Could you please get in touch with @kadel ?

**Comment by baijum** [comment]
I have created a screencast to explain the process of customizing the pipeline.
https://www.youtube.com/watch?v=U3Wv_fO84ng

**Comment by pedjak** [comment]
@kadel please let us know if you were able to make progress on this?

As @baijum pointed out, you can replace [BindingDefinition](https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/reconcile/pipeline/handler/collect/impl.go#L38) stage with a custom one where CRDs are not read at all. An alternative to that is to provide your own [Context](https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/reconcile/pipeline/api.go#L94) implementation that also return its own [Service](https://github.com/redhat-developer/service-binding-operator/blob/7bdc3c94786f4cd07a4b113d57a9e89328f245db/pkg/reconcile/pipeline/api.go#L42) implementation where access to CRDs are ignored. Your own Context implementation can be based on [the existing implementation](https://github.com/redhat-developer/service-binding-operator/blob/7bdc3c94786f4cd07a4b113d57a9e89328f245db/pkg/reconcile/pipeline/context/impl.go#L60), or you can start it from scratch.

Anyhow, not reading CRDs/CSVs will turn off one important source of binding information,  making impossible to bind a service that does not contain binding annotation nor it is provisioned. The idea behind having annotations on CRDs is to set them once by operator vendor, freeing user from adding them on each service resource.

According to the specification, binding annotations can exist on:
* OLM descriptors
* CRDs
* service resource

> If the code base is supposed to be useful as a library it should avoid calls that require special privileges.

The binding logic should have access to all above resources to gather all relevant data. Skipping some of them would make binding impossible/wrong in certain usecases, and it should be used with care.

**Comment by kadel** [comment]
> @kadel please let us know if you were able to make progress on this?

@valaparthvi is working on this. 
@valaparthvi, can you please let @pedjak and @baijum know if you face any problems? 

> Anyhow, not reading CRDs/CSVs will turn off one important source of binding information, making impossible to bind a service that does not contain binding annotation nor it is provisioned. The idea behind having annotations on CRDs is to set them once by operator vendor, freeing user from adding them on each service resource.

> The binding logic should have access to all above resources to gather all relevant data. Skipping some of them would make binding impossible/wrong in certain usecases, and it should be used with care.

Odo executes actions on behalf of its user (all API calls to Kubernetes are done with user account). 
Most "normal" develop user accounts won't have permission to read cluster wide resources. We would like to read the information form CRD, but most user will not have enough permissions for that.

This will be a  problem for most **client-side** tools  that will try to use service binding "as a library".

**Comment by pedjak** [comment]
> This will be a problem for most client-side tools that will try to use service binding "as a library".

The binding process requires the access to a number of resources and requests need to be executed on behalf of user/service account having proper permission. Unfortunately, I do not see a way around it, given how the binding spec is defined. 

`client-side` tools could execute requests on behalf of a dedicated service account.

IMHO, users should not experience any difference when service binding operator is installed or not in the cluster. We should use service binding as "library" only when we can guarantee the same behavior, i.e. user has enough permission to read all needed resources. That is probably a case on local dev clusters, but certainly not on DevSandbox. Otherwise, insisting on binding without operator on a cluster without enough rights could be confusing for users.

BTW, @valaparthvi and @kadel do we need some more action items out of this issue, or it could be closed?

**Comment by valaparthvi** [comment]
>BTW, @valaparthvi and @kadel do we need some more action items out of this issue, or it could be closed?

 I think we can close it for now. The video by @baijum was really helpful, thank you for that. It seems like we might be able to fix this for odo without much hassle(:crossed_fingers:). We can reopen this issue if something related to it pops up again.
