### ISSUE TITLE
Unable to install operator on Power Cluster (ppc64le) 4.7 into all namespaces

### ISSUE THREAD

**Issue by kandarpamalipeddi** [redhat-developer/service-binding-operator#1006]
### What is the environment (Minikube, Openshift)?
Openshift

### What is the SBO version used?
0.9.0 and 0.9.1

### What are the steps to reproduce this issue?
  1. On Power cluster (OCP 4.7) install service-binding-operator 0.9.0 or 0.9.1 using command line or from console (operatorhub). 
  2. Use All namespaces (channer preview/beta)

### What is the expected behaviour?
It should install successfully.

### What is the actual behaviour?
Installation going into pending state forever.

### Service Binding Operator Logs
No pod created for operator.
Failed at second event. 
I can see **_RequirementsNotMet: one or more requirements couldn't be found._**

### Additional Information (Screenshots, etc)
![image](https://user-images.githubusercontent.com/69784217/128201439-8d366b95-a306-4861-86bf-b0ff93e30ddf.png)
![image](https://user-images.githubusercontent.com/69784217/128201392-8adb3e46-d0bc-46ba-83f0-046be2a7d32b.png)

### Notes : 
1. Earlier I used servicebindingoperator 0.6.0 and 0.7.0, those are working fine on my cluster. Not sure since when it is failing.
2. Can install operator for a single namespace.
![image](https://user-images.githubusercontent.com/69784217/128201954-427cb4f4-6020-41e4-96e4-cd4e10b63940.png)

I tried removing all the CRDs after installation, but still same issue persist.

**Comment by pedjak** [comment]
@kandarpamalipeddi just to verify - the cluster did not have 0.8 installed previously? Is it possible to find more details about requirements that did not meet?

**Comment by pedjak** [comment]
Closing due to the lack of the feedback. Please reopen if still valid.
