### ISSUE TITLE
Operator cannot be updated using OLM

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#1026]
### What is the environment (Minikube, Openshift)?

New version fails to update on the number of clusters (tests, end users, demo clusters, workshops etc.).

### What is the SBO version used?

0.10.0 

### What are the steps to reproduce this issue?
  1. Have older version of Operator installed with OLM autoupdates
  2. Just wait :)

### What is the expected behaviour?

Operator running

### What is the actual behaviour?

Operator ends up in some strange state (two operators visible)
New one crashing in the loop (logs attached)
Old is not functional

### Service Binding Operator Logs

Logs:
https://gist.github.com/b1zzu/c33f01cc1d565adcab2165295cf38f02

### Additional Information (Screenshots, etc)
![image](https://user-images.githubusercontent.com/981838/133807502-9bb2471c-b1ef-4655-8c97-1da6a501d40d.png)
![Screenshot 2021-09-17 at 16 16 29](https://user-images.githubusercontent.com/981838/133807527-064d843f-58df-4a78-8d9c-9188a5ec45d5.png)

**Comment by wtrocki** [comment]
If you notice that problem.

Workaround:

Remove both operators
Cleanup all CR's and things left out by the operator (Not possible in some cases)
Install fresh operator version

**Comment by pmacik** [comment]
+1 for the workaround - the updates are not yet tested.

Error message:
```
 install strategy failed: Deployment.apps "service-binding-operator" is
        invalid: spec.selector: Invalid value:
        v1.LabelSelector{MatchLabels:map[string]string{"control-plane":"service-binding-controller-manager"},
        MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
The reason is most likely the change of the name of the `control-pane` of the controller manager introduced in https://github.com/redhat-developer/service-binding-operator/pull/1020

/cc @pedjak

**Comment by pmacik** [comment]
@wtrocki @pedjak  I found and tested another (minimal) workaround:

 * **Delete `service-binding-operator` deployment**

```shell
oc delete deployment service-binding-operator -n openshift-operators
```

**Comment by wtrocki** [comment]
@pmacik

**Comment by xkwangcn** [comment]
Is this issue fixed now? 
When update from 0.9.1->0.10.0, I also have this error 
```install strategy failed: Deployment.apps "service-binding-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"control-plane":"service-binding-controller-manager"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
And I uninstall 0.9.1 and reinstall 0.10.0 is succeed.

**Comment by xkwangcn** [comment]
But I met a new error, after installed 0.10.0, can't install 0.9.1 success.
I uninstall 0.10.0 from console, and then install 0.9.1, pending:
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/29972855/134924614-11db457b-7c1f-4514-983e-76598eaf22ee.png">

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/29972855/134924558-0fc42760-cc57-4270-b993-ba7c4efacec5.png">

**Comment by pedjak** [comment]
This is an OLM issue, reported here: https://github.com/operator-framework/operator-lifecycle-manager/issues/1608 and closed with a proposed workaround, that we cannot apply on the existing releases. Closing. Moving forward we will have that proposed workaround in mind.
