### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by jbpratt** [redhat-developer/service-binding-operator#1041]
With the feature preview of arm64 support in 4.9 (https://github.com/openshift/ocp-on-arm) and microshift (https://github.com/redhat-et/microshift) on the rise, SBO should have support for aarch64 images. Eventually the Interop team will support multi-arch testing to support this.

Related issue:
https://github.com/openshift/ocp-on-arm/issues/5

**Comment by pedjak** [comment]
Published in https://access.redhat.com/errata/RHEA-2021:4763
