### ISSUE TITLE
Use consistent names for operator and operator container image

### ISSUE THREAD

**Issue by ron1** [redhat-developer/service-binding-operator#106]
The name "service-binding-operator" is used consistently within the project except for the container image name. Rename container image name "app-binding-operator" to "service-binding-operator" to eliminate confusion.

**Comment by sbose78** [comment]
:) The name had got taken and wasn't available :(

**Comment by ron1** [comment]
Would it make more sense to rename "service-binding-operator" and "ServiceBindingRequest" to "app-binding-operator" and "AppBindingRequest"? Or rename the image to "svc-binding-operator"? The current naming inconsistency seems really problematic if you broaden adoption moving forward.

**Comment by sbose78** [comment]
I really like both the options, I will consider them in this sprint and update this issue. Thanks!

**Comment by sbose78** [comment]
> "app-binding-operator"
Are you OK with this, given that AppsCode already has an app binding CRD ? :)

**Comment by ron1** [comment]
Clearly there would be some confusion between the AppsCode AppBinding CRD and your AppBindingRequest CRD. But this seems no worse than the confusion between the Service Catalog ServiceBinding CRD and your current ServiceBindingRequest CRD. If you change the operator name from service-binding-operator to app-binding-operator, am I correct you would rename "service-binding" to "app-binding" globally including the name of this git repo?

**Comment by sbose78** [comment]
>  If you change the operator name from service-binding-operator to app-binding-operator, am I correct you would rename "service-binding" to "app-binding" globally including the name of this git repo?

Yes.


> But this seems no worse than the confusion between the Service Catalog ServiceBinding CRD and your current ServiceBindingRequest CRD.

Agreed. That is partially a goal. To move folks into binding to operator-backed services rather than service catalog services :)

**Comment by sbose78** [comment]
The image name is in way too many places now, will close this :)
