### ISSUE TITLE
Service Binding Operator cannot project bindings to Jobs

### ISSUE THREAD

**Issue by pedjak** [redhat-developer/service-binding-operator#1071]
### What is the SBO version used?

1.0

### What are the steps to reproduce this issue?
  1. Create a job 
  2. Create binding pointing to the job
  3. Binding cannot be established because `spec.template` is immutable

### What is the expected behaviour?

Binding could be projected into jobs

## Release Notes
Currently, binding to a `Job` CR from the `batch/v1` API fails because the `spec.template` is immutable. There is currently no workaround for this issue.

**Comment by baijum** [comment]
Normally `Job` resources are created through `CronJob` resources or custom resources (with controllers).

**Comment by filariow** [comment]
Document Service Binding Operator limitations with Immutable resources, like Pods and Jobs.

**Comment by baijum** [comment]
I sent PR #1317 to document supported and non-supported resources.
