### ISSUE TITLE
[Discussion] Any issue with using SBO as dependency in other operator

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#1073]
Context:
https://github.com/redhat-developer/app-services-operator/issues/290

Would adding ServiceBindingOperator as olm dependency case any issues for your team.

**Comment by slemeur** [comment]
Not at all if we have proper integration tests and e2e tests.
What do you envision necessary for that? and how would we coordinate the effort?

cc @pmacik

**Comment by wtrocki** [comment]
No need for coordination. The only issue I could see are sandbox relases. we need to make sure we would not dublicate sbo in this scenario

**Comment by pedjak** [comment]
> No need for actions from sbo side. The only issue I could see are sandbox releases. we need to make sure we would not duplicate sbo in this scenario.

Right. Actually if an operator strongly depends on an API delivered by some other operator, then this should be declared in operator bundle, similar to how we do this in rpm/deb world.
