### ISSUE TITLE
Missing setup with crunchy postgresQL database created with cruchy operator

### ISSUE THREAD

**Issue by mhdawson** [redhat-developer/service-binding-operator#1078]
### What is the environment (Minikube, Openshift)?
OpenShift

### What is the SBO version used?
1.0.0

### What are the steps to reproduce this issue?
  1. Install Crunch PostgresQL operator
  2. Create database with operator in application namespace
  3. Drag from DeploymentConfig to create service binding
  4. Connect with the data provided in the service binding files

### What is the expected behaviour?

Connection succeeds.

### What is the actual behaviour?

Connection fails with:

``` shell
[1638397659933] INFO (24 on nodejs-rest-http-crud-17-8fqt4): Listening on port 8080
error: no pg_hba.conf entry for host "10.217.0.194", user "crunchy2", database "crunchy2", SSL off
    at Parser.parseErrorMessage (/opt/app-root/src/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/opt/app-root/src/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/app-root/src/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/opt/app-root/src/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 154,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '503',
  routine: 'ClientAuthentication'
}
```

I expected the service binding operator to do all required setup so that the database can be accessed.

**Comment by pedjak** [comment]
> I expected the service binding operator to do all required setup so that the database can be accessed.

SBO just projects as files a number of bindings exposed by Crunchy Postgres operator and the application/runtime now needs to know where to find and to read them to construct database connection objects. Here is the acceptance tests that verifies what is accessible to the app:

https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/features/supportExistingOperatorBackedServices.feature#L92

in particular thee files:

https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/features/supportExistingOperatorBackedServices.feature#L92

> error: no pg_hba.conf entry for host "10.217.0.194", user "crunchy2", database "crunchy2", SSL off

SBO does not create any `pg_hba.conf` file

What is the application you used? Is it service binding compatible?

**Comment by pedjak** [comment]
> So my complaint is not so much that it does not create a pg_hba.conf but that after having connected the database to the application using the service binding UI, it showing me that it is successfully connected, that the application still cannot connect.

This is then more question for Openshift Console team and UX there.

**Comment by mhdawson** [comment]
@pedjak who should talk to/where would I open an issue to raise it with them?

**Comment by mhdawson** [comment]
@pedjak my other question is if you know how to configure the database through the Crunchy operator/UI to work around this?

**Comment by pedjak** [comment]
> who should talk to/where would I open an issue to raise it with them?

You should report the issue here:
https://github.com/openshift/console/issues

**Comment by mhdawson** [comment]
Ok I figure out what was going on.

I looked at this quick start and was able to see that an application could connect to the database following those instructions, so the question was why was it failing in my case: https://redhat-developer.github.io/service-binding-operator/userguide/getting-started/quick-start.html

The hint ended up being  this part of the error message above: ` SSL off`.  Turns out the crunchy operator is configured to only allow SSL by default. 

Interestingly following the instructions in the quickstart above for Java what gets mapped into the application pd does not give you any way to tell that you should use SSL. I assume that the Java Framework in the quickstart `assumes` that you are going to use SSL...

Luckily when you use the console UI to create the service binding it provides a bunch of extra files, from which you can deduce using SSL is suggested. I've used those to get something that works for kube-service-bindings for both the crunchy and edb operators -  https://github.com/nodeshift/kube-service-bindings/pull/12.

The difference seems to  be that if you use the console UI to create the service binding it sets `detectBindingResources: true` where as if you use the service binding UI that is not in the default set of options shown and unlike `bindAsFiles: true` does not get populated automatically.  Without the extra files provided with `detectBindingResources:true` I don't see any way to tell if SSL should be used or not and I don't know how both SSL and non-SSL autobinding could work.

@pedjak I'm wondering if creation of the service binding in the service binding UI (and maybe if you deploy from command line as well) should be adding `detectBindingResources:true`?  Without that kube-service-bindings will fail to connect because there won't be enough info to know that SSL should be used, and even if it assumed SSL should be used the only option would be to automatically add an option to not reject server certs that could not be validated which I don't think makes sense.

**Comment by pedjak** [comment]
> Interestingly following the instructions in the quickstart above for Java what gets mapped into the application pod does not give you any way to tell that you should use SSL. I assume that the Java Framework in the quickstart assumes that you are going to use SSL..

Hm, the application used in the example is based on the spring framework and it uses the sprint cloud bindings library to read bindings. Here is the code handling Postgres binding:

https://github.com/spring-cloud/spring-cloud-bindings/blob/main/src/main/java/org/springframework/cloud/bindings/boot/PostgreSqlBindingsPropertiesProcessor.java#L45

and it does not expect nor process any certificates. Furthermore, even Crunchy documentation does not say anything particular about them, it just mention that a secret `<cluster-name>-pguser-<cluster-name>` gets created and there are no certificates listed.  `jdbc-url` key in such secret looks like:

```
jdbc:postgresql://hippo-primary.foo.svc:5432/hippo?password=XwuYS0Lr%2F%3A%3Fem%3Cyo%7C0b2cqpw&user=hippo
```

i.e. there is no indication that certificates should be used.

I can confirm that `<cluster-name>-cluster-cert` secret gets created as well, containing the certificates, but they need to be used only when a client wants to verify the connection. I have found in https://access.crunchydata.com/documentation/postgres-operator/5.0.4/tutorial/connect-cluster/ that all connection are configured to be TLS, but they are not speaking about the need to use certificates.

We could expose more keys, certificates as well.. but we can also introduce `provider` key - it is optional by the service binding spec, but it can for example indicate the operator used for provisioning the database - in our case this is `crunchydata`. Based on that, client can know that the connections need to be TLS and act properly. Wdyt @mhdawson ?

**Comment by mhdawson** [comment]
> indicate the operator used for provisioning the database

This might help, but I wonder if it might be possible that the same operator could be configured with/without SSL so depending on that may not be the best way to signal if SSL is used or not.  It may still be useful info to have.

> I have found in https://access.crunchydata.com/documentation/postgres-operator/5.0.4/tutorial/connect-cluster/ that all connection are configured to be TLS, but they are not speaking about the need to use certificates.

What I needed to make the connection work for Node.js
  * That SSL should be enabled
  * The CA cert that should be provided because otherwise Node.js by default rejects server certs that cannot be verified. Since crunchy was using a self-signed certificate I either needed to add the ca cert or configure to not reject if the cert was not validated.  Configuring to not reject does not seem like something I'd want to do automatically.

With `detectBindingResources:true` provided when you using the console UI, there was a ca.crt file that I could used to add the ca cert and decide to use SSL. Since tls.key and tls.crt were also there I could optionally add those if they were there as well.

**Comment by pedjak** [comment]
@mhdawson I have tried to reproduce the issue in #1084 but I was able to connect to the database even without access to the certificates. In our tests we use plain regular `psql` CLI: https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/resources/apps/sbo-generic-test-app/postgres-ready.sh

Anyhow, #1084 exposes `ca.crt`, `tls.crt` and `tls.key`, together with `provider` key as well. I hope it solves the issue on Nodejs side.

**Comment by mhdawson** [comment]
@pedjak thanks, will take a look.

**Comment by mhdawson** [comment]
@pedjak has #1084 made it into an update of the service binding operator? I looked at what I have installed and it says I'm up to date but I don't think there was an update since I installed since the name still says 1.0.0.

Just trying to see how I test out if #1084 resolve the issue I was having

**Comment by pedjak** [comment]
@mhdawson we still did not release any new version, but you can try the latest master code by creating a catalog source from the following index image:

```
quay.io/redhat-developer/servicebinding-operator:index
```

and installing SBO from it. 

[install.sh](https://github.com/redhat-developer/service-binding-operator/blob/master/install.sh) script in our project root does that all for you if you invoke it as:

```sh
OPERATOR_INDEX_IMAGE=quay.io/redhat-developer/servicebinding-operator:index ./install.sh
```
