### ISSUE TITLE
Rabbitmq/service binding operator

### ISSUE THREAD

**Issue by mhdawson** [redhat-developer/service-binding-operator#1110]
### What is the SBO version used?
1.0

### What are the steps to reproduce this issue?
  1. follow instructions in 
  2. https://github.com/rabbitmq/cluster-operator
  3. Bind it to an application with:
```yaml
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  annotations:
    servicebinding.io/requester: >-
      {"username":"kubeadmin","uid":"ed0e6892-3fbb-487d-b1bb-d3718fa4d834","groups":["system:authenticated:oauth","system:authenticated"],"extra":{"scopes.authorization.openshift.io":["user:full"]}}
  resourceVersion: '183274'
  name: rabbit-to-worker
  uid: 0ddee6fa-8357-40b0-a46e-db0912de36e1
  creationTimestamp: '2022-03-04T21:16:23Z'
  generation: 1
  managedFields:
    - apiVersion: binding.operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:application':
            .: {}
            'f:group': {}
            'f:kind': {}
            'f:name': {}
            'f:version': {}
          'f:bindAsFiles': {}
          'f:services': {}
      manager: Mozilla
      operation: Update
      time: '2022-03-04T21:16:23Z'
    - apiVersion: binding.operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"finalizer.servicebinding.openshift.io"': {}
      manager: manager
      operation: Update
      time: '2022-03-04T21:16:23Z'
    - apiVersion: binding.operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions':
            .: {}
            'k:{"type":"CollectionReady"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"InjectionReady"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:secret': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2022-03-04T21:17:45Z'
  namespace: test
  finalizers:
    - finalizer.servicebinding.openshift.io
spec:
  application:
    group: apps.openshift.io
    kind: DeploymentConfig
    name: nodejs-messaging-work-queue-worker
    version: v1
  bindAsFiles: true
  services:
    - group: rabbitmq.com
      kind: RabbitmqCluster
      name: hello-world
      version: v1beta1
```

### What is the expected behaviour?
The type matches the "protocol" that the client can use to connect. For example kafka, redis, amqp, etc.

### What is the actual behaviour?
Instead it reports rabbitmq which I don't think is a protocol. rabbitmq support a number of protocols. the provider reports rabbitmq which makes sense so that the app can know the specific provider.

Since it supports a number of protocols though, the question might then be which one should it report?

Has this situation been though through, documented as to how it should work. ie 1 provider supports a number of protocols?  Is there a way in the service binding to override the type so that I can set the type to the protocol that should be used?

**Comment by mhdawson** [comment]
To add some additional context, what I expected is that I can write an application that knows it's going to use AMQP, and then map in any provider/backend that support AMQP and get the same info bound into the environment. In that way my application is not tied to a specific back end and the admins can swap out the provider without the application code needing to change.

**Comment by sadlerap** [comment]
We hand off the `type` field from RabbitMQ's service binding information; in this case, we're getting it from their provisioned service secret.  I did some digging around in their documentation/code, but I didn't see a lot there that addressed this use case; it looks like [RabbitMQ exposes `type=rabbitmq` unconditionally](https://github.com/rabbitmq/cluster-operator/blob/main/internal/resource/default_user_secret.go#L72).

> Has this situation been though through, documented as to how it should work. ie 1 provider supports a number of protocols? Is there a way in the service binding to override the type so that I can set the type to the protocol that should be used?

We've started to give this some thought, yes.  We're likely going to represent these different endpoints as separate custom resources that we can bind applications to (i.e. they support the [provisioned service](https://github.com/servicebinding/spec/#provisioned-service) standard).  It's still early days, and a lot of the effort to get operators on board with this has yet to be done.

* * *

As a more immediate workaround for your situation, I think the simplest thing you can do is use an annotation to override rabbitmq's `type` field.  Apply this annotation to your rabbitmq custom resource (or its CRD to apply it globally):
```
service.binding/type: amqp # or whichever protocol you support
```
This does have the drawback that every client for that rabbitmq cluster needs to speak the same protocol, which may or may not be acceptable.

cc: @dperaza4dustbit

**Comment by mhdawson** [comment]
@sadlerap thanks for the quick response and for a work around we can use.

It's good to know you are working through how 1 provider with multiple protocols will work. 

I've also come up with a work around on the kube-service-bindings side (aliasing rabbitmq to amqp) but it only works if you assume that rabbit will provide all protocols its supports versus only those currently enabled.

Your forward path of being able to bind separately for each protocol makes sense as that will let the binding set the type to the appropriate protocol.

**Comment by baijum** [comment]
Values for `type` and `provider` can be overridden from [ServiceBinding](https://github.com/servicebinding/spec/#service-binding) resource.

**Comment by Kartikey-star** [comment]
@mhdawson  does the solution provided above makes sense to you.

**Comment by mhdawson** [comment]
@Kartikey-star we came up with a work around in kube-service-bindings were we map rabbit to AMQP, but I still think the model on the service binding side should be adjusted to reflect protocol being offered (possibly many) versus a specific provider type.

**Comment by pmacik** [comment]
@mhdawson Thanks, closing
