### ISSUE TITLE
How do we watch CRs which are registered post  SBR operator install?

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#142]
To 'manage' the binding, we _could_ watch changes to the "BackingService" CR. However, watches are added at the controller boot time - and you can't anticipate what is to be added.

If you did anticipate ( from the OperatorSource ) or some static list, you still wouldn't be able to do a 

```

	gvk := schema.GroupVersionKind{
		Group:   "baiju",
		Version: "valpha1",
		Kind:    "databases",
	}

	objRuntime, _ := scheme.NewUnstructuredCreator().New(gvk)

	err = c.Watch(&source.Kind{Type: objRuntime}, handler)

```

This would return an error:
```
{"level":"error","ts":1566413911.0931442,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"databases.g1","error":"no matches for kind \"databases\" in version \"g1/valpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.add\n\t/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/controller.go:95\ngithub.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest.Add\n\t/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebindingrequest/controller.go:31\ngithub.com/redhat-developer/service-binding-operator/pkg/controller.AddToManager\n\t/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/pkg/controller/controller.go:13\nmain.main\n\t/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/cmd/manager/main.go:122\nruntime.main\n\t/usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:200"}
```

Unless the CRD was installed before the ServiceBindingRequest operator is installed

**Comment by sbose78** [comment]
@isutton @ron1 @otaviof

**Comment by ron1** [comment]
I suspect the service-binding-operator should restart itself when it discovers that one of its SBR CRs has a BackingService CRD that it does not recognize. It seems reasonable to treat this as an error condition and terminate, allowing its managing Deployment to restart it. You might want to ask the question at https://groups.google.com/forum/#!forum/operator-framework. I suspect this issue is not unique to the service-binding-operator.

**Comment by sbose78** [comment]
> discovers that one of its SBR CRs has a BackingService CRD

It would probably be able to talk to it. But it wouldn't have a `watch` on it since watches need prior registration. :)

Any idea how to terminate a controller pod so that a new one rises ?

**Comment by ldimaggi** [comment]
Is it constantly polling for new/unrecognized CRDs? At what time intervals? Thx!

**Comment by sbose78** [comment]
@ldimaggi , No on receipt of a ServiceBindingRequest, the controller might need to watch the new Backing Service CR

**Comment by otaviof** [comment]
@ron1 I like the approach you suggest with terminate the controller when an unrecognized CR has pop up.
> It seems reasonable to treat this as an error condition and terminate

@sbose78 in this case, we expect k8s itself to bring back the operator pod, so from the code-base we only need to `exit`
> Any idea how to terminate a controller pod so that a new one rises ?

**Comment by otaviof** [comment]
@sbose78 We also need to remember that before watching a GVK/GVR a `ServiceBindingRequest` must have been successful. In other words, the `SBR` must have found the GVK/GVR to make the operation happen, and therefore, when we start watching for GVK/GVRs is logical to expect that they will exist.
So, in the case of watching over specific resource types, do you think that's a valid assumption to work with?
> Unless the CRD was installed before the ServiceBindingRequest operator is installed

**Comment by sbose78** [comment]
> in other words, the SBR must have found the GVK/GVR to make the operation happen
Yes!

> when we start watching for GVK/GVRs is logical to expect that they will exist.
yes!

**Comment by sbose78** [comment]
Hi @otaviof @ron1  @ldimaggi  and @isutton  I've implemented the "dynamically watch more CRDs" - could you please review ?  #144

Note: It needs general cleanup but I've tested the functionality.
