### ISSUE TITLE
Consolidate application object updates from different SBRs

### ISSUE THREAD

**Issue by ron1** [redhat-developer/service-binding-operator#160]
I have an application that binds to numerous backing services. Assume the SBRs for this application are created in succession from a single YAML file. Especially when initially deploying this application, it would be most efficient if the application object updates from the different SBRs were consolidated into a single update. In the service-binding-operator SBR reconciliation loop, consider sorting by application object and consolidating updates by application object.

**Comment by DhritiShikhar** [comment]
@ron1 +1 This is an efficient approach.

**Comment by ldimaggi** [comment]
That would help in avoiding cascading updates - good suggestion!

**Comment by pedjak** [comment]
Closing, please reopen if still relevant.
