### ISSUE TITLE
CRD is missing resourceRef in the applicationSelector

### ISSUE THREAD

**Issue by pmacik** [redhat-developer/service-binding-operator#187]
The [`resourceRef`](https://github.com/redhat-developer/service-binding-operator/blob/61f688a71f3a9664e517c78e0fa28bc2187028a6/pkg/apis/apps/v1alpha1/servicebindingrequest_types.go#L72) field is part of the `applicationSelector` API but it is missing in the either of the CRDs:
* https://github.com/redhat-developer/service-binding-operator/blob/61f688a71f3a9664e517c78e0fa28bc2187028a6/deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml#L35
* https://github.com/redhat-developer/service-binding-operator/blob/61f688a71f3a9664e517c78e0fa28bc2187028a6/manifests/service-binding-operator.servicebindingrequests.crd.yaml#L37

This affects the `v0.0.20` release.

**Comment by DhritiShikhar** [comment]
@pmacik `resourceRef` is present under `deploy/` directory CRD. Please refer -> https://github.com/redhat-developer/service-binding-operator/blob/master/deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml#L65

And this is the PR to add `resourceRef` in manifest CRD -> https://github.com/redhat-developer/service-binding-operator/pull/211
