### ISSUE TITLE
Feature: Add support of adding configmap name dynamically.

### ISSUE THREAD

**Issue by akashshinde** [redhat-developer/service-binding-operator#222]
### What is currently supported 
```
 servicebindingoperator.redhat.io/status.dbConfigMap-db.host: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.port: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.name: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.user: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.password: 'binding:env:object:configmap'

```
Here 'dbConfig' is the hard coded configmap name. 

### What should be supported 
I have came across one scenario where above configmap name(dbConfigMap) gets dynamically generated. 
### Operator Used 
Cruncydata's Postgres operator - 
**OperatorHub** - https://operatorhub.io/operator/postgresql 
**Github URL** - https://github.com/CrunchyData/postgres-operator 

This operator generates secret with a name in following format  _${CR_NAME}__POSTGRES_SECRETS_

**Comment by sbose78** [comment]
Sorry, I didn't get what the request exactly is. Are you saying that we should detect resources prefixed by th CR name?

**Comment by isutton** [comment]
I'm not sure whether having a dynamic placeholder in there is what we want, but I'm still intrigued.

What do you mean by "gets dynamically generated"? Can you give another example?

My take on this is that, I believe at the time the ServiceBindingRequest author gets to write the manifest, the generated secret has already been created by the operator. Whenever the application changes, by requiring another database for example, the SBR manifest should be updated accordingly to reflect this new dependency, and this will trigger the SBR reconciliation process.

The annotation would look like the following if I didn't miss anything: `servicebindingoperator.redhat.io/status._mydatabase_POSTGRES_SECRETS-db.user: 'binding:env:object:secret'`.

**Comment by isutton** [comment]
Is there something we can do here, or should we close this issue?
