### ISSUE TITLE
Example applications' ServiceBindingRequests require updates

### ISSUE THREAD

**Issue by ldimaggi** [redhat-developer/service-binding-operator#255]
The references to labels should be replaced with ResourceRef's as provided here:

https://github.com/redhat-developer/service-binding-operator/pull/173

**Comment by DhritiShikhar** [comment]
@ldimaggi Thanks for creating an issue for this. I will take this up.

/assign @DhritiShikhar

**Comment by ldimaggi** [comment]
See:  https://github.com/redhat-developer/service-binding-operator/pull/259

Other changes were needed too, in order to stay in sync with OpenShift 4.3
