### ISSUE TITLE
Service Binding Operator is in Operatorhub - but it is not listed in a category

### ISSUE THREAD

**Issue by ldimaggi** [redhat-developer/service-binding-operator#261]
The Service Binding Operator is now in the local Operatorhub - https://console-openshift-console.apps.clustername.devcluster.openshift.com/operatorhub/ns/openshift-operators - but it is not included in the "other" category.

The only way a user can find it is to filter on all operators:
![Screenshot from 2019-11-26 09-34-00](https://user-images.githubusercontent.com/642621/69642768-488e9580-1030-11ea-8601-27af68269290.png)

**Comment by sbose78** [comment]
@DhritiShikhar Could you look into this, please?

**Comment by DhritiShikhar** [comment]
Yes

**Comment by DhritiShikhar** [comment]
@sbose78 @ldimaggi I would be adding `Service Binding Operator` under `Integration & Delivery` category. 

Is that okay?

Refer -> https://github.com/operator-framework/community-operators/blob/master/docs/required-fields.md#categories

**Comment by ldimaggi** [comment]
+1 Yes - that looks good - (adding the Service Binding Operator under Integration & Delivery).

If the operator is not in a category, then it is difficult to find thru filtering. Thx!

**Comment by sbose78** [comment]
What about a developer tools category, if multiple are allowed?

**Comment by DhritiShikhar** [comment]
Sure, So 3 categories:
[1] Developer Tools
[2] Integration & Delivery
[3] Openshift Optional

**Comment by DhritiShikhar** [comment]
PR -> https://github.com/operator-framework/community-operators/pull/1147
