### ISSUE TITLE
Backing Service CRD Annotation parsing error 

### ISSUE THREAD

**Issue by pdettori** [redhat-developer/service-binding-operator#270]
I am running the service binding operator from master (b0c9641574269f58b6126a406bace6a4b2c07afd on Dec 5) and using `make local` to run. When I try to run the example in `examples/nodejs_postgresql` I get the following error:

```
2019-12-06T11:43:38.954-0500    ERROR   controller-runtime.controller   Reconciler error        {"controller": "servicebindingrequest-controller", "request": "service-binding-demo/binding-request", "error": "should have two parts"}
```

from what I can see the error originates in `olm.go`, in the following part of the code:

```Golang
func splitBindingInfo(s string) (string, string, error) {
	parts := strings.SplitN(s, "-", 2)

	if len(parts) != 2 {
		return "", "", fmt.Errorf("should have two parts")
	}

	return parts[0], parts[1], nil
}
```

When I added some debugging print, I noticed that some strings have the `-` but some don't, and that is where the issue occurs, for example:

```
status.dbConfigMap-db.host
status.dbConfigMap-db.user
status.dbConnectionIP. <- this where the error happens
```

It seems I can get past that error if I replace the line `parts := strings.SplitN(s, "-", 2)` with `parts := strings.SplitN(s, ".", 2)`, however I am not clear on what what the intent for `splitBindingInfo` is and if this makes sense.

**Comment by sbose78** [comment]
Let me check, Paolo.

**Comment by isutton** [comment]
Thanks for raising  this issue, Paolo. 

@sbose78 I'll create an internal task referring this issue to review and document the annotations' contracts we have in place; I believe it was changed but the examples haven't been updated.

@otaviof Do you think "example applications should be reviewed and updated accordingly" can and should be added in the Definition of Done document we've been discussing?

**Comment by sbose78** [comment]
@pdettori , this is the fix https://github.com/redhat-developer/service-binding-operator/pull/279

status.dbConfigMap-db.host --> means, that dbConfigMap is potentially referring to a secret/configmap whose `host` key is meaningful.

status.dbConnectionIP  -->  implies that it refers to a string.

The parsing logic was broken during a recent refactor https://github.com/redhat-developer/service-binding-operator/pull/249/files#diff-afc354676cb222be0b0a0cf0dee67561R232

**Comment by sbose78** [comment]
The most recent upstream image which didn't have this bug was `quay.io/redhat-developer/app-binding-operator:v0.0.23`

**Comment by sbose78** [comment]
> I believe it was changed but the examples haven't been updated.

The examples are fine, master is broken.

**Comment by pdettori** [comment]
@sbose78 thanks, I will try the fix. Is there some description of constraints on the names of parameters used in annotations ? Can names contain the `-` character ?

**Comment by pdettori** [comment]
I tested the fix on branch isutton/GH-270. It seems to work (I get past that point) but I still run into #271 (when I try without `customEnvVar` ) and #272 (when I use `customEnvVar`).

**Comment by sbose78** [comment]
Fixed and merged https://github.com/redhat-developer/service-binding-operator/pull/279
