### ISSUE TITLE
Include negative test to track error if user has bound the same backing service more than once

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#276]
This comment is to late as the PR has been merged - but - an interesting negative test would be to track the error (if any returned) if a user inadvertently bound the same backing service more than once.

_Originally posted by @ldimaggi in https://github.com/redhat-developer/service-binding-operator/pull/274#issuecomment-563482179_

**Comment by baijum** [comment]
Service binding operator supports connecting to the same backing service by more than one application, right? I am not getting the "inadvertently bound the same backing service more than once."

@ldimaggi Can you please explain this.

**Comment by ldimaggi** [comment]
> Service binding operator supports connecting to the same backing service by more than one application, right? I am not getting the "inadvertently bound the same backing service more than once."
> 
> @ldimaggi Can you please explain this.

I assumed that creating multiple/duplicate connections between one application and one service would be flagged as an error. Is this not the case? Thx!

**Comment by otaviof** [comment]
> I assumed that creating multiple/duplicate connections between one application and one service would be flagged as an error. Is this not the case? Thx!

I don't think so, @ldimaggi . Please consider internal issue [APPSVC-304](https://issues.redhat.com/browse/APPSVC-304). (cc @baijum)

**Comment by ldimaggi** [comment]
Just confirm, we are NOT supporting users in creating duplicate bindings (that is, multiple bindings from one application to the same service), correct? Do we report an error is a user, inadvertently or otherwise, creates a duplicate binding?

**Comment by isutton** [comment]
> Just confirm, we are NOT supporting users in creating duplicate bindings (that is, multiple bindings from one application to the same service), correct? Do we report an error is a user, inadvertently or otherwise, creates a duplicate binding?

Currently you have one application selector and one backing service selector. Once we support multiple backing services, we will propagate any issue as a condition in `status.conditions`.

**Comment by pedjak** [comment]
Closing as obsolete.
