### ISSUE TITLE
Multiple Duplicate finalizers for Service Binding Request

### ISSUE THREAD

**Issue by pdettori** [redhat-developer/service-binding-operator#287]
I am running with the latest master, and I have noticed that the first time that I apply a SBR and the reconciliation runs, I can see the following finalizers applied:
```
finalizers:
  - finalizer.servicebindingrequest.openshift.io
  - finalizer.servicebindingrequest.openshift.io
```
If I edit the SBR, and apply again, the finalizer become:
```
finalizers:
  - finalizer.servicebindingrequest.openshift.io
  - finalizer.servicebindingrequest.openshift.io
  - finalizer.servicebindingrequest.openshift.io
  - finalizer.servicebindingrequest.openshift.io
```
I repeated a third time and the list grew by two more. And so on. This does not seem to impact functionality but it seems like a possible bug with finalizers handling in the operator.

**Comment by otaviof** [comment]
@pdettori indeed, that's a left over from #256. It should not cause any functional issues, while we address this.

**Comment by otaviof** [comment]
Closing this issue, after merging #289.
