### ISSUE TITLE
Is it possible to opt out from injecting environment variables?

### ISSUE THREAD

**Issue by navidsh** [redhat-developer/service-binding-operator#296]
Edit by Shoubhik 
Jira https://issues.redhat.com/browse/APPSVC-9

---

Is it possible to skip the "injecting environment variable" step after the controller created service binding secrets?

We are looking into integrating [Appsody Operator](https://github.com/appsody/appsody-operator/) with Service Binding Operator, and we want our operator to be in charge of modifying the resources (e.g. `Deployment`, `StatefulSet`) created by the Appsody operator to run users' applications.

**Comment by sbose78** [comment]
Heya!


> Is it possible to skip the "injecting environment variable" step after the controller created service binding secrets?

We have a task on our planning board to only generate a managed secret which we never got to :) 


> Just to throw it out there, if applicationSelector is not defined in ServiceBindingRequest, SBO skips the injection.

You mean, it already works? That would be an intended feature then :)

**Comment by navidsh** [comment]
> We have a task on our planning board to only only generate a managed secret which we never got to :)

Nice! Is there any timeline of when it will be implemented?

> You mean, it already works? That would be an unintended feature then :)

No, I think specifying `applicationSelector` is required now. I meant one way to do it is by not defining `applicationSelector` in the CR :)

**Comment by sbose78** [comment]
I'll move it up the board, @navidsh .

@DhritiShikhar Could you start working on https://issues.redhat.com/browse/APPSVC-9 again :) , do have a chat with @isutton to avoid conflicts since there's a major refactoring happening in https://github.com/redhat-developer/service-binding-operator/pull/293 / https://github.com/redhat-developer/service-binding-operator/pull/286 .

**Comment by sbose78** [comment]
Created a public copy of the feature request/story https://github.com/redhat-developer/service-binding-operator/issues/297

**Comment by navidsh** [comment]
@sbose78 Thank you very much!

**Comment by arthurdm** [comment]
thx guys!  this will allow for a seamless integration.  👍

**Comment by sbose78** [comment]
Update:

We merged https://github.com/redhat-developer/service-binding-operator/pull/293 which had refactoring to support multiple backing CRs ( example: PostgreSQLService CR and a PostreSQLCredential CR ) ). 

As far as I remember, this was one of the use cases in some of the IBM operators which could be used as backing services.

**Comment by sbose78** [comment]
@DhritiShikhar is working on this, and should have a PR this week.

**Comment by arthurdm** [comment]
awesome, thanks guys.

**Comment by sbose78** [comment]
Work is in progress https://github.com/redhat-developer/service-binding-operator/pull/350

**Comment by Avni-Sharma** [comment]
#350 is merged. @DhritiShikhar shall we close this issue?

**Comment by DhritiShikhar** [comment]
Yes
