### ISSUE TITLE
Support Application and BackingService in different namespaces

### ISSUE THREAD

**Issue by Jamstah** [redhat-developer/service-binding-operator#314]
We have the requirement to be able to connect a BackingService in one namespace and an Application in another.

Is there a way to handle this already? If not, can we extend the spec to allow this? The binding secret would need to be created in the Application namespace, but I don't see a reason that wouldn't work.

**Comment by sbose78** [comment]
This is definitely valuable. 

I do wonder if that lets a user do a privilege escalation to the Application namespace?

**Comment by sbose78** [comment]
Should be fairly easy to add this https://github.com/redhat-developer/service-binding-operator/pull/315

**Comment by Jamstah** [comment]
Thanks!

I was imaging we'd need some sort of RBAC on creating the bindings, rather than on being able to modify the replicasets. I agree there is a security concern, but as you say, it already exists for single namespace.

I see in your PR you're adding a namespace to the app selector, I was actually thinking of the other way around, adding it to the BackingService selector, so an app can create the binding it needs to a service in another namespace.

I suppose access to create a SBR in the namespace of the service itself granted by RBAC might be the best way to keep the service itself secure, and allow specific accounts to bind as granted by the admin. Either way, we are allowing one namespace to interfere with another, so I agree it needs to be handled with care.

**Comment by sbose78** [comment]
Agreed.

We could potentially support specification of namespaces for both the application and the backing service.
The "managed" binding token could live close to the app. Let me modify my PR ( and add tests..)

**Comment by isutton** [comment]
Hi Shoubhik,

Can you create a document to capture your ideas to discuss in a Cabal
session?

Igor.

**Comment by sbose78** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/346 Testing this out.
