### ISSUE TITLE
Upstream-friendly API Group of the ServiceBindingRequest CRD

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#364]
We spoke about this idea in one of the [PRs](https://github.com/redhat-developer/service-binding-operator/pull/348#issuecomment-592529402), so placing it into its own issue.

It would be good to update the apiVersion from `apps.openshift.io/v1alpha1` into something that is neutral to OpenShift.

**Comment by arthurdm** [comment]
A suggestion: `service.binding/v1alpha1`.

**Comment by sbose78** [comment]
+1 
Suggestion sounds nice. I'll check with operator-framework folks too on the group name.

**Comment by ZhuangYuZY** [comment]
It is great to help to adopt service binding CRD to run on other k8s cluster. Thank you.

**Comment by ron1** [comment]
Would an API Group name such as `redhatdeveloper.redhat.io` or `redhatdev.redhat.io` be more frictionless? Is including "developer" or "dev" in the API Group name too restrictive?

There is already precedent for such a naming scheme with repo `github.com/redhat-cop` mapping to API Group `redhatcop.redhat.io`. It would be great to get this renaming committed sooner than later.

**Comment by ianpartridge** [comment]
As the `ServiceBinding[Request]` CRD is intended to be used in conjunction with non Red Hat binding targets/services, I think we should avoid mentioning Red Hat in the API.

**Comment by sbose78** [comment]
@redhat-developer/service-binding could you do a final weighing in on this, and agree on the group and kind?

**Comment by baijum** [comment]
The kind name `ServiceBinding` looks good. A generic group like `service.binding` is also fine.

**Comment by Avni-Sharma** [comment]
> The kind name `ServiceBinding` looks good. A generic group like `service.binding` is also fine.

+1

**Comment by pedjak** [comment]
With the recent API refactoring (https://github.com/redhat-developer/service-binding-operator/pull/608), the group got updated to `operators.coreos.com`
