### ISSUE TITLE
Update CRD Kind to ServiceBinding

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#365]
As suggested by @pdettori [here](https://github.com/redhat-developer/service-binding-operator/pull/348#issuecomment-592202458), it would be nice to use `ServiceBinding` for the CRD kind.

**Comment by ianpartridge** [comment]
Agreed. Kubernetes resources are declarative (Deployment not DeploymentRequest).

**Comment by sbose78** [comment]
+1. 

History:
During the initial days, we wanted to avoid confusion with Service Catalog's Service Binding which led us to choose ServiceBindingIntent or ServiceBindingRequest. 

We've come a full circle and I agree `ServiceBinding` looks right.

**Comment by pdettori** [comment]
+1 
Happy to see agreement around this!

**Comment by DhritiShikhar** [comment]
This is done.
