### ISSUE TITLE
Cannot build master locally

### ISSUE THREAD

**Issue by metacosm** [redhat-developer/service-binding-operator#374]
- `go version go1.14 darwin/amd64`
- `go build cmd/manager/main.go` 
```
go: downloading github.com/openshift/api v3.9.1-0.20190924102528-32369d4db2ad+incompatible
cmd/manager/main.go:11:2: github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
```

**Comment by sbose78** [comment]
@metacosm Did the meeting with @DhritiShikhar & @Avni-Sharma help resolve this?

**Comment by metacosm** [comment]
@sbose78 no, it didn't, unfortunately…

**Comment by isutton** [comment]
If you're using Fedora and Fedora's golang package, you need to configure
the proxy related environment variables that are currently disabled during
packaging.

Try setting GOPROXY to https://proxy.golang.org,direct.

**Comment by metacosm** [comment]
I retried again today and I can now build the code without having changed anything… Weird.
