### ISSUE TITLE
Why are many dependencies defined with `v0.0.0` version?

### ISSUE THREAD

**Issue by metacosm** [redhat-developer/service-binding-operator#376]
I understand that there are associated `replace` directives, however this makes it very difficult to try to use the project types in a different project, in particular if one is trying to generate service binding request programmatically. Relates to #375.

**Comment by sbose78** [comment]
@pedjak do you want to address this?

**Comment by pedjak** [comment]
Addressed in https://github.com/redhat-developer/service-binding-operator/pull/839
