### ISSUE TITLE
Make service-binding-operator work on vanilla k8s

### ISSUE THREAD

**Issue by ZhuangYuZY** [redhat-developer/service-binding-operator#385]
Now service-binding-operator is working together with OpenShift OLM, it is hard dependency. 

Based on email discussion, @sbose78 agree with it (copy his statement below). Thank you.

```
Making Service Binding Operator work independent of OLM as well, has been a goal for a while. We've made some progress but need to make a lot more.
1. We started with looking up CSV descriptors to find out what is interesting for binding ( needs OLM ).

https://github.com/operator-backing-service-samples/postgresql-operator/blob/master/manifests/nightly/postgresql-operator.v0.0.9.clusterserviceversion.yaml#L168
2. We added support for CRD annotations as a way to find out what is interesting for binding ( doesn't need OLM, in theory ). 

https://github.com/application-stacks/service-binding-specification

3. We are also going to add support for reading "what is interesting for binding" from any kubernetes resources or CR ( doesn't need OLM, in theory ).
https://github.com/redhat-developer/service-binding-operator/pull/367
Having said that, some code changes need to be done such that we are able to run binding error-free where OLM isn't there. That's the goal we haven't gotten to yet. 
```

@sbose78 I am glad to work with on this issue. My team will work on design and submit PR for this issue.  Do you have anything initial thinking for design, how to remove the dependency with OLM, it will help us to get align quickly ? 
Thank you.

**Comment by sbose78** [comment]
Before getting into details, I would say 
* OLM is more of a soft-dependency
* OLM is not specific to OpenShift, Kubernetes is its primary target.

#### "What is interesting for binding in a backing service" can today be defined in two ways
* OLM descriptors, and/or
* CRD annotations
* Annotations on any Kubernetes resource https://github.com/redhat-developer/service-binding-operator/pull/367

#### Support status

☑Service Binding on OpenShift with OLM
☑Service Binding on Kubernetes with OLM - **should work in theory, needs testing**
⚪️Service Binding on Kubernetes without OLM - should work if error scenarios when OLM objects are absent are handled well. 


We watch changes to
- clusterserviceversion objects "react if a new CSV is added to the cluster / existing backing service CRD's descriptors change"
- all CRDs/types specified in csv objects "react if backing service CR changes"
- some openshift specific objects like `routes` 

We may need a bit of cleanup to ensure that if above types are absent, we should gracefully assume that we are running on kubernetes with no-OLM.

I'll add links to the code where things need to be done a bit differently.

Ideally, a CRD, not managed by OLM should carry annotations and the operator should behave perfectly.

**Comment by ZhuangYuZY** [comment]
Sure, I already get a developer starting on this. Thank you.

**Comment by sbose78** [comment]
@arthurdm Could you please track this issue in https://github.com/application-stacks/service-binding-specification/issues/16#issuecomment-605309629 ?

**Comment by sbose78** [comment]
As per confirmation in https://github.com/redhat-developer/service-binding-operator/pull/397#issuecomment-604184956 , closing this.

Thank you very much @ZhuangYuZY !

**Comment by ZhuangYuZY** [comment]
And thank you very much to @int8dev

**Comment by arthurdm** [comment]
yup - added @sbose78!
