### ISSUE TITLE
Expose a list of bindable services

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#399]
There's a desired to offer equivalent capability to `odo catalog list services`, but using SBO as the entity that can find bindable services and bind to them.

We started this discussion at the spec level via this [PR](https://github.com/application-stacks/service-binding-specification/pull/9), but work would still be needed in SBO to expose such a list and their corresponding ServiceBinding CR skeletons.

**Comment by Avni-Sharma** [comment]
So basically it is not only `listing` of the services but also the `modification` of the service binding request (CR) upon finding the annotation `servicebinding/bindable: "true"` ?

**Comment by arthurdm** [comment]
I think if the `list` result provides the data in a way that's easily consumable for the caller (i.e. `odo`, or another tool),then SBO doesn't actually have to modify any resources.

What I had in mind is:  a way to query SBO for the bindable services and get a response such as:

```
    - group: postgres.dev
      kind: Service
      resourceRef: user-db
      version: v1beta1
    - group: postgres.dev
      kind: Credentials
      resourceRef: admin-creds
      version: v1beta1
```

then that's something that could be pushed into a ServiceBinding CR as-is (by tools other than SBO).

**Comment by pedjak** [comment]
How about following approach:

* Watch for `CustomResourceDefinition` changes, and try to find servicebinding annotatons, or figure out if CRD defines a provisioned services. If CRD is owned by a ClusterServiceVersion, check if service binding descriptors are defined. In case of match, set an annotation on CRD indicating that CRs are potentially bindable:

```
service.binding/bindable: true
```

* Provide an endpoint served by SBO that confirm if a resource is bindable for a given resource referrence
* Provide the endpoint logic in a form of Golang function that could be embedded into 3rd party tooling/clients.

**Comment by pedjak** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/1036 got merged and now SBO reports bindable resource kinds, so that clients can figure out if there bindable services of a given kind in a namespace.

**Comment by baijum** [comment]
> #1036 got merged and now SBO reports bindable resource kinds, so that clients can figure out if there bindable services of a given kind in a namespace.

Closing the issue as 1.0.0 has these changes.
