### ISSUE TITLE
Adoption of annotations from specification

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#403]
The [section](https://github.com/k8s-service-bindings/spec#binding-secret-generation-strategies) of the service binding specification that describes the `x-descriptors` and `annotations` that a service should use to be bindable uses slightly different names than what SBO supports today.

A proposal is:
* start supporting the annotations from the spec
* document that SBO is deprecating the usage of its old annotations described [here](https://github.com/redhat-developer/service-binding-operator/blob/master/docs/OperatorBestPractices.md#making-an-operator-managed-backing-service-bindable), but continue to use it for a release or two to give time for migration of any existing services.

This is an important item to get adoption of the spec, since we're starting to reach out to services (Strimzi, Postgresql, etc) to make them more bindable.

**Comment by sbose78** [comment]
Thanks, let me follow-up with a "before" and "after" of the annotations.

**Comment by sbose78** [comment]
@Avni-Sharma Could you please review the spec and provide an example of how the new annotations would look like for https://github.com/operator-backing-service-samples/postgresql-operator ?
```
2. Non-OLM Operator: - An annotation in the Operator's CRD to mark which `status` properties reference the [binding data](#service-binding-schema).  The value of this annotation can be specified in either [JSONPath](https://kubernetes.io/docs/reference/kubectl/jsonpath/) or [GO templates](https://golang.org/pkg/text/template/):
      * ConfigMap:
        * servicebinding/configMap: {.status.bindable.ConfigMap}
      * Secret:
        * servicebinding/secret: {.status.bindable.Secret}
      * Individual binding items:
        * servicebinding/secret/host: {.status.address}
        * servicebinding/secret/`<binding_property>`: {.status.`<status_property>}` (where `<binding_property>` is any property from the binding schema, and `<status_property>` refers to the path to the correspoding `status` property)
```

**Comment by Avni-Sharma** [comment]
Currently, the annotations are like 
```
    servicebindingoperator.redhat.io/spec.dbName: 'binding:env:attribute'
    servicebindingoperator.redhat.io/status.dbCredentials-user: 'binding:env:object:secret'
    servicebindingoperator.redhat.io/status.dbCredentials-password: 'binding:env:object:secret'
    servicebindingoperator.redhat.io/status.dbConnectionIP: 'binding:env:attribute'
    servicebindingoperator.redhat.io/status.dbConnectionPort: 'binding:env:attribute'
    servicebindingoperator.redhat.io/status.dbName: 'binding:env:attribute'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.host: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.port: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.name: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.user: 'binding:env:object:configmap'
    servicebindingoperator.redhat.io/status.dbConfigMap-db.password: 'binding:env:object:configmap'
```
In the current scenario we have the `env` option when we need to inject the bindable data as an environment variable. That can also be changed to `volumemount` incase we need to have data as a volumemount. In the spec [https://github.com/application-stacks/service-binding-specification/tree/updateSchema#pointer-to-binding-data] we have not used it. Are we planning to drop the `env/volumemount` option altogether?

**Comment by arthurdm** [comment]
hi @Avni-Sharma - I have opened [this issue](https://github.com/application-stacks/service-binding-specification/issues/15) in the spec side to also support environment variables.  I was convinced that in cases of non-sensitive data it's still a very practical and used method.  =)

**Comment by Avni-Sharma** [comment]
Reference - https://github.com/application-stacks/service-binding-specification/pull/25

**Comment by otaviof** [comment]
Community meeting notes:
- Pressuring point to avoid supporting two different annotations sets
- Relates to PR #407

**Comment by arthurdm** [comment]
@isutton / @sbose78 - we could use this issue to lay out the plan and divide-and-conquer in terms of resources?

**Comment by isutton** [comment]
@Avni-Sharma will be implementing this with my collaboration.

The plan so far is, with the changes introduced in #407 :

* Modify [`annotations.BuildHandler`](https://github.com/isutton/service-binding-operator/blob/179c2fb40bb274eeacace087320b00154a6d0e48/pkg/controller/servicebindingrequest/annotations/annotations.go#L66-L91) to support the new annotations;
* Implement a predicate similar to [`IsConfigMap`](https://github.com/isutton/service-binding-operator/blob/179c2fb40bb274eeacace087320b00154a6d0e48/pkg/controller/servicebindingrequest/annotations/configmap.go#L10-L15) to build the right annotation handler; and
* Implement a type consuming [`annotations.Handler`](https://github.com/isutton/service-binding-operator/blob/179c2fb40bb274eeacace087320b00154a6d0e48/pkg/controller/servicebindingrequest/annotations/annotations.go#L47-L50), which will be returned by `annotations.BuildHandler`. The implementation will provide the `Handle` method which is responsible to create a `annotation.Result` value (this is the type that should be adapted to provide the new annotation semantics.

I currently don't believe it is necessary to have more hands on the deck for this.

What do y'all think?

**Comment by Avni-Sharma** [comment]
Support added in https://github.com/redhat-developer/service-binding-operator/pull/628
