### ISSUE TITLE
Define service grouping

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#411]
I believe an intended goal is to provide a canonical [Service Binding Schema](https://github.com/application-stacks/service-binding-specification#service-binding-schema) for backing services. In the above example, Kafka is a single service but requires two service "entries" to accomplish its binding. Some of the binding schema elements are extracted from the Kafka CR and others are extracted from the KafkaUser CR. From a binding schema perspective, all binding properties for a single `type=kafka` should appear within a single "binding root" regardless of the CR from which they were extracted.

In other words, I do not want a Kafka "binding root" in the resulting binding secret that has the following subset of binding schema elements:

type - kafka
endpoints.<listener_name> - bootstrap server information for all listeners (TBD)
ca.p12 - CA certificate PKCS #12 archive file for storing certificates and keys (`binding:env:object:secret:ca.p12`)
ca.password - password for protecting the CA certficate PKCS #12 archive file (`binding:env:object:secret:ca.password`)

and another KafkaUser "binding root" that has the remaining subset of binding schema elements:

username - username for the consuming client (`binding:env:object:secret:username`)
user.p12 - user certificate for the consuming client PKCS #12 archive file for storing certificates and keys (`binding:env:object:secret:user.p12`)
user.password - password for protecting the user certficate PKCS #12 archive file (`binding:env:object:secret:user.password`)

Again, the resulting binding secret should have a single binding `type=kafka` that contains all the above properties. No binding `type=kafkauser` should be introduced.

If the service "entries" for Kafka and KafkaUser shared a common `id`, for example, that `id` could potentially serve as the "binding root" in the binding secret within which all the properties are located.

_Originally posted by @ron1 in https://github.com/redhat-developer/service-binding-operator/pull/348#issuecomment-608419584_

**Comment by isutton** [comment]
cc @ron1 @sbose78 @arthurdm

**Comment by isutton** [comment]
I think the reason we're discussing this is the need to both group services under a logical group (Kafka according to previous examples) and, at the same time, refer to a specific service resource to fulfill the custom environment variables template contract.

For this, at least two terms have been mentioned in our discussions: `id` and `envVarPrefix`. 

According to my understanding, `envVarPrefix` is meant only to prefix environment variables that are collected according to annotations in CRD and OLM specific attributes.

This means that if the Kafka kind exposes its `status.ca.p12`, two things could happen:

1. The user hasn't specified the `envVarPrefix`, so a prefix is generated using the scheme "{kind}.{name}", resulting in the environment variable name `KAFKA_LONGNAMEHERE_STATUS_CA_P12`.
2. The user has specified the `envVarPrefix` to Kafka, so this should be used instead of the generated variable prefix, resulting in the environment variable name `KAFKA_STATUS_CA_P12`.

This logic is to be applied to each resource sequentially.

On the other hand, `id` is intended to be mostly likely used in template expressions in the custom environment variables section as an alias to a specific service declared in the service binding resource.

This means that `id` could be used in the absence of `envVarPrefix` when generating the environment variable prefix.

So hypothetically `id` and `envVarPrefix` can be are both optional, and co-exist.

**Comment by ron1** [comment]
@isutton I think `mountPathPrefix` should also be included in this discussion.

**Comment by ron1** [comment]
IMO, one of the problems here is that what we are proposing to call `services` for simplicity in ServiceBinding(Request) CRD are really `serviceBindingResources`. These could now be K8S Services/Routes/Secrets/ConfigMaps as well as CRs. One or more of these `serviceBindingResources` may be combined to accomplish a single service binding. In addition, a single ServiceBinding(Request) CR support binding multiple applications to a select group of services.

In addition, this issue introduces the term "Service Group(ing)". Would it make sense to enhance the Service Binding Specification to be more explicit and precise regarding the terms defined in its glossary?

**Comment by isutton** [comment]
>
> IMO, one of the problems here is that what we are proposing to call
> services for simplicity in ServiceBinding(Request) CRD are really
> serviceBindingResources. These could now be K8S
> Services/Routes/Secrets/ConfigMaps as well as CRs. One or more of these
> serviceBindingResources may be combined to accomplish a single service
> binding. In addition, a single ServiceBinding(Request) CR support binding
> multiple applications to a select group of services.
>
A binding context has at least two roles: the application role (the
configuration values' receiver) and the service role (the configuration
values' provider). As you've pointed out, the service name might be
misleading since there are other useful resources that can be used as
services.

My interpretation is that services represent dependencies one or more
applications have to be able to do their work; a dependency as previously
pointed out can be any type of resource. It could be said then that two
resource roles exist in a service binding: the application role, which
specifies the receiver of configuration values and the dependency (a.k.a.
service) role, which specifies resources exposing configuration values.

**Comment by arthurdm** [comment]
The spec talks about [using the ID](https://github.com/application-stacks/service-binding-specification#id-prefix) as the prefix for the injected bindings.  (it says mounted right now, but will be expanded to also env vars).

So if two (or more) services are part of a single binding, couldn't the author of the `ServiceBinding` CR just use `id`s that share a common prefix?  For example:

```
  services:
    - group: kafka.strimzi.io
      kind: KafkaUser
      resourceRef: my-producer
      version: v1beta1
      id:  KAFKA_USER
    - group: kafka.strimzi.io
      kind: Kafka
      resourceRef: my-cluster
      version: v1beta1
      id:  KAFKA_CLUSTER
```

With this usage we wouldn't need `envVarPrefix` or `mountVarPrefix` - they would just be accomplished by the `id` field.

**Comment by ron1** [comment]
What about this example that allows service binding resource grouping and eliminates the need for the id?

```
  services:
  - name: kafka
    resources:
    - group: kafka.strimzi.io
      kind: KafkaUser
      resourceRef: my-producer
      version: v1beta1
    - group: kafka.strimzi.io
      kind: Kafka
      resourceRef: my-cluster
      version: v1beta1
  - name: postgres
    resources:
    - group: postgres.dev
      kind: Service
      resourceRef: user-db
      version: v1beta1
```

**Comment by sbose78** [comment]
I would avoid nested "services" at the moment because nesting can go on and on :) 
One could get everything done without nesting and the correct `envVarPrefix` and `id`.

I agree that the term "service" can be ambiguous and redundant but I can't really have a better way to specify "binding information producer" for an "consumer"(app). 🤔

**Comment by ron1** [comment]
A service has one or more binding resources. What's the use case beyond a flat list of binding  resources?

**Comment by isutton** [comment]
>
> A service has one or more binding resources. What's the use case beyond a
> flat list of binding resources?
>
Are you implying here applications should have multiple service binding
requests, one for each service it depends on instead of having one service
binding request declaring all services an application requires?

**Comment by ron1** [comment]
No. I see the value in a single SBR CR supporting multiple apps and services.

Instead using an `id` to name a service, my suggestion is to use a `name` field for this purpose. Then within each named service exists one or more "binding" resources as provided in my sample above. IMO, the rename from backingserviceselectors to services is confusing when a single logical kafka service is represented as individual kafka and kafkauser services. My proposal eliminates such confusion. 

However, I don't understand @sbose78 comment about multiple nestings of resources.

**Comment by pedjak** [comment]
Closing, please reopen if needed.
