### ISSUE TITLE
data in secret are duplicated with prefix configMap and secret

### ISSUE THREAD

**Issue by qibobo** [redhat-developer/service-binding-operator#415]
As it is showed in the following code, the data in secret are duplicated with prefix configMap and secret, is there any special purpose?
https://github.com/redhat-developer/service-binding-operator/blob/35e8d3a1988e74880c4d15a35698ab154b6162f9/pkg/controller/servicebindingrequest/retriever.go#L200

**Comment by sbose78** [comment]
That looks like a bug to me.
