### ISSUE TITLE
Once the selected application is deleted, the sbr can't be deleted

### ISSUE THREAD

**Issue by cdlliuy** [redhat-developer/service-binding-operator#419]
After a sbr created successfully,  I deleted the selected application directly.

```
spec:
  applicationSelector:
    group: serving.knative.dev
    resource: services
    resourceRef: mydemo
    version: v1
.....
```

That means I deleted `mydemo`. 

Then, I realized and tried to delete sbr , but I can't delete it at all.

```
 >> kubectl get sbr
NAME                    AGE
mydemo-bindingrequest   3h24m
>>  kubectl delete sbr mydemo-bindingrequest
servicebindingrequest.apps.openshift.io "mydemo-bindingrequest" deleted
(Then it hangs here ...)




^C
>> $ kubectl get sbr
NAME                    AGE
mydemo-bindingrequest   3h24m
```

Any comment on this?  Expected behavior? 

It makes me to think about whether the selected `application` should be the owner of the sbr , since the sbr is only serving for the specific application only.   If  the ownership is set,  the sbr can be deleted when the application is removed.

**Comment by sbose78** [comment]
I think the finalizer we create has a bug?

**Comment by Avni-Sharma** [comment]
> After a sbr created successfully, I deleted the selected application directly.
> 
> ```
> spec:
>   applicationSelector:
>     group: serving.knative.dev
>     resource: services
>     resourceRef: mydemo
>     version: v1
> .....
> ```
> 
> That means I deleted `mydemo`.
> 
> Then, I realized and tried to delete sbr , but I can't delete it at all.
> 
> ```
>  >> kubectl get sbr
> NAME                    AGE
> mydemo-bindingrequest   3h24m
> >>  kubectl delete sbr mydemo-bindingrequest
> servicebindingrequest.apps.openshift.io "mydemo-bindingrequest" deleted
> (Then it hangs here ...)
> 
> 
> 
> 
> ^C
> >> $ kubectl get sbr
> NAME                    AGE
> mydemo-bindingrequest   3h24m
> ```
> 
> Any comment on this? Expected behavior?
> 
> Furthermore, I created `mydemo` again, SBR didn't reconcile to have the secrets injected into `mydemo` container anymore. Anyway, with the recreation of `application resourceRef`, I can delete sbr.
> 
> It makes me to think about whether the selected `application` should be the owner of the sbr , since the sbr is only serving for the specific application only. If the ownership is set, the sbr can be deleted when the application is removed.

The selected application should ideally not be made the owner of a sbr, because in some cases we might not want the injection of the intermediate secret(configuration values) in the app directly(pod spec).  This means I just want the information dumped into a Secret, and then I'll choose what to do with it after that. This is good for referencing the Secret from other things like Jobs, or a Tekton pipeline, where your controller may not be able to directly modify a pod spec.

**Comment by cdlliuy** [comment]
Sure,  any idea to resolve the failure deletion issue?  Also, how to make sure  the SBR can be reconciled after the application object updates?

**Comment by cdlliuy** [comment]
I moved the following issue description to a new issue   #422 

```
Furthermore, I created mydemo again, SBR didn't reconcile to have the secrets injected into mydemo container anymore. ```

**Comment by Avni-Sharma** [comment]
> I think the finalizer we create has a bug?

Yup, if we delete the finalized from the sbr instance, then the instance will get deleted

**Comment by Avni-Sharma** [comment]
on the hindsight, the logs say 
```
2020-04-15T01:44:18.693+0530	ERROR	reconciler.Unbind	On unbinding related objects	{"Request.Namespace": "service-binding-demo", "Request.Name": "binding-request", "ServiceBindingRequest.Name": "binding-request", "error": "deployments.apps \"deployments\" not found"}
```
so it is not exactly a finalizer issue.

**Comment by isutton** [comment]
Nice catch!

Not found errors are tricky sometimes because one usually wants to
propagate this error further, but since deletions are idempotent they're
safe to be ignored.

**Comment by int8dev** [comment]
I found the following errors need to handled in the deletion flow.
1) CRD/CR defined in BackingServiceSelector does not exist
2) Errors returned by retriever.Get(). This may happens when the there is issue to parse the template in CustomEnvVar.

**Comment by Avni-Sharma** [comment]
Hi @int8dev , I have raised a PR for this particular issue. If there are other deletion flow issues, I guess we should track it as separate issues, as it becomes easy for tracking. Also with the deletion flow issue can you give a set of guided steps to recreate them. Thanks! :)
