### ISSUE TITLE
Adding support for discovering binding information from app perspective

### ISSUE THREAD

**Issue by navidsh** [redhat-developer/service-binding-operator#425]
#### What?
As an application developer, I want to know what binding information is available to me in my application container either as env var or mounted volume.

#### How?

Having Service Binding Operator adding a well-known key (`SERVICE_BINDINGS`) into the binding secret with a JSON payload as value containing a dictionary of all the envVars/mountPath that Service Binding is managing and exposing.

Example binding secret:
```json
SERVICE_BINDINGS = {
  "bindingKeys": [
    {
      "name": "KAFKA_USERNAME",
      "bindAs": "envVar"
    },
    {
      "name": "KAFKA_PASSWORD",
      "bindAs": "volume",
      "mountPath": "/platform/bindings/secret/"
    }
  ]
}
```

In the example above, the application can query the environment variable `SERVICE_BINDINGS`, walk its JSON payload and learn that `KAFKA_USERNAME` is available as an environment variable and that `KAFKA_PASSWORD` is available as a mounted file inside the directory `/platform/bindings/secret/`.

---

* This came up from https://github.com/application-stacks/service-binding-specification/issues/24
* Some discussions around `bindAs` env var vs volume mount: https://github.com/application-stacks/service-binding-specification/issues/15
* Additional details in [Service binding spec](https://github.com/application-stacks/service-binding-specification/blob/master/README.md#injecting-data).

**Comment by ZhuangYuZY** [comment]
In my side, we also want to using on env variable `VCAP_SERVICE` as example to organize all backing service instances. And we are using IBM Cloud CLI to hide the binding request CR, define custom env var as JSON template string, and also using IBM Cloud CLI to update existing bind request CR to add more backing service instances to keep only one binding request CR for one application. And end user can also define service binding request CR by kubectl, overwrite may happens which is not good for my user case.

I am not sure if there is other user case needs multiple service binding request CR for one application ?

And one possbile solution is defining Admission Web hook to verify if one application multiple service binding request happens and reject.

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: helloworld-binding
spec:
  applicationSelector:
    resourceRef: helloworld
    group: serving.knative.dev
    version: v1
    resource: services
  backingServiceSelectors:
    - group: ibmcloud.ibm.com
      version: v1alpha1
      kind: Binding
      resourceRef: coligo-cos-service-credential
      envPreFix: cloud-object-storage                
      id:  cloud-object-storage  
    - group: ibmcloud.ibm.com
      version: v1alpha1
      kind: Binding
      resourceRef: coligo-virtual-recogntion-service-credential
      envPreFix: watson-vision-combined   
      id: watson-vision-combined  
  customEnvVar:
    - name: VCAP_SERVICE                          // CLI logic to generate the JSON template
      value: {
          "watson-vision-combined": [             //Service Class from bx resource service-instance service-instance-name
            {
              "credentials": {
                {{to_json watson-vision-combined.status.secretName}}   //Credential from Binding cr result
              },
              "name": "coligo-virtual-recogntion1"    //Service name
              "plan": "standard"                      //Service plan from bx resource service-instance service-instance-name
            }
          ],
          "cloud-object-storage": [               //Service Class from bx resource service-instance service-instance-name
            {
              "credentials": {
                {{to_json cloud-object-storage.status.secretName}}                   //Credential from Binding cr result
              }.
              "name": "coligo-cos"                    //Service name
              "plan": "standard"                      //Service plan from bx resource service-instance service-instance-name
            }
          ]
        }
```

**Comment by sbose78** [comment]
Internal https://issues.redhat.com/browse/APPSVC-534 , not assigned to anyone yet.

**Comment by otaviof** [comment]
Community meeting notes:
- @isutton: should we mark data points as "sensitive", and therefore expose it as a file;
- @arthurdm: what should be [env-var or volume-mount](https://github.com/application-stacks/service-binding-specification/issues/15#issuecomment-609972948);

**Comment by navidsh** [comment]
Added more details to [the issue description](https://github.com/redhat-developer/service-binding-operator/issues/425#issue-600553563).

**Comment by arthurdm** [comment]
To add some background:   

When we were discussing how to toggle env var injection vs volume mounting in the spec [an idea](https://github.com/application-stacks/service-binding-specification/issues/15#issuecomment-609916882) was brought up in terms of having a hierarchy of ways to specify this binding.

So that's what spawned the addition of `bindAs` [as part of the annotations in the spec](https://github.com/application-stacks/service-binding-specification/blob/master/annotations.md#data-model--building-blocks-for-expressing-binding-information), giving the bindable service a way to suggest / recommend a binding method.  In the spec we outline how this suggestion can be [overridden](https://github.com/application-stacks/service-binding-specification#mounting-and-injecting-binding-information) at a global level in the ServiceBinding CR as well as per binding element.

So this information (bindAs) is one of the pieces of information that is parsed from the bindable service's annotations.  Once that is available it can be used to populate this "umbrella" environment variable.

**Comment by yharish991** [comment]
My thoughts to limit only one service binding CR per application. I think there are a couple of ways to do that:
1. Admission webhook
  we can implement a validating webhook to validate the CR in the operator. But there are some problems if we are relying on OLM for installation of operator and the administrator must care about certificates and regenerate them when they expire. I believe some of these issues would be taken care of when they integrate kubebuilder into operator-sdk.
  Some useful links:
  https://github.com/operator-framework/operator-sdk/issues/1217
  https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/kubebuilder-integration.md
  https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/contributors/design-proposals/webhooks.md
2. During the reconcile cycle, query for the service binding CRS of same resourceRef group and kind in the namespace, if there is already an existing one we can either:
  a. Log the message saying that we limit only one CR per application, update the status to indicate that.
  b. Perform an update on the existing CR with the changes from CR being reconciled, and update the status of the CR that is being reconciled to indicate that we limit only one CR per application. We should probably limit the update to just addition and updation of fields

I have a draft implementation of the 2nd option.
