### ISSUE TITLE
Community meeting Agenda , April 23

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#431]
* Please add a topic in this thread and add a link to the Github issue associated with the topic.

* Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting :)

**Comment by cdlliuy** [comment]
PRs and road-blocker issues that we would like to discuss: 

* Using instance.id to distinguish multiple backendService  https://github.com/redhat-developer/service-binding-operator/pull/428 (Need to move forward)

* Customized env injection path  https://github.com/redhat-developer/service-binding-operator/issues/353 (Need to move forward) 

* Failed to reconcile application when application selector / backingserviceselectors content changes https://github.com/redhat-developer/service-binding-operator/issues/422
