### ISSUE TITLE
Misleading SBR status when applicationNotFound

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#440]
## Problem

When deployment not found with the given 
- `resourceRef` 
- `matchLabels`+ GVR

Then, SBR status should have:

```
Type: Ready
Status: "False"
Reason: "ApplicationNotFound"
Message: "Could not find deployment with matching ResourceRef or matchLabel"
```

## How to reproduce

1. Follow the steps given in this [example](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql) to:
- install DB operator, Service Binding Operator
- Import an application
- Create a DB instance

2. Create the following SBR

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: sbo-try-1
spec:
  applicationSelector:
        resourceRef: abc
        group: apps
        version: v1
        resource: deployments
  backingServiceSelectors:
        - resourceRef: db-demo
          group: postgresql.baiju.dev
          version: v1alpha1
          kind: Database
  detectBindingResources: true
```

Notice the `applicationSelector.resourceRef` is a random string `abc` and we don't have any deployment with the name `abc`

```
➜  ~ oc get deployments                                       
NAME                    READY     UP-TO-DATE   AVAILABLE   AGE
db-demo-postgresql      1/1       1            1           3m3s
nodejs-rest-http-crud   1/1       1            0           3m12s

```

4. The SBR status says `Type:Ready` and `Status:True`

```
➜  ~ oc get ServiceBindingRequest binding-request -o yaml
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.openshift.io/v1alpha1","kind":"ServiceBindingRequest","metadata":{"annotations":{},"name":"binding-request","namespace":"sbo-try-1"},"spec":{"applicationSelector":{"group":"apps","resource":"deployments","resourceRef":"abc","version":"v1"},"backingServiceSelectors":[{"group":"postgresql.baiju.dev","kind":"Database","resourceRef":"db-demo","version":"v1alpha1"}],"detectBindingResources":true}}
  creationTimestamp: 2020-04-25T01:59:54Z
  finalizers:
  - finalizer.servicebindingrequest.openshift.io
  generation: 1
  name: binding-request
  namespace: sbo-try-1
  resourceVersion: "413445"
  selfLink: /apis/apps.openshift.io/v1alpha1/namespaces/sbo-try-1/servicebindingrequests/binding-request
  uid: 23c4f5ce-4dfb-49ed-8a57-9e1f20ace8d1
spec:
  applicationSelector:
    group: apps
    resource: deployments
    resourceRef: abc
    version: v1
  backingServiceSelectors:
  - group: postgresql.baiju.dev
    kind: Database
    resourceRef: db-demo
    version: v1alpha1
  detectBindingResources: true
status:
  conditions:
  - lastHeartbeatTime: 2020-04-25T01:59:55Z
    lastTransitionTime: 2020-04-25T01:59:54Z
    status: "True"
    type: Ready
  secret: binding-request

```

**Comment by DhritiShikhar** [comment]
This is similar to #422 because both of them are related to missing application.

but this is a little different issue than #422 because:

- In #422 the user creates an applicationSelector, deletes it and then re-creates it again with the same name.
So, in the end user actually has an application with the same name as specified in `applicationSelector.ResourceRef`.

- In this issue, the deployment with the name `abc` never existed.

**Comment by DhritiShikhar** [comment]
@Avni-Sharma are you looking into this bug?

**Comment by Avni-Sharma** [comment]
> @Avni-Sharma are you looking into this bug?

looking at the latter, not 422

**Comment by isutton** [comment]
There are a couple of distinct cases related to the `spec.applicationSelector` field. It might be:

a. Empty;
b. Present but resolving to an empty resource list; and
c. Present and resolving to at least one resource.

In a), it is not expected the operator to retry the reconciliation since there are no expected changes in the environment that might change the result. 

In b), the user has declared an unknown dependency when the reconciliation happened, so it is expected a retry because this might be expected to be fulfilled in a later moment.

In c), it is also not expected a retry since the dependency has been already fulfilled.

Please bear in mind that `spec.applicationSelector` related retries are _orthogonal_ to the process of triggering the reconciliation process due to changes in resources used by the service binding as stated in #422.

**Comment by sbose78** [comment]
being done as part of https://github.com/redhat-developer/service-binding-operator/pull/498

**Comment by DhritiShikhar** [comment]
This is fixed.
