### ISSUE TITLE
Community Meeting, April 30th

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#445]
# Agenda
* Confirm this meeting will be weekly on Wed, instead of THu.
* Discussion about PRs
    * Add watching for workloads #442
    * Associate binding secret to a custom schema path in the workload #353
    * Streamline data retrieval based on annotations #407

**Comment by Avni-Sharma** [comment]
https://gist.github.com/isutton/12a20a8aa1f9a1469a963caa4fc13f3a for #353

**Comment by Avni-Sharma** [comment]
Closing this issue. Specific discussions have now been moved to #446
