### ISSUE TITLE
Community Meeting - May 14, 2020

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#446]
- Please add a topic in this thread and add a link to the Github issue associated with the topic.

- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting :)

**Comment by sbose78** [comment]
From @isutton : 

- Follow up single vs. multiple applications in Service Binding.
  * Related to "Associate binding secret to a custom schema path in the workload #353"
- Follow up observing all GVKs in SBO at startup time with specific CustomResourceDefinition add events.
  * Related to "Add watching for workloads #442"

**Comment by sbose78** [comment]
- @redhat-developer/service-binding to call out features/bugs that would be actively worked upon.

**Comment by sbose78** [comment]
@redhat-developer/service-binding to mention plan for switching the Group/Kind.

* https://github.com/redhat-developer/service-binding-operator/issues/364
* https://github.com/redhat-developer/service-binding-operator/issues/365.

**Comment by cdlliuy** [comment]
* progress on #353
* progress and further questions on issue #422

**Comment by lanceliuu** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/457#issuecomment-628521331
