### ISSUE TITLE
Upgrade operator-sdk to v0.17.x

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#449]
Refer https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/migration/version-upgrade-guide.md#v017x

**Comment by gorkem** [comment]
Can we close this in favour of #622 ?

**Comment by pedjak** [comment]
Done in https://github.com/redhat-developer/service-binding-operator/pull/798

**Comment by Avni-Sharma** [comment]
Closing this issue. Upgrades to 1.0.0 tracked in #622
