### ISSUE TITLE
Potential issues for unit tests caused by fake clients

### ISSUE THREAD

**Issue by lanceliuu** [redhat-developer/service-binding-operator#450]
There are two types of client in concrete type `Binder` in https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/binder.go#L43-L44.
```
// Binder executes the "binding" act of updating different application kinds to use intermediary
// secret. Those secrets should be offered as environment variables.
type Binder struct {
	ctx        context.Context                 // request context
	client     client.Client                   // kubernetes API client
	dynClient  dynamic.Interface               // kubernetes dynamic api client
	sbr        *v1alpha1.ServiceBindingRequest // instantiated service binding request
	volumeKeys []string                        // list of key names used in volume mounts
	modifier   ExtraFieldsModifier             // extra modifier for CRDs before updating
	logger     *log.Log                        // logger instance
}
```
In unit tests both of them are initliazed with provided objects. But the underneath behavior of both is to create deep copies of the objects. So the two client are holding two different objects and CRUDs might cause discrepancy. And the test results might also be affected.
https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L373-L376

Why we are holding two type of clients in `Binder`? I assume the dynamic client is enough for binder to interact with API server.

**Comment by isutton** [comment]
Indeed, the dynamic client is enough for binder to interact with the API server.

This is a left over from before we have introduced the dynamic client, it's fine to remove it.

For reference`*unstructured.Unstructured` are fed to the test scenario to be used by the fake dynamic client.
