### ISSUE TITLE
Remove backingServiceSelector from the CRD spec

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#455]
Remove [backingServiceSelector](https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/apis/apps/v1alpha1/servicebindingrequest_types.go#L33) in favour of [backingServiceSelectors](https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/apis/apps/v1alpha1/servicebindingrequest_types.go#L39)

**Comment by Avni-Sharma** [comment]
Shall we address it when we are breaking the API by changing the Kind and the Group?
Also, shall we change to applications and services altogether along with the Kind and group change?

**Comment by sbose78** [comment]
Yes, let's address this altogether when we break th API.

**Comment by sbose78** [comment]
This might break the UI I think?

**Comment by DhritiShikhar** [comment]
Yes, we can solve this when we want to break the API.. but yes, this is something that should be fixed.

**Comment by DhritiShikhar** [comment]
because having two fields `backingServiceSelector` and `backingServiceSelectors` is confusing and we have to handle two cases.

**Comment by sbose78** [comment]
Right! Thanks for tracking this closely.
On a related note, we should probably use [ group, version, kind, name ] instead of [ group, version, kind, resourceRef ] ?

**Comment by DhritiShikhar** [comment]
@sbose78 

Yes. +1 We should use `name` instead of `resourceRef`.

**Comment by Avni-Sharma** [comment]
cc @akashshinde  This is a subtask of https://issues.redhat.com/browse/APPSVC-574 . Hence assigning this issue to you.

**Comment by pedjak** [comment]
Fixed in https://github.com/redhat-developer/service-binding-operator/pull/608
