### ISSUE TITLE
remove `detectBindingResources`

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#456]
the boolean value of `detectBindingResources` flag is no where used in the code

```
➜  service-binding-operator git:(master) grep -rnI "detectBindingResources" .
./pkg/apis/apps/v1alpha1/servicebindingrequest_types.go:49:     DetectBindingResources bool `json:"detectBindingResources,omitempty"`
./examples/multiple_services/README.md:117:  detectBindingResources: true
./examples/nodejs_etcd_operator/README.md:41:  detectBindingResources: true
./deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml:250:            detectBindingResources:
./docs/OperatorBestPractices.md:106:detectBindingResources : true
```

**Comment by Avni-Sharma** [comment]
It is being used here https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/bind_custom_resources.go#L67

**Comment by Avni-Sharma** [comment]
We should not remove this and there are couple of examples for the functionality of the same captured here 
https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_etcd_operator
https://github.com/redhat-developer/service-binding-operator/tree/master/examples/multiple_services

**Comment by DhritiShikhar** [comment]
> It is being used here https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/bind_custom_resources.go#L67

How are you getting the value from `ServiceBindingRequest`?

**Comment by Avni-Sharma** [comment]
we are getting from options here https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/binding.go#L47 and since it is a bool we are checking it here https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/binding.go#L330 and calling the appropriate function

**Comment by DhritiShikhar** [comment]
oh Thanks @Avni-Sharma 

Closing this issue
