### ISSUE TITLE
Only the last SBR is recorded in backingservice annotation. 

### ISSUE THREAD

**Issue by cdlliuy** [redhat-developer/service-binding-operator#458]
Currently,  we have a requirement to  support the multiple application binding testcase: 
 binding application `A` -> backingService CR `Y`  with SBR CR named as A-Y
 binding application `B` -> backingService CR  `Y` as well  with SBR CR named as B-Y

After the binding operation, I would like to do some further queries to understand how many application is bound to the service.   
But when checking the Y's annotation,  I only see: 
```
service-binding-operator.apps.openshift.io/binding-name:  B-Y
```
Also, once I deleted SBR `B-Y`, there is no annotation at all on the backingService CR `Y` any more ! 

I know there may be some discussion to define multiple applications inside a single SBR,  but if the end-user intends to define multiple SBRs over the same backingService (as my example above),  I think the annotation should reflect a correct information. 

So, I hope to  need to change this field from json entry to json array as:
```
service-binding-operator.apps.openshift.io/binding-name:  A-Y,B-Y
```
or 
```
     service-binding-operator.apps.openshift.io/binding-name: |
      [
       {"binding-name":"sbr1"},
       {"binding-name":"sbr2"},
      ]
```

Any comment? Any other suggestion?

**Comment by sbose78** [comment]
This looks right to me. We should support this.

**Comment by DhritiShikhar** [comment]
I was able to reproduce the issue.

```
➜  crc-linux-1.8.0-amd64 oc get sbr                        
NAME                AGE
binding-request     2m24s
binding-request-2   97s
➜  crc-linux-1.8.0-amd64 oc get db db-demo -o yaml         
apiVersion: postgresql.baiju.dev/v1alpha1
kind: Database
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"postgresql.baiju.dev/v1alpha1","kind":"Database","metadata":{"annotations":{},"name":"db-demo","namespace":"sbo-try-1"},"spec":{"dbName":"db-demo","image":"docker.io/postgres","imageName":"postgres"}}
    service-binding-operator.apps.openshift.io/binding-name: binding-request-2
    service-binding-operator.apps.openshift.io/binding-namespace: sbo-try-1
  creationTimestamp: "2020-05-11T23:27:56Z"
  generation: 1
  name: db-demo
  namespace: sbo-try-1
  resourceVersion: "477493"
  selfLink: /apis/postgresql.baiju.dev/v1alpha1/namespaces/sbo-try-1/databases/db-demo
  uid: 045f8c1a-06d0-4925-819e-61dc263c214b
spec:
  dbName: db-demo
  image: docker.io/postgres
  imageName: postgres
status:
  dbConfigMap: db-demo
  dbConnectionIP: 172.30.70.188
  dbConnectionPort: 5432
  dbCredentials: db-demo-postgresql
  dbName: db-demo


```

>  but if the end-user intends to define multiple SBRs over the same backingService (as my example above), I think the annotation should reflect a correct information.

Absolutely right.


```
service-binding-operator.apps.openshift.io/binding-name:  [A-Y, B-Y]

```

This design looks concise and clean.
