### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#463]
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422491032
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422490504
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418073489
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418074534
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422494018

**Comment by DhritiShikhar** [comment]
Related Jira Issue -> https://issues.redhat.com/browse/APPSVC-578

**Comment by pedjak** [comment]
Obsolete by #919
