### ISSUE TITLE
Community Meeting - May 22nd, 2020

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#470]
* Please add a topic in this thread and add a link to the GitHub issue associated with it
* Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting :)

**Comment by qibobo** [comment]
we can discuss about issue https://github.com/redhat-developer/service-binding-operator/issues/475

**Comment by lanceliuu** [comment]
Discussed the next step and any concern for below: 
https://github.com/redhat-developer/service-binding-operator/pull/457  
https://github.com/redhat-developer/service-binding-operator/pull/442

**Comment by DhritiShikhar** [comment]
@isutton We decided to move this meeting to tomorrow. I will reschedule the meeting invite.

**Comment by ZhuangYuZY** [comment]
Status ? https://github.com/redhat-developer/service-binding-operator/pull/353

**Comment by navidsh** [comment]
Controller doesn't reconcile to changes to backing services. Similar issue as #422.

**Comment by isutton** [comment]
#468 is a priority.

Create one issue to track the extra prefix in config maps and secrets injection.

Create one issue to change the global prefix in custom env vars.

**Comment by isutton** [comment]
Both #457 and #442 seem good to be merged, needs prio.

**Comment by navidsh** [comment]
Re https://github.com/redhat-developer/service-binding-operator/issues/470#issuecomment-632636193, the description of https://github.com/redhat-developer/service-binding-operator/issues/422 covers both application and **backing service** scenario.

@isutton @DhritiShikhar Please let me know if it's better I create a separate issue for backing service and keep #422 for application changes.

**Comment by DhritiShikhar** [comment]
@navidsh Let me check if #442 addresses the issue or not. I will update you here.

**Comment by DhritiShikhar** [comment]
Created a new ticket for next meeting - https://github.com/redhat-developer/service-binding-operator/issues/482

**Comment by DhritiShikhar** [comment]
@navidsh #442 addresses the issue. 

The annotations are re-injected in the backing service once it becomes available.

**Comment by navidsh** [comment]
@DhritiShikhar Thx for confirming this
