### ISSUE TITLE
Increase coverage in existing tests

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#471]
Review comments related to coverage in existing tests after #407:

* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422490037
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422473473
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418196105
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422218974
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418196105
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422227351
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422229996
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422230944
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422235223

**Comment by sbose78** [comment]
cc @pmacik

**Comment by pedjak** [comment]
Obsolete by #919
