### ISSUE TITLE
Review test names

### ISSUE THREAD

**Issue by isutton** [redhat-developer/service-binding-operator#472]
Review comments from #407 regarding test names:

* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418204201
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418185911
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418186050
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418204201
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r418214628
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422154375
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422155739
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422158126
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422158754
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422210518
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422233338
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422154868
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422158126
* https://github.com/redhat-developer/service-binding-operator/pull/407#discussion_r422210518

**Comment by pedjak** [comment]
Obsolete by #919
