### ISSUE TITLE
Makefile with shell script for installing operator-sdk

### ISSUE THREAD

**Issue by baijum** [redhat-developer/service-binding-operator#480]
From:
https://github.com/redhat-developer/service-binding-operator/pull/478#issuecomment-631526574

> 
> Would an idea be bringing some goodies from other projects, such as redhat-developer/build [install-operator-sdk.sh](https://github.com/redhat-developer/build/blob/8bc82ef7e6fdbbd64a40d9a3b3112ce63e58af61/hack/install-operator-sdk.sh)?
> 
> I find the approach of having the default version in the [Makefile](https://github.com/redhat-developer/build/blob/d28017bdc1054b01799c50f4c9f93c8b45bc90a6/Makefile#L26) quite straightforward, as well as the configuration propagation through environment variables.

**Comment by otaviof** [comment]
In general, I find the idea of reusing the scripts between our operators a good idea. We have common needs like to install `operator-sdk`, `kubectl`, executing Codecov script, and other common automation that we can share.

So my +1 on this :-)

**Comment by baijum** [comment]
As there was no need came up for a re-usable script, I think this issue can be closed.
