### ISSUE TITLE
Document-  Associate binding secret to a custom schema path in the workload

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#481]
Add relevant documentation for #353

**Comment by DhritiShikhar** [comment]
@Avni-Sharma
[1] Is this documentation suppose to reside under `docs/` ? 
[2] Can we handle this as a part of #353 PR itself?

**Comment by Avni-Sharma** [comment]
We can have it under https://github.com/redhat-developer/service-binding-operator/tree/master/examples 
I believe we can capture it as a separate PR, #353 is a priority and has been around for quite some time now, so we might want to take it in soon

**Comment by sbose78** [comment]
As for docs, could we add this to our list of sample scenarios too?

**Comment by isutton** [comment]
@sbose78 @siamaksade are we good to merge then #353 without docs and track it here?

**Comment by sbose78** [comment]
Since it's a new non-breaking capability, the docs may go in a future PR.

**Comment by sbose78** [comment]
done in https://github.com/redhat-developer/service-binding-operator/commit/e84c5a9a73eca88f3b679af8921eb34e819815d1
