### ISSUE TITLE
Community Meeting - May 28, 2020

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#482]
- Please add a topic in this thread and add a link to the GitHub issue associated with it
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting :)

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/issues/475

**Comment by DhritiShikhar** [comment]
[1] Tests for PR #442

**Comment by DhritiShikhar** [comment]
Next community meeting -> https://github.com/redhat-developer/service-binding-operator/issues/500
