### ISSUE TITLE
Provide an option to run service binding operator in leader-for-lease approach

### ISSUE THREAD

**Issue by cdlliuy** [redhat-developer/service-binding-operator#488]
In current service binding operator implementation, only leader-for-life is supported, 
https://github.com/redhat-developer/service-binding-operator/blob/1fe7f5a2a8c8ee57c0fcb1634771a974c57206fe/cmd/manager/main.go#L85-L94

According to operator sdk docs,  some code changes is required if running it with leader-for-lease. 

Given there is an environment variable setting to enable/disable the leader selection as below already, 
https://github.com/redhat-developer/service-binding-operator/blob/1fe7f5a2a8c8ee57c0fcb1634771a974c57206fe/cmd/manager/main.go#L57-L59
 how about adding another option to select the different leader selection algorithm per deployment? 

With some internal estimation, we would like to use leader-for-lease since `leader-for-life` doesn't work well under some conditions, i.e. sometimes when network issue happens,  the leader is not working correctly, but the previous leader pod is not deleted automatically, and new leader cannot be elected

**Comment by cdlliuy** [comment]
Any comment on this?  If no objection, maybe we can start to draft PR for this. 
@isutton  @sbose78  @DhritiShikhar  ?

**Comment by DhritiShikhar** [comment]
> With some internal estimation, we would like to use leader-for-lease since leader-for-life doesn't work well under some conditions, i.e. sometimes when network issue happens, the leader is not working correctly, but the previous leader pod is not deleted automatically, and new leader cannot be elected

@cdlliuy 

[1] Are you suggesting to remove `leader-for-life` approach entirely and just have `leader-for-lease` approach?
[2] Would you be introducing a new environment variable for `leader-for-lease` approach?

**Comment by cdlliuy** [comment]
@DhritiShikhar , I am suggesting to introduce a new env variable to leader-for-lease,  so that we can choose to use `leader-for-lease` or `leader-for-life` with deployment yaml.

**Comment by DhritiShikhar** [comment]
@cdlliuy Sounds good!

**Comment by DhritiShikhar** [comment]
@cdlliuy Go ahead with a PR for the same :)

**Comment by cdlliuy** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/504 added for this
