### ISSUE TITLE
`update-version` script throws error

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#492]
```
➜  service-binding-operator git:(master) ./hack/update-version.sh 
./hack/update-version.sh: line 9: $1: unbound variable
➜  service-binding-operator git:(master) 

```

**Comment by Avni-Sharma** [comment]
$1 here means an argument to be passed during running the script. Here the argument would be the new version.

**Comment by Avni-Sharma** [comment]
Moreover, I think we are not using this script as the manifests-upstream has also been removed. However, we can restructure/repurpose this script for making git releases, in sync with releases on operatorHub.io.
cc @pedjak @baijum

**Comment by DhritiShikhar** [comment]
> $1 here means an argument to be passed during running the script. Here the argument would be the new version.

@Avni-Sharma if an input is required from user. More descriptive error should be returned.

**Comment by DhritiShikhar** [comment]
> Moreover, I think we are not using this script as the manifests-upstream has also been removed. However, we can restructure/repurpose this script for making git releases, in sync with releases on operatorHub.io.

+1

**Comment by pedjak** [comment]
@DhritiShikhar these scripts are invoked from Makefile, not sure if they were designed to be used directly.

**Comment by DhritiShikhar** [comment]
@pedjak It would be good to have a comment on the script which says that this command is not be run directly and which phony from Makefile invokes this script.

**Comment by pedjak** [comment]
We do not use this script anymore, closing.
