### ISSUE TITLE
Controller doesn't reconcile on changes to BackingService CR

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#508]
It's been reported that 

"We use ServiceBindingRequests to bind services like kafka/databases to microservices. In the kafka example, because a cluster can take up to a few minutes to come up and make its address available to the Service Binding operator, the secrets created by the SBO are empty. It is apparent that the SBO does not watch CRDs (like kafka here) and update/recreate the secrets when the expected data is available. "

"I think in this case, the status field of the Kafka CR is getting updated once the kafka cluster is up and running, but then SBO doesn’t get notified about the update. and therefore the binding secret doesn’t include the updated kafka address"

Taken out from https://github.com/redhat-developer/service-binding-operator/pull/442#issuecomment-637421911

**Comment by sbose78** [comment]
* Initial implementation : https://github.com/redhat-developer/service-binding-operator/pull/162 used to watch all GVKs associated with CRDs owned by CSVs.
* In master, the controller watches all [GVKs](https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/sbrcontroller.go#L154 ) including those [owned by CSVs ](https://github.com/redhat-developer/service-binding-operator/blob/70cdc2caf9ac0d227353fd0f016f8b2b3e44b7b1/pkg/controller/servicebindingrequest/sbrcontroller.go#L92)

**Comment by sbose78** [comment]
cc @pushkarnk @navidsh for more info.

**Comment by DhritiShikhar** [comment]
### How to test

1. Follow the steps given in this [example](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql) to:
- install DB operator, Service Binding Operator
- Import an application
- Create a DB instance 
- Create a ServiceBindingRequest

Binding should be successful.

2. Delete DB instance 

```
oc delete deployment db-demo
```

3. Recreate the DB instance with the same name. Refer the [steps](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql#create-a-db-instance-for-the-application)

With the new backingservice, the service credential is changed. But the injected env in application containers is not updated.

**Comment by Avni-Sharma** [comment]
> ### How to test
> 1. Follow the steps given in this [example](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql) to:
> 
> * install DB operator, Service Binding Operator
> * Import an application
> * Create a DB instance
> * Create a ServiceBindingRequest
> 
> Binding should be successful.
> 
> 1. Delete DB instance
> 
> ```
> oc delete deployment db-demo
> ```
> 
> 1. Recreate the DB instance with the same name. Refer the [steps](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql#create-a-db-instance-for-the-application)
> 
> With the new backingservice, the service credential is changed. But the injected env in application containers is not updated.

For me watch for this particular example is working. I will add steps for it.

**Comment by Avni-Sharma** [comment]
On adding a postgres as a service first and then adding another service etcd instead of postgres the service binding secret is getting updated. That means a watch is there. Steps
i) install postgres db
2) import an app
3) Create db postgres with resourceref- db-demo
4) create sbr
5) Check contents of the binding secret
6) delete db
7) create another etcd cluster and update sbr with gvk and resourceref db-demo
8) check the binding secret now. The contents of the secret is updated.

Is there anything that is missing here

@navidsh @pushkarnk  can you give some steps to recreate the issue

The reconcile logs i
```
2020-06-18T13:18:20.264+0530	DEBUG	sbrcontroller	Adding watch for GVK...	{"GVK": "postgresql.baiju.dev/v1alpha1, Kind=Database"}
2020-06-18T13:18:20.264+0530	DEBUG	sbrcontroller	Skipping watch on GVK twice, it's already under watch!	{"GVK": "postgresql.baiju.dev/v1alpha1, Kind=Database"}
```

On step (6) when I deleted the db The reconcile logs showed as follows
```
aiju.dev/v1alpha1, Kind=Database"}
2020-06-18T13:52:07.134+0530	DEBUG	sbrcontroller	Adding watch for GVK...	{"GVK": "postgresql.baiju.dev/v1alpha1, Kind=Database"}
2020-06-18T13:52:07.134+0530	DEBUG	sbrcontroller	Skipping watch on GVK twice, it's already under watch!	{"GVK": "postgresql.baiju.dev/v1alpha1, Kind=Database"}
2020-06-18T13:52:40.839+0530	INFO	reconciler	Reconciling ServiceBindingRequest...	{"Request.Namespace": "service-binding-demo", "Request.Name": "binding-request"}
2020-06-18T13:52:41.135+0530	DEBUG	reconciler	Found service binding request to inspect	{"Request.Namespace": "service-binding-demo", "Request.Name": "binding-request", "ServiceBindingRequest.Name": "binding-request"}
2020-06-18T13:52:41.415+0530	ERROR	controller-runtime.controller	Reconciler error	{"controller": "servicebindingrequest-controller", "request": "service-binding-demo/binding-request", "error": "databases.postgresql.baiju.dev \"db-demo\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/avni/go/src/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/avni/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/avni/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/avni/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/home/avni/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/avni/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/home/avni/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
```

which shows that db-demo isn't found. So the backing service is being watched.

**Comment by pushkarnk** [comment]
@Avni-Sharma I have an application-related test case for now. I can work on a simpler test case if @navidsh hasn't already created one.

**Comment by navidsh** [comment]
@pushkarnk I also used the coffeeshop app to reproduce the issue last time.
I have a sample app and I should be able to quickly recreate using the app. I'll add a comment here once it's ready.

**Comment by navidsh** [comment]
Steps to reproduce:
1. Install the Strimzi Operator (`v0.18.0`).
1. Install the Service Binding Operator `v0.1.1-282`. This is the latest version of the operator available through OperatorHub.
1. Create `ServiceBindingRequest`, application, and the backing service (Kafka) resources:
    ```console
    cat <<EOF | oc apply -f -
    apiVersion: apps.openshift.io/v1alpha1
    kind: ServiceBindingRequest
    metadata:
      name: kafka-producer-binding
    spec:
      applicationSelector:
        resourceRef: nginx-deployment
        group: apps
        version: v1
        resource: deployments
      backingServiceSelectors:
        - group: kafka.strimzi.io
          kind: Kafka
          resourceRef: my-cluster
          version: v1beta1
      customEnvVar:
        - name: BOOTSTRAP_SERVERS
          value: |-
            {{- range .status.listeners -}}
              {{- if and (eq .type "tls") (gt (len .addresses) 0) -}}
                {{- with (index .addresses 0) -}}
                  {{ .host }}:{{ .port }}
                {{- end -}}
              {{- end -}}
            {{- end -}}
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      selector:
        matchLabels:
          app: nginx
      replicas: 0 # tells deployment to deploy no pod
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
            - containerPort: 80
    ---
    apiVersion: kafka.strimzi.io/v1alpha1
    kind: Kafka
    metadata:
      name: my-cluster
      labels:
        app: my-cluster
    spec:
      kafka:
        replicas: 3
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: "1"
        jvmOptions:
          -Xms: 1024m
          -Xmx: 1024m
        listeners:
          plain: {}
          tls:
            authentication:
              type: tls
        authorization:
          type: simple
          superUsers:
            - CN=my-connect
            - my-connect
            - ANONYMOUS
        config:
          offsets.topic.replication.factor: 3
          transaction.state.log.replication.factor: 3
          transaction.state.log.min.isr: 2
        storage:
          type: ephemeral
      zookeeper:
        replicas: 3
        resources:
          requests:
            memory: 1Gi
            cpu: "0.3"
          limits:
            memory: 1Gi
            cpu: "0.5"
        storage:
          type: ephemeral
    EOF
    ```
1. It takes a few minutes until the Kafka cluster is being deployed:
    ```console 
    $ oc get kafka my-cluster -o yaml

    ...
    status:
      conditions:
      - lastTransitionTime: 2020-06-19T15:03:49+0000
        message: Kafka cluster is being deployed  <---
        reason: Creating
        status: "True"
        type: NotReady
      observedGeneration: 0
    ```
1. Once the cluster is up and running, the Kafka CR's status field gets info needed in the SBR:
    ```console
    $ oc get kafka my-cluster -o yaml

    ...
    status:
      conditions:
      - lastTransitionTime: 2020-06-19T15:06:30+0000
        status: "True"
        type: Ready
      listeners:
      - addresses:
        - host: my-cluster-kafka-bootstrap.rco.svc
          port: 9092
        bootstrapServers: my-cluster-kafka-bootstrap.rco.svc:9092
        type: plain
      - addresses:
        - host: my-cluster-kafka-bootstrap.rco.svc
          port: 9093
        bootstrapServers: my-cluster-kafka-bootstrap.rco.svc:9093
        certificates:
    ...
    ```
1. Check the content of the secret and see that the `BOOTSTRAP_SERVERS` key is empty.
    ```
    $ oc get sbr
    NAME                     AGE
    kafka-producer-binding   10m

    $ oc get secret kafka-producer-binding -o yaml
    apiVersion: v1
    data:
      BOOTSTRAP_SERVERS: ""
    kind: Secret
    metadata:
      creationTimestamp: "2020-06-19T15:03:53Z"
      name: kafka-producer-binding
      namespace: rco
      resourceVersion: "35260417"
      selfLink: /api/v1/namespaces/rco/secrets/kafka-producer-binding
      uid: c603e596-4716-40ba-aa34-c465b4c78165
    type: Opaque
    ```
1. Delete the SBR, Kafka CR and the application.
1. Redeploy the Kafka CR first and **wait until it is ready by checking the status of the CR**:
    ```console
    cat <<EOF | oc apply -f -
    apiVersion: kafka.strimzi.io/v1alpha1
    kind: Kafka
    metadata:
      name: my-cluster
      labels:
        app: my-cluster
    spec:
      kafka:
        replicas: 3
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: "1"
        jvmOptions:
          -Xms: 1024m
          -Xmx: 1024m
        listeners:
          plain: {}
          tls:
            authentication:
              type: tls
        authorization:
          type: simple
          superUsers:
            - CN=my-connect
            - my-connect
            - ANONYMOUS
        config:
          offsets.topic.replication.factor: 3
          transaction.state.log.replication.factor: 3
          transaction.state.log.min.isr: 2
        storage:
          type: ephemeral
      zookeeper:
        replicas: 3
        resources:
          requests:
            memory: 1Gi
            cpu: "0.3"
          limits:
            memory: 1Gi
            cpu: "0.5"
        storage:
          type: ephemeral
    EOF
    ```
1. Then deploy the SBR and the app:
    ```console
    cat <<EOF | oc apply -f -
    apiVersion: apps.openshift.io/v1alpha1
    kind: ServiceBindingRequest
    metadata:
      name: kafka-producer-binding
    spec:
      applicationSelector:
        resourceRef: nginx-deployment
        group: apps
        version: v1
        resource: deployments
      backingServiceSelectors:
        - group: kafka.strimzi.io
          kind: Kafka
          resourceRef: my-cluster
          version: v1beta1
      customEnvVar:
        - name: BOOTSTRAP_SERVERS
          value: |-
            {{- range .status.listeners -}}
              {{- if and (eq .type "tls") (gt (len .addresses) 0) -}}
                {{- with (index .addresses 0) -}}
                  {{ .host }}:{{ .port }}
                {{- end -}}
              {{- end -}}
            {{- end -}}
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      selector:
        matchLabels:
          app: nginx
      replicas: 0 # tells deployment to deploy no pod
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
            - containerPort: 80
    EOF
    ```
1. Check the binding secret and see that the `BOOTSTRAP_SERVERS` key is not empty.

**Comment by pushkarnk** [comment]
@Avni-Sharma Can you let us know the outlook on this issue please? Thank you :)

**Comment by Avni-Sharma** [comment]
I believe it is happening because of https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/sbrcontroller.go#L123 and we might need to change the predicate for GVK. Looking more into this. Sorry for the delay, was caught up with one more issue :sweat_smile:

**Comment by Avni-Sharma** [comment]
we had a discussion regarding this and it is captured here https://github.com/redhat-developer/service-binding-operator/pull/556

**Comment by Avni-Sharma** [comment]
Some observations that I gathered during debugging this

the steps I do to recreate it again are :
1)Sbr.yaml is applied first
2)app deployment yaml and then
3)the kafka yaml
So now kafka's statuses are false, and it takes like 2 mins to turn to True. Till then the operator is reconciling and watching resources( like strimzi kafka )
For some reason on update to status of the strimzi kafka resource the operator does not reconcile.
However it does not reconcile on a retryInterval as well, I thought maybe by luck it takes updates from the kafka resource due to the retry Interval but that does not happen.
So far all resources are there in the cluster and there we have a secret with no contents
data:
  BOOTSTRAP_SERVERS: ""

So now I checked the kafka resource after some time, so far so good, I have my statuses populated with certs and set to True so I am ready to retrigger a reconcile. In order to retrigger a reconcile I update my SBR with some random annotation in the metadata. Reconcile gets retriggered. Hoping that now the secret data is populated, I check it and it is still  BOOTSTRAP_SERVERS: "".

Then I do ` k edit sbr resource` the secret didn't get updated. So now I change the secret data itself, hoping that reconcile is retriggered and it tries to bring back the secret to a state where the actual data is populated and not what I have entered on k edit secret. So I do k edit secret name save some data. Reconcile hits again, and I see the logs with all the steps, so reconcile is retriggered. Then I see the intermediate secret to find the data BOOTSTRAP_SERVERS: "". Even after the kafka status is updated and we are retriggering the reconcile, by whatever mechanism it may be,  the secret isn't getting populated.

**Comment by Avni-Sharma** [comment]
Just realized, the above issue occurs because after a few prs got into master, we need to give the id with customEnvVar now.
Example id:kaf
```
  customEnvVar:
    - name: BOOTSTRAP_SERVERS
      value: |-
        {{- range kaf.status.listeners -}}
          {{- if and (eq .type "tls") (gt (len .addresses) 0) -}}
            {{- with (index .addresses 0) -}}
              {{ .host }}:{{ .port }}
            {{- end -}}
          {{- end -}}
        {{- end -}}
```

**Comment by Avni-Sharma** [comment]
Hi @navidsh  and @pushkarnk . I have proposed a fix for the issue and I am working for e2e tests right now. Can you give an app example where the BOOTSTRAP_SERVERS is being consumed in the app.

**Comment by Avni-Sharma** [comment]
https://youtu.be/E3SsHE7K9OQ

**Comment by Avni-Sharma** [comment]
Link to the working piece - https://youtu.be/E3SsHE7K9OQ

**Comment by cdlliuy** [comment]
@Avni-Sharma ,   @qibobo did some tests with latest master, but the workflow in https://github.com/redhat-developer/service-binding-operator/issues/508#issuecomment-645450600  seems not work

**Comment by sbose78** [comment]
^ re-opening in that case.

**Comment by Avni-Sharma** [comment]
@cdlliuy I tried the same steps, and it seems to be working for me, i.e reconciling after deleting db and creating db with the same name. Note, unless anything is changed in the intermediate secret (via changes in db spec or CM/Secret changes), the injection won't happen again in the app deployment. Any change in the DB spec or the secret/CM of the DB, but with the same resource name for the DB instance would trigger the reconcile.
I followed the following steps
- install DB operator(I installed https://github.com/operator-backing-service-samples/postgresql-operator ),
- Ran SBO from master locally
- Import an application
- Create a DB instance with name `db-demo`
```
apiVersion: postgresql.baiju.dev/v1alpha1
kind: Database
metadata:
  name: db-demo
  namespace: service-binding-demo
spec:
  image: docker.io/postgres
  imageName: postgres
  dbName: db-demo
```
- Create a ServiceBindingRequest
```
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: binding-request
  namespace: service-binding-demo
spec:
  application:
    name: nodejs-rest-http-crud
    group: apps
    version: v1
    resource: deployments
  services:
  - group: postgresql.baiju.dev
    version: v1alpha1
    kind: Database
    name: db-demo
```

After applying SBR, a connection was established
Later I deleted ` oc delete db db-demo`
Now I applied again the db instance with name `db-demo`

Following db instance 
```
apiVersion: postgresql.baiju.dev/v1alpha1
kind: Database
metadata:
  name: db-demo
  namespace: service-binding-demo
spec:
  image: docker.io/postgres
  imageName: postgres
  dbName: db-demo-2
```

Note I changed a spec part, but the CRs name is same, i.e db-demo
I check the resourceVersion of the intermediate Secret now, and it is updated and the latest values are injected in the app as well.

**Comment by Avni-Sharma** [comment]
But I can add predicate for metadata changes as well, cc @pedjak
