### ISSUE TITLE
Lack of condition updating in reconcile process

### ISSUE THREAD

**Issue by qibobo** [redhat-developer/service-binding-operator#511]
In the reconcile process, some steps may fail without updating the SBR's condition. The steps between  [start](https://github.com/redhat-developer/service-binding-operator/blob/a7aa2af3a3df9d7afef2f75d26f163155fbc4ff4/pkg/controller/servicebindingrequest/reconciler.go#L152) and [end](https://github.com/redhat-developer/service-binding-operator/blob/a7aa2af3a3df9d7afef2f75d26f163155fbc4ff4/pkg/controller/servicebindingrequest/reconciler.go#L198) may fail, but it just returns error, the SBR's condition is not updated.

A example of condition setting:
https://github.com/redhat-developer/service-binding-operator/blob/a7aa2af3a3df9d7afef2f75d26f163155fbc4ff4/pkg/controller/servicebindingrequest/reconciler.go#L134

Is it an issue or it does not need?

**Comment by isutton** [comment]
You're completely right, we should look at it.

Let's use this issue to track whether all reconciler return points update conditions appropriately.

**Comment by pedjak** [comment]
@qibobo can you please share the test case demonstrating the issue?

**Comment by qibobo** [comment]
@pedjak 
The reconciler has been enhanced, I will close this issue.
