### ISSUE TITLE
Integration tests are failing on operator-sdk v0.17.1

### ISSUE THREAD

**Issue by akashshinde** [redhat-developer/service-binding-operator#518]
E2E test cases are failing at the initial stage.

### What I did 
`make test-e2e` 

which internally does
```
operator-sdk --verbose test local ./test/e2e \
		--namespace test-namespace-1058909b-794c-4212-ad94-dc4aa077a071 \
		--up-local \
		--go-test-flags "-timeout=15m" \
		--local-operator-flags "--zap-level=debug --zap-encoder=console " \
		"--debug" 
```

### Output
Getting following error message
```INFO[0000] --namespace is deprecated; use --operator-namespace instead.```

### Plausible fix
Since operator-sdk v0.17.0 `namespace` argument has been changed to `operator-namespace`. Ref(https://github.com/operator-framework/operator-sdk/pull/2617)

**Comment by Avni-Sharma** [comment]
We are yet to upgrade operator-sdk version to 0.17.x We are currently on 0.16.0

**Comment by Avni-Sharma** [comment]
Closing this issue as we have not yet migrated to 0.17.x
