### ISSUE TITLE
Update status with a proper message when two similar services have been referred in 2 SBR for the same app

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#520]
An informational condition could be created to inform the user there's a duplicated entry in the services field, but it shouldn't prevent the well functioning of the operator because of that fact.

Refer https://github.com/redhat-developer/service-binding-operator/pull/514#issuecomment-645809793

**Comment by Avni-Sharma** [comment]
An update in the status would only  happen effectively if the similar services are in the same SBR, however, with 2 different sbrs and a similar service in both the sbrs, won't be able to update the status of their respective sbrs, with the knowledge of having distinct services.

**Comment by pedjak** [comment]
@Avni-Sharma please provide acceptance tests demonstrating the expected behaviour.

**Comment by Avni-Sharma** [comment]
Currently, we avoid redundancy of binding 2 services of a particular db instance with an app. ie if db-1 instance is mentioned in the list of the services more than once in a single sbr, then we take the count as 1 and avoid duplicates or more copies. But if the same instance of the service is in a separate sbr, then the redundancy is not avoided. That os covered as an acceptance test in #825

**Comment by Avni-Sharma** [comment]
We need to discuss whether we should propagate a message as a status, mentioning the redundant service? or we want to completely avoid the injection in case of a second/third/n th sbr with a redundant service?

**Comment by Avni-Sharma** [comment]
As illustrated in PR #825 . The user experience for the application author is not broken, i.e the author can continue to work with multiple instances of SBR but with a similar spec. 
- As a follow up we can look at how this turns out to be on the OpenShift Console.
- Add a status/message suggesting the redundant bindings(multiple sbrs with the same spec)

Right now the issue does not seem to be critical as the user experience is not broken. As discussed in the Cabal I would be removing the 0.5 release tag for this.

Also, we would like to explore any use cases wherein there is a need by the app author to have multiple sbrs with the same spec.

**Comment by Avni-Sharma** [comment]
On OpenShift DevConsole when we apply the second SBR with the same spec (so we can test the behavior of the console with duplicate bindings) and it only rendered a single arrow (for the first binding). When deleted the binding (via right-clicking on the arrow) the arrow remained to represent the second binding. So It Doesnt seem to be a critical issue on the DevConsole UI as well. So this can be closed IMO
