### ISSUE TITLE
How to install Service Binding Operator on Kubernetes?

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/service-binding-operator#536]
I'd like to install SBO on k8s to try linking an application and service on k8s. I'm using minikube

1. I don't find SBO on operatorhub.io website.
2. I tried the step mentioned in [Quick Start section](https://github.com/redhat-developer/service-binding-operator#quick-start) but faced below error:
    ```sh
    $ cat <<EOS |kubectl apply -f -
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorSource
    metadata:
      name: redhat-developer-operators
      namespace: openshift-marketplace
    spec:
      type: appregistry
      endpoint: https://quay.io/cnr
      registryNamespace: redhat-developer
    EOS
    error: unable to recognize "STDIN": no matches for kind "OperatorSource" in version "operators.coreos.com/v1"
    ```
Minikube info:
```
$ minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```

Am I doing something wrong? What's the right way to have SBO on k8s?

**Comment by sbose78** [comment]
> I tried the step mentioned in Quick Start section but faced below error:

Could you try doing so after installing OLM ?

@lanceliuu and @zhangtbj deploys Service Binding on kubernetes clusters in a non-OLM way : could you share your steps?

I would expect it to look like this:
* You could install all the yamls in https://github.com/redhat-developer/service-binding-operator/tree/master/deploy except for the olm-catalog.
* Use quay.io/redhat-developer/app-binding-operator in https://github.com/redhat-developer/service-binding-operator/blob/master/deploy/operator.yaml#L24 

Dharmit, however, if you wish to do an `oc get csv` inside odo, you need it the OLM way :)

**Comment by greglanthier** [comment]
I've been struggling a little to find a way to use OLM to install this operator, too.

I think the confusion with using the OLM way, at least for me, stems from the fact that the `OperatorSource` kind is [deprecated and/or not available](https://github.com/operator-framework/operator-marketplace/pull/284) in new versions of OLM (certainly from [0.15.1](https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/0.15.1) onwards).

I've been looking for ways to add a `CatalogSource` that will let me deploy `service-binding-operator` - something like the equivalent to the following that adds the community-operators catalog to a fresh OLM installation:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: ca-operators
spec:
  displayName: Community Operators
  image: quay.io/operator-framework/upstream-community-operators:latest
  publisher: OperatorHub.io
  sourceType: grpc
```

I'm still digging for more examples of how to map from the deprecated `OperatorSource` kind to the `CatalogSource` kind.

I'm working with both `Minikube` and `kind`.

```shell
$ minikube version   
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
$ kubectl logs -n olm deployments.apps/olm-operator  | grep olm.version
time="2020-07-02T23:46:32Z" level=info msg="Labels updated!" labels="olm.api.4bca9f23e412d79d=provided,olm.version=0.14.1"
$ kubectl get crd | grep source                                  
catalogsources.operators.coreos.com           2020-07-02T23:53:42Z
$
```

```shell
$ kind --version
kind version 0.8.1
$ kubectl logs -n olm deployments.apps/olm-operator  | grep olm.version
time="2020-07-02T23:51:46Z" level=info msg="updated labels" csv=packageserver labels="olm.api.4bca9f23e412d79d=provided,olm.version=0.15.1" ns=olm
$ kubectl get crd | grep source    
catalogsources.operators.coreos.com           2020-07-02T23:51:05Z
$
```

**Comment by dharmit** [comment]
> Could you try doing so after installing OLM ?

I did indeed try after installing OLM. The way I'm "installing" OLM is by simply enabling its add-on:
```sh
$ minikube addons enable olm
```

> Dharmit, however, if you wish to do an `oc get csv` inside odo, you need it the OLM way :)

Indeed, I need it as `oc get csv`. We fetch the list of CSVs available in the namespace using the OLM APIs.

**Comment by dharmit** [comment]
> > Dharmit, however, if you wish to do an `oc get csv` inside odo, you need it the OLM way :)
> 
> Indeed, I need it as `oc get csv`. We fetch the list of CSVs available in the namespace using the OLM APIs.

@sbose78 I think it's worth giving a shot without having it available for `oc get csv`. In the end we only need to have `ServiceBindingRequest` API object available in the cluster. So long as we can create an SBR, it should be fine if we don't have this installed the OLM way for now.

**Comment by cdlliuy** [comment]
@isutton ,  as discussed in meeting,    we tried to install SBO on top of  PR #397 with the deployment yaml file.

**Comment by dharmit** [comment]
I was able to get this installed on my minikube cluster using the deployment yaml. However, being able to use it through OLM APIs would be desirable.

**Comment by sbose78** [comment]
@greglanthier 
@dharmit 

There's actually a fair bit to work to move away from OperatorSource unfortunately, I recently found out 
https://github.com/redhat-developer/gitops-operator#re-build-and-deploy 

We've had some fancy CD scripts which generated an OperatorSource bundle on every push to master, that work needs to be done away with, to an extent, to support the new way :)

Till that happens, the best bet should be to install using plain old Kubernetes yamls in `deploy/` .

**Comment by dharmit** [comment]
@sbose78 OK, thanks for the info. That's helpful! We'll add that to odo docs for k8s users.

**Comment by sbose78** [comment]
@dharmit , by any chance would you be able to contribute docs for installation on Kubernetes?

**Comment by dharmit** [comment]
> @dharmit , by any chance would you be able to contribute docs for installation on Kubernetes?

Sure. It's just that I'm not in a position to commit on the timeline at the moment. Would doing this some time after odo v2 release be fine by the team?

**Comment by dharmit** [comment]
For time being, I've documented the steps that helped me setup SBO on minikube in this PR on odo repohttps://github.com/openshift/odo/pull/4140. Once we get it merged, I'll open a PR on SBO repo for the same.

**Comment by Avni-Sharma** [comment]
Thanks @dharmit , no worries, raised a PR https://github.com/redhat-developer/service-binding-operator/pull/738 . Will follow up with PR reviews and follow ups

**Comment by pedjak** [comment]
With https://github.com/operator-framework/community-operators/pull/2796 merged, the operator can installed easily on Kubernetes, following the instructions:

https://operatorhub.io/operator/service-binding-operator

Installing the operator without OLM is tracked in #799 .
