### ISSUE TITLE
Proposal for refactoring E2E

### ISSUE THREAD

**Issue by pratikjagrut** [redhat-developer/service-binding-operator#537]
# Refactoring E2E

This is a proposal refactoring e2e tests.

## Motivation:
Current e2e tests are fine, they work well and serves the purpose. The difficulty arises when we want to add new tests. The basic part of the setup is quite similar for all the e2e tests, and there are some common variables too, as shown below.

```
var (
   retryInterval  = time.Second * 5
   timeout        = time.Second * 120
   cleanupTimeout = time.Second * 5
)
```

We can not define this variable or some common functions again in new test file as all tests are in one package and unexported global variable has package level scope.

Some common functions like CreateApp, CreateDB etc. looks tightly bounded to current e2e tests scenario.

## Proposed solution:
Creating a new file say `utils.go` in the same package where we’ll define common variables and functions. We can create teardown and setup functions like `bootstrapping namespace`. 

This will set a regular pattern or framework for writing new e2e tests and code will be better maintainable.

**Comment by pratikjagrut** [comment]
@pmacik @pedjak Now if we are concentrating on acceptance test then should this issue be closed?

**Comment by Avni-Sharma** [comment]
Closing this as we have shifted to acceptance test
