### ISSUE TITLE
Support duck type from spec

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#548]
The Service Binding Specification introduces a [duck type](https://github.com/k8s-service-bindings/spec#provisioned-service) for provisioned services to make themselves bindable.  

To support the desire of being spec compliant, this issue should enhance SBO to support this pattern for target services.

**Comment by sbose78** [comment]
Thanks.

**Comment by sbose78** [comment]
@pedjak could you schedule this for a design review please with the team? I've tentatively marked this for 0.4 ( cc @baijum )
