### ISSUE TITLE
Implement scorecard tests.

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#552]
Currently, we have a target for validating the operator releases https://github.com/redhat-developer/service-binding-operator/blob/master/Makefile#L476. When we raise a PR for an operator update/upgrade release at OperatorHub a couple of scorecard tests are run against the operator bundle. We should explore more of these tests and what does it entail. Refer https://sdk.operatorframework.io/docs/scorecard/scorecard/ for configuring scorecard tests. Such scorecard tests should be implemented as a makefile target which may be used whenever we want to make a release.

**Comment by pedjak** [comment]
the scorecard tests are not executed anymore at PR submission.

**Comment by pedjak** [comment]
Closing as not relevant anymore - the tests are not executed at OpenHub PR submission.
