### ISSUE TITLE
Support air gap scenarios

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#557]
We have recently [updated](https://github.com/application-stacks/runtime-component-operator/pull/146) the Runtime Component Operator to be compliant with Red Hat's requirement for air gap scenarios.

Given that SBO is an essential Operator for many scenarios, we would like to request for it to also comply with the air gap requirements.  

Additional details in 
* https://docs.openshift.com/container-platform/4.3/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs 
* https://docs.openshift.com/container-platform/4.3/openshift_images/image-configuration.html#images-configuration-registry-mirror_image-configuration

**Comment by sbose78** [comment]
Agreed, we gotta do this. @pmacik , could you queue up a testing plan for this?

**Comment by pmacik** [comment]
> Agreed, we gotta do this. @pmacik , could you queue up a testing plan for this?

Sure, @sbose78 I'll give it a thought or two.

**Comment by ianpartridge** [comment]
Hi! Is there any update on this? 🙂

**Comment by sbose78** [comment]
Since we do not have any related images that the controller would be referring directly, we should be good. The only image that the project works with is the one in the CSV's deployment, so we are implicitly compatible with disconnected environments, *I think*. 

@pedjak, thoughts?

**Comment by ianpartridge** [comment]
It's the one in the CSV that needs updating to support disconnected installation, I think.

Currently, the CSV's `spec.containerImage` is `quay.io/redhat-developer/app-binding-operator:72abb50`.  `72abb50` is a tag not a SHA and https://docs.openshift.com/container-platform/4.5/operators/olm-restricted-networks.html states operators must "Reference all specified images by a digest (SHA) and not by a tag."

https://access.redhat.com/articles/4740011 says that SBO currently does not support disconnected mode.

**Comment by pedjak** [comment]
> Currently, the CSV's spec.containerImage is quay.io/redhat-developer/app-binding-operator:72abb50. 72abb50 is a tag not a SHA

@ianpartridge you are right, the reference needs to contain sha.

**Comment by pedjak** [comment]
Fixed in https://github.com/operator-framework/community-operators/pull/2796 - the published CSV refers the operator image using sha.
