### ISSUE TITLE
Community Meeting - July 23, 2020

### ISSUE THREAD

**Issue by cdlliuy** [redhat-developer/service-binding-operator#581]

**Comment by cdlliuy** [comment]
1. PR #521,  why the test can't be kicked off
2. PR #513,  thanks to make the volume optional.  We would like to see it to be merged.
Once #521 and #513  merged, we would like to get the latest master head into our env to have a fully test indoor .
3.   The backend watcher #508

**Comment by DhritiShikhar** [comment]
Closing this. Next meeting -> https://github.com/redhat-developer/service-binding-operator/issues/586
