### ISSUE TITLE
If applicationSelector gets replaced with an App2, the App1 still points to the service.

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#585]
Considering the following steps:

Scenario 1
Create a SBR where:
App 1 points to DB 1
App 1 is injected with the intermediate secret.

Scenario 2:
App 1  points to DB 1
Update SBR to have App 2 point to DB 1
App 2 will point to DB 1 , but App 1 might continue pointing to DB 1

App1 who has now resigned from the SBR still has the intermediate secret in the deployment as secretRef.

**Comment by DhritiShikhar** [comment]
When ServiceBindingRequest is updated to replace/ remove ApplicationSelector, then
[1] secret reference should be removed from application

before proceeding further.

Similarly, when ServiceBindingRequest is updated to replace/ remove a Service, then
[1] intermediate secret should be deleted

before proceeding further.

**Comment by pedjak** [comment]
@sbose78 what would the real use case for updating existing service binding to point to fully different application. It looks very academic to me. Instead,  how about the following approach:

* we do not allow updating application selector once the service binding once created
* if needed to rebind a service to another application, the existing service binding need to be deleted and another service binding created.

IMHO, this workflow is more explicit to users.

**Comment by sbose78** [comment]
I agree.

We should check with the developer console lead if there are any experience expectations that drive this.

> we do not allow updating application selector once the service binding once created

Fair enough. Anyway, can we have two exceptions:
* We allow if no application was provided in the first place ( generic binding )
* we allow if application was provided but not found ( erroneous CR ) ?

**Comment by pedjak** [comment]
Obsolete by #896
