### ISSUE TITLE
Support specification extension for custom projection

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#590]
One of the specification extensions defines how to support a [custom project](https://github.com/k8s-service-bindings/spec#custom-projection), where another Operator owns the application deployment.  

This issue will track SBO's compliance to this extension, including the creation of the [internal CRD](https://github.com/k8s-service-bindings/spec/blob/master/internal.service.binding_servicebindingprojections.yaml) which will be picked up by the application reconciler.

This is a needed scenario to support the combination of Runtime Component Operator with the Service Binding Operator, in a spec-compliant way.

**Comment by sbose78** [comment]
Could you or someone in your team provide an enhancement proposal on this please?

**Comment by arthurdm** [comment]
definitely - @navidsh will be looking into this proposal.

**Comment by pedjak** [comment]
Obsolete - custom projections got replaces by `ClusterApplicationResourceMapping`
