### ISSUE TITLE
Run e2e/acceptance tests on Kubernetes

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#594]
Possibly on travis CI using a Kind cluster?

**Comment by sbose78** [comment]
cc @redhat-developer/service-binding 

@qibobo Would you or someone else from your team be able to take care of this? I really wish to avoid our PRs breaking the experience on Kubernetes. There's extensive testing for OpenShift, but none for vanilla kubernetes.

**Comment by pedjak** [comment]
the acceptance testing framework has been designed to support running tests against an arbitrary cluster, providing the needed `kubeconfig`. Our plan is run the same set of tests against various kubernetes and openshift clusters. Nevertheless, some of scenario steps use `oc` command to perform actions, and this need to be changed to `kubectl`. 

Using Travis and KinD could be a good starting point.

/cc @pmacik

**Comment by cdlliuy** [comment]
@pedjak ,  where the Kind cluster provision can happen ?   I didn't find the piece to set  Kubeconfig  env in .travis.yaml (maybe I am not careful enough .. Correct me if I am wrong) ,  also, I didn't notice the acceptance test will be trigger through .travis.yaml

It is not complex to create a Kind cluster , and easy to put it into .travis.yaml.

**Comment by pedjak** [comment]
> where the Kind cluster provision can happen ? 

It can happen in `travis.yaml` file, but we did not setup anything yet, but it is doable.

**Comment by Avni-Sharma** [comment]
Hi @cdlliuy The kubeconfig is being set as an env var and being consumed here https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/features/steps/command.py#L16

**Comment by sbose78** [comment]
I see a Travis job already :)

**Comment by cdlliuy** [comment]
@sbose78 ,  so is this issue resolved?  I still can't find where acceptance is launched in travis.yaml...

**Comment by sbose78** [comment]
No, there is a Travis job but it doesn't do much

**Comment by baijum** [comment]
Here is an example: https://github.com/lilic/travis-minikube

**Comment by baijum** [comment]
Another example using Kind: https://github.com/xmudrii/travis-kind

**Comment by jasperchui** [comment]
Closing as its completed.  Thanks.
