### ISSUE TITLE
Community Meeting - Aug 6, 2020

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#595]

**Comment by sbose78** [comment]
https://github.com/redhat-developer/service-binding-operator/issues/594

**Comment by cdlliuy** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/513

**Comment by DhritiShikhar** [comment]
Meeting Minutes:

[1] #513 will be merged by early next week

[2] Bobo will test #513 and post result on the issue.

**Comment by DhritiShikhar** [comment]
next meeting -> https://github.com/redhat-developer/service-binding-operator/issues/600
