### ISSUE TITLE
Community Meeting - August 13, 2020

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#600]

**Comment by qibobo** [comment]
status for https://github.com/redhat-developer/service-binding-operator/pull/513

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/issues/594

**Comment by DhritiShikhar** [comment]
Meeting Minutes:

[1] #513 
- a bit more polishing is required for #513 Hopefully will get merged by mid-next week. [Predrag]
- API is modified slightly [Baiju]

**Comment by DhritiShikhar** [comment]
Closing this. Next meeting -> https://github.com/redhat-developer/service-binding-operator/issues/609

**Comment by DhritiShikhar** [comment]
PR #513 has been a part of the agenda in more than 5 last community meetings.

Let's try to get it merged before next community call @baijum @pedjak ?
