### ISSUE TITLE
Identify sanity tests from acceptance-tests and have CI prow job for the same

### ISSUE THREAD

**Issue by shvasude** [redhat-developer/service-binding-operator#614]
Background: 
For now we have acceptance-tests that validates all the scenarios. To say binding works functionally in a narrow scope or all the basic functionality works for binding, It is always good to have a suite which confirms that the basic functionality works. 

if this fails, then we can assure that the binding fails fundamentally and there is no need to further testing to be done until it is fixed.

Proposal: 

- Identify scenario and add tags to the framework as `--tags==@sanity`

- create independent CI prow job just to run the sanity tests

**Comment by DhritiShikhar** [comment]
@shvasude Can you explain a bit more?

> which confirms that the basic functionality works

What would you consider a basic functionality and a non-basic functionality?

**Comment by shvasude** [comment]
Basic functionality is positive flow or the most important functions that works. The result of this tests are used to decide if it is stable enough to proceed with further testing.

**Comment by DhritiShikhar** [comment]
Okay

**Comment by pedjak** [comment]
Our CI jobs run all acceptance tests, there is no need to introduce another job running just a subset of them
