### ISSUE TITLE
create jira test cycles for releases automatically from feature files

### ISSUE THREAD

**Issue by shvasude** [redhat-developer/service-binding-operator#615]
Creating JIRA issues (Task/Epic) through JIRA rest API that has link to a specific spec/feature file
    Update JIRA issues (Task/Epic/Story) through JIRA rest API with any data that are editable
    Get JIRA issues information

Reference: https://github.com/shvasude/featurefiledemo/tree/setToken

**Comment by pedjak** [comment]
we would like to start using more GitHub as the source of truth.

**Comment by sbose78** [comment]
> we would like to start using more GitHub as the source of truth.

+1

**Comment by DhritiShikhar** [comment]
> we would like to start using more GitHub as the source of truth.

+1

**Comment by jasperchui** [comment]
Closing. Reopen if needed. Thanks.
