### ISSUE TITLE
Explore policy agent- OPA Gatekeeper

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#617]
To implement a way for Allowing binding to proceed only if the user has permission to read relevant objects, we should explore OPA Gatekeeper- https://github.com/open-policy-agent/gatekeeper
Gatekeeper is an admission webhook and the policies are deployed as CRDs.

Gatekeeper has an audit functionality that allows you to check existing resources in the cluster against all the policies. Audit runs periodically and the violations will be reported in the status of each failed Constraint (policy).

**Comment by Avni-Sharma** [comment]
Test can be catered by https://www.conftest.dev/

**Comment by pedjak** [comment]
Closing as obsolete.
