### ISSUE TITLE
Improve Quick Start docs

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#625]
We should address the following iteratively. 

1. Use CatalogSource instead of OperatorSource. https://github.com/redhat-developer/service-binding-operator/issues/624
2. Show a non-OLM way of installing ( assumption that everyone has OLM could be wrong )
3. Show an OLM way of installing on Kubernetes https://github.com/redhat-developer/service-binding-operator/issues/623

**Comment by pedjak** [comment]
Closing since 1. and 3. are done, tracking 3. in #799
