### ISSUE TITLE
Remove finalisers in the controller

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#626]
Now that https://github.com/redhat-developer/service-binding-operator/pull/596 is merged, we can consider removing finalisers as no cleanup is required on unbind(). The annotations has been removed and ownerRefs added to the intermediate secret which makes the presence of finalisers redundant

cc @isutton

**Comment by sbose78** [comment]
Does this take into account that application objects need to be modified too ?

**Comment by pedjak** [comment]
Obsolete by #919
