### ISSUE TITLE
Email acceptance test reports to stakeholders

### ISSUE THREAD

**Issue by shvasude** [redhat-developer/service-binding-operator#627]
For now, we have acceptance reports generated in CI and we have to download the artifacts to see reports. 
Instead, send an email with reports to respective email recipients. 

Challenge: Currently, by using allure reports, xml reports are served by allure. Need to look into an html report or something.

**Comment by pmacik** [comment]
There is a way to generate the html report by using `allure generate ...` command.

**Comment by jasperchui** [comment]
closing. Reopen if needed. Thanks.
