### ISSUE TITLE
Infinite reconcile loop in case of two SBRs sharing an application

### ISSUE THREAD

**Issue by pmacik** [redhat-developer/service-binding-operator#630]
The acceptance test [scenario](https://github.com/redhat-developer/service-binding-operator/commit/7cfa82b8efd343df5f6c490cefc38e501c3baf84#diff-b6193b748058d6c0fbd1afa25adbb880R11) for two services being bound to a single application via 2 separate SBRs reproduces this while running in a fresh and clean OpenShift cluster. After the two requests are created, the SBO constantly reconciling the two requests `binding-request-1` and `binding-request-2` and re-deploying the deployment's pods over and over again.

The two SBRs are created in sequence one after the other.

**Comment by pmacik** [comment]
I've noticed that the first SBR has BindingFail status:
```json
{"lastHeartbeatTime":"2020-08-20T15:58:45Z",
"lastTransitionTime":"2020-08-20T15:58:45Z","message":"Operation cannot be fulfilled on deployments.apps \"nodejs-app\": the object has been modified; please apply your changes to the latest version and try again","reason":"BindingFail","status":"False","type":"InjectionReady"}
```

**Comment by pmacik** [comment]
[operator log](https://gist.github.com/pmacik/5c7743f1f9dd7b4ff0c97e208fc65b4b)

**Comment by pmacik** [comment]
@pratikjagrut Could you please check this, since you are the author of the acceptance test scenario? Thx

**Comment by durera** [comment]
Hitting this at the moment, but I have a related question ... once this is fixed, how will SBR handle to bindings of the same type given the naming convention at the moment is to prefix each secret key with `Kind`?

e.g. 

- binding1 binds to instance1 of resource Foo to application1, creates a secret containing FOO_USERNAME=bob / FOO_PASSWORD=passw0rd
- binding2 binds to instance2 of resource Foo to application1, creates a secret containing FOO_USERNAME=john / FOO_PASSWORD=password123
- application1 now has conflicting env vars for FOO_USERNAME & FOO_PASSWORD declared

If I attempt to bind those both to the same application, even without this current issue there's going to be a conflict, or is there something in place to avoid this already that I'm just not aware of?

I'm actually more interested in _not_ binding to any application at all and just making the secrets created by SBR available for the operator that defines the SBRs to use as it sees fit within the resources it manages, but if I'm reading https://github.com/redhat-developer/service-binding-operator/issues/89 correctly, the equivalent of this "don't bind" is actually binding everything to the operator deployment (hence hitting this issue right now), and now I'm curious about how this will eventually work with bindings to multiple instances of the same resource kind when can get past this bug.

**Comment by DhritiShikhar** [comment]
@durera 

> how will SBR handle two bindings of the same type given the naming convention at the moment is to prefix each secret key with Kind?

This is definitely a bug which needs to be fixed.

However, we do have a workaround for now.

>  or is there something in place to avoid this already that I'm just not aware of?

Yes.

We can use `envVarPrefix` to distinguish between env vars from different SBRs

Consider these two different SBRs `binding-request-2` and `binding-request` which inject information in the same deployment `nodejs-rest-http-crud`

![Screenshot from 2020-08-31 18-27-09](https://user-images.githubusercontent.com/6303309/91722398-d0a15d00-ebb7-11ea-9b20-425befacea67.png)

**NOTICE `envVarPrefix` set as `binding2` and `binding1` in SBRs `binding-request-2` and `binding-request` respectively.**


The two different intermediate secret are prefixed with different envVarPrefix.

![Screenshot from 2020-08-31 18-27-05](https://user-images.githubusercontent.com/6303309/91722724-4c9ba500-ebb8-11ea-829b-b38c8653aa9c.png)

**Comment by DhritiShikhar** [comment]
> I'm actually more interested in not binding to any application at all and just making the secrets created by SBR

@durera In this video, you can see that:

1. Collection of data and creation of intermediate secret is successful, thus the `CollectionReady` is true.

2. Injection of secret did not happen because applicationSelector is missing, thus
`InjectionReady` is false with reason `EmptyApplicationSelector`.

https://youtu.be/uTODhkkmH5w

**Comment by DhritiShikhar** [comment]
@pmacik I was able to reproduce this error locally.

Yes,  the SBO constantly reconciles the two requests and re-deploying the deployment's pods over and over again.

**Comment by DhritiShikhar** [comment]
@sbose78 Would this be a part of fixes for 0.3.0 ?

**Comment by sbose78** [comment]
>the SBO constantly reconciles the two requests and re-deploying the deployment's pods over and over again.

@DhritiShikhar , as a workaround to creating two SBRs, can the user create one SBR with multiple backing services listed?

**Comment by DhritiShikhar** [comment]
@sbose78 Yes

**Comment by DhritiShikhar** [comment]
JIRA task - https://issues.redhat.com/browse/APPSVC-712

**Comment by DhritiShikhar** [comment]
> I've noticed that the first SBR keeps `BindingFail` status:
> 
> ```json
> {
> "lastHeartbeatTime":"2020-08-20T15:58:45Z",
> "lastTransitionTime":"2020-08-20T15:58:45Z",
> "message":"Operation cannot be fulfilled on deployments.apps \"nodejs-app\": the object has been modified; please apply your changes to the latest version and try again",
> "reason":"BindingFail",
> "status":"False",
> "type":"InjectionReady"
> }
> ```

This is a video where I tried to reproduce this bug locally - https://youtu.be/1Ojt-VFBYLU

I can see that status of both the ServiceBinding `sbr-1` and `sbr-2` are updated properly with both `collectionReady` and `injectionReady` as `True`.

which means, 
a) Secret `sbr-1` and `sbr-2` are populated properly. I cross-checked.
b) deployment `nodejs-rest-http-crud` contains:

```
        envFrom:
        - secretRef:
            name: sbr-1
        - secretRef:
            name: sbr-2
```

The only undesirable behaviour is constant creation and termination of application pods.

**Comment by DhritiShikhar** [comment]
Also, there is an acceptance test for this -> https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/features/bindAppToMultipleServices.feature#L11

**Comment by DhritiShikhar** [comment]
@pmacik Can you help me in understanding how to write an acceptance test for this specific scenario?

**Comment by DhritiShikhar** [comment]
Based on the discussion in cabal:
1. Adding a new step similar to "application should be re-deployed" step with timeout.
3. Timeout is worst case scenario. Action Item for Dhriti to think on a better solution.
