### ISSUE TITLE
Sharing operator CRD with the native group "apps.openshift.io" 

### ISSUE THREAD

**Issue by garbagego** [redhat-developer/service-binding-operator#637]
Steps to Reproduce:
-> openshift 3.11 cluster with cluster-admin

```
# oc create -f https://raw.githubusercontent.com/redhat-developer/service-binding-operator-manifests/0c3feda5c95b2e97791fb9501cc14bbf89d11249/0.1.1-274/apps.openshift.io_servicebindingrequests_crd.yaml

# oc get crd servicebindingrequests.apps.openshift.io

# oc api-resources 
```
 **error: unable to retrieve the complete list of server APIs: apps.openshift.io/v1alpha1: the server could not find the requested resource**

$  oc version
oc v3.11.170
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.11.188
kubernetes v1.11.0+d4cacc0

api logs:

E0409 13:25:22.835777       1 memcache.go:147] couldn't get resource list for apps.openshift.io/v1alpha1: the server could not find the requested resource
E0409 13:25:32.877753       1 memcache.go:147] couldn't get resource list for apps.openshift.io/v1alpha1: the server could not find the requested resource
E0409 13:25:42.956812       1 memcache.go:147] couldn't get resource list for apps.openshift.io/v1alpha1: the server could not find the requested resource

**Comment by sbose78** [comment]
Hey, have you tried this https://github.com/redhat-developer/service-binding-operator/issues/409 ?

**Comment by sbose78** [comment]
Closing this since #409 has details for openshift 3.x usage.
