### ISSUE TITLE
Community Meeting - August 27, 2020

### ISSUE THREAD

**Issue by baijum** [redhat-developer/service-binding-operator#642]
* Date and Time: Thursday, August 27⋅4:45 – 5:30pm IST
* Meeting URL: https://meet.google.com/jti-pujt-zqs

Agenda:

1. Breaking API changes and 0.2.0 release
2. Status update on PR #513

**Comment by DhritiShikhar** [comment]
@baijum We have people from different time zones joining the meeting. 
So, can you mention `IST` in the meeting time?

**Comment by baijum** [comment]
> @baijum We have people from different time zones joining the meeting.
> So, can you mention `IST` in the meeting time?

Done

**Comment by Avni-Sharma** [comment]
Any updates on https://github.com/redhat-developer/service-binding-operator/issues/594
