### ISSUE TITLE
Propagate updates from services' resource to the app in non OLM environment

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#650]
Few findings on the SBO, while debugging for #508 , for which a fix is proposed in #597 . Currently, we have watches only for CRDs that are listed as ownedCRDs in the CSVs. So if we have a service that is not (Operator backed/ via CSV) then on applying the SBR yaml we will have a connection established(i.e a connection is established between the app and the service), however, changes from the service's CR won't be propagated. A potential workaround is to create a SBR resource again or delete/update the intermediate secret so that the reconcile retriggers,  but we might want to avoid it. This would be required for complete support on non OLM environment. It is another thing, that after some retryInterval we can get the value propagated, but again that would be because of the retryInterval and not because of a change that occurred on the service's CR.
Follow up tasks-  watch for all CRDs , and not limited to just CSV. (Is it okay/feasible to watch for all CRDs?)

**Comment by sbose78** [comment]
It is fine to watch all CRDs except specific API groups which we wouldn't want to watch in Openshift because they are control plane CRDs

Maintain a denylist that is maintained as a
* Initially a static array in the code
* configurable using env vars 
* Configurable by admins in a configmap that is that is to be configured in a specific namespace.

**Comment by DhritiShikhar** [comment]
> It is fine to watch all CRDs except specific API groups which we wouldn't want to watch in Openshift because they are control plane CRDs

+1

**Comment by pedjak** [comment]
Obsolete by #903
