### ISSUE TITLE
Operator version does not match with the latest release v0.1.1-352

### ISSUE THREAD

**Issue by prietyc123** [redhat-developer/service-binding-operator#654]
Installing subscription `service-binding-operator` on 4.6 cluster 

```
> oc get subscription -n openshift-operators service-binding-operator -o yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-binding-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: service-binding-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: service-binding-operator.v0.1.1-364
```
but `startingCSV` is referring to some unknown version `v0.1.1-364` which I guess does not matching the latest release version. Is it the expected behavior?

**Comment by sbose78** [comment]
Thank you for reporting this @prietyc123 .

> which I guess does not matching the latest release version.

Could you help understand what the latest release version is as per your understanding? 


cc @pedjak @DhritiShikhar

**Comment by prietyc123** [comment]
> Could you help me understand what the latest release version is as per your understanding?

AFAIU ideally it would be the latest release [v0.1.1-352](https://github.com/redhat-developer/service-binding-operator/releases/tag/v0.1.1-352)

**Comment by Avni-Sharma** [comment]
Latest release got merged https://github.com/operator-framework/community-operators/pull/2253 which is indeed 0.1.1-364

**Comment by sbose78** [comment]
> ideally it would be the latest release v0.1.1-352

Ah got it, thank you!

That's actually a distinct release that isn't the one you are trying out when you use "startingCSV: service-binding-operator.v0.1.1-364" 
https://github.com/operator-framework/community-operators/tree/master/community-operators/service-binding-operator/0.1.1-352


@pedjak @Avni-Sharma  As a good housekeeping practice, we should do a Github release with the commit relevant to https://github.com/operator-framework/community-operators/tree/master/community-operators/service-binding-operator/0.1.1-364

**Comment by Avni-Sharma** [comment]
@sbose78 . Have already made a similar suggestion to @pedjak  and brought it up in Cabals too :)

**Comment by pedjak** [comment]
> Have already made a similar suggestion to @pedjak and brought it up in Cabals too :)

@sbose78, I do not think that we should release tarballs/zip archives on GitHub, nobody consumes that. Instead, we should put the tag on the relevant commit.

**Comment by sbose78** [comment]
Sure, whatever we do, let's ensure things show up on the home page "releases" section. The source code tar is a by-product which Github gives for free.

We should probably add a few lines on what's the best way to consume the release.

![image](https://user-images.githubusercontent.com/545280/91746536-c3ba4480-eb8a-11ea-9829-3909ef64a46a.png)

**Comment by sbose78** [comment]
https://github.com/redhat-developer/service-binding-operator/releases

Thank you @pedjak , closing this. @prietyc123 , feel free to continue the conversation though!

**Comment by prietyc123** [comment]
Thanks @sbose78 for addressing the concern.

**Comment by DhritiShikhar** [comment]
@sbose78 @pedjak 

Just to conclude,

**With every Operatorhub release there should be Github release as well.**

Right?

**Comment by pedjak** [comment]
>With every Operatorhub release there should be Github release as well.

Yes.
