### ISSUE TITLE
binding:env:attribute being missed/ignored currently while fetching info from x-descriptors

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#656]
If we try to export the backing service values via just the x-descriptors(i.e CSV in OLM) then `binding:env:attribute` or `binding:volumemount:attribute` is missed currently here https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebindingrequest/service.go#L82 .  Need to tackle it as https://gist.githubusercontent.com/isutton/61e20b4034207ef065821246df6ab3a4/raw/2764b977396f4ac9148b7dd4ea5b2e234bddbbe4/loadDescriptor.go as suggested by @isutton .

**Comment by pedjak** [comment]
Got obsolete after merging https://github.com/redhat-developer/service-binding-operator/issues/403
