### ISSUE TITLE
Community Meeting - September 3, 2020

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#660]

**Comment by DhritiShikhar** [comment]
Agenda:

[1] Discussion on adding a `Ready` status:
https://github.com/redhat-developer/service-binding-operator/pull/565#issuecomment-684356894

**Comment by cdlliuy** [comment]
[2] Discuss on https://github.com/redhat-developer/service-binding-operator/pull/647#issuecomment-683818261

**Comment by Avni-Sharma** [comment]
Do we need any follow up GitHub issues regarding status or any other discussion?

**Comment by cdlliuy** [comment]
@Avni-Sharma ,  https://github.com/redhat-developer/service-binding-operator/issues/665 for the status ready discussion.
