### ISSUE TITLE
Change timestamp to human readable such RFC3339/ISO8601 format in log

### ISSUE THREAD

**Issue by qibobo** [redhat-developer/service-binding-operator#686]
In current log the timestamp is difficult for developers to read and understand.
`{"level":"debug","ts":1600931556.2031412,"logger":"mapper","msg":"resource is not a service declared by the SBR","Object.Namespace":"default","Object.Name":"thetranslator-46"}`

So it is better to change tot RFC3339 format date-time format:

`{"level":"debug","dt":2020-09-24 15:00:00 000,"logger":"mapper","msg":"resource is not a service declared by the SBR","Object.Namespace":"default","Object.Name":"thetranslator-46"}`

**Comment by Avni-Sharma** [comment]
I feel that shifting to only date time format would be good and like this suggestion, unless folks feel otherwise. @redhat-developer/openshift-dev-services please feel free to post your thoughts.

**Comment by isutton** [comment]
I'm fine with this change.

**Comment by qibobo** [comment]
This can be done by changing the deployment parameter:

--zap-time-encoding string - Sets the zap time format (epoch, millis, nano, or iso8601)

**Comment by cdlliuy** [comment]
@baijum ,  as discussion on the community meeting,   we will put effort on this issue to raise this enhancement.

**Comment by qibobo** [comment]
@cdlliuy @baijum 
No code change is needed for this issue. The logger will output iso8601 format datetime if we add --zap-time-encoding=iso8601 when start the SBO.
