### ISSUE TITLE
Community Meeting - September 24, 2020

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#688]

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/issues/686

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/681

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/issues/508

**Comment by sbose78** [comment]
Would someone from the codeengine team be able to contribute docs for https://github.com/redhat-developer/service-binding-operator/issues/536 ?

**Comment by Avni-Sharma** [comment]
On it
