### ISSUE TITLE
Provide documentation for JSONPath support in customEnvVar

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#705]
Currently, customEnvVar API in the ServiceBinding supports both 1) go templating and JSONPath Support. While the documentation for the go templating exists, it would be good if we have for JSONPath as well. Refer link https://github.com/redhat-developer/service-binding-operator/pull/412 when this support was added. in https://github.com/redhat-developer/service-binding-operator/tree/master/examples for the examples *_customvar/ we can show ServiceBinding with go templating and JSONPath both.

**Comment by pedjak** [comment]
JSONPath support dropped in the effort to get more compatible to the spec.
