### ISSUE TITLE
Provide documentation for projecting information as "files"/volume mounts

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/service-binding-operator#706]
There are multiple ways of projecting information as files/volume mounts based on information from 
* CR/CRD annotations
* OLM descriptors

( even if the feature breaks in a release and marked as a known issue, we should document the expectation )

**Comment by Avni-Sharma** [comment]
Captured https://github.com/redhat-developer/service-binding-operator/blob/master/docs/application-author.md#accessing-the-binding-data-from-the-application . Feel free to reopen a new issue for future use cases.

**Comment by jasperchui** [comment]
Completed. Closing.
