### ISSUE TITLE
"application not found" when using `Deployment` instead of `deployments`

### ISSUE THREAD

**Issue by johnpoth** [redhat-developer/service-binding-operator#709]
Hi all,

Great project!

I get the error "application not found" when using `Deployment` instead of "deployments" in spec.applicationSelector.resource. I feel like Deployment should be valid ? Let me know if you need the full SBR.

Thanks!

**Comment by Avni-Sharma** [comment]
Hi @johnpoth . In the application we use the `resource` instead of `kind` . So the corresponding resource for a kind deployment would be `deployments` . Refer https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/apis/operators/v1alpha1/servicebinding_types.go#L71

**Comment by sbose78** [comment]
Yeah, the API supports GroupVersionResource, and not GroupVersionKind, though I can't think off head why.

Avni, do you remember why 🤨🤠

**Comment by Avni-Sharma** [comment]
Not quite sure. But we did discuss on moving everything to GVR. currently we use `gvr, _ := meta.UnsafeGuessKindToResource(gvk)`  and 
```
// UnsafeGuessKindToResource converts Kind to a resource name.
// Broken. This method only "sort of" works when used outside of this package.  It assumes that Kinds and Resources match
// and they aren't guaranteed to do so.
```
so it would be better to move to GVR for both

**Comment by johnpoth** [comment]
Ah makes sense then. Yeah Knative is using [Kind](https://github.com/knative/eventing/blob/69f5d21b88b5582717cd121b7696af72252bafd3/vendor/knative.dev/pkg/tracker/interface.go#L41) for it's SinkBinding which is similar to this, maybe that's why I was confused :) 

Feel free to close this now that it's clear :+1:

**Comment by isutton** [comment]
> Not quite sure. But we did discuss on moving everything to GVR. currently we use `gvr, _ := meta.UnsafeGuessKindToResource(gvk)` and
> 
> ```
> // UnsafeGuessKindToResource converts Kind to a resource name.
> // Broken. This method only "sort of" works when used outside of this package.  It assumes that Kinds and Resources match
> // and they aren't guaranteed to do so.
> ```
> 
> so it would be better to move to GVR for both

We've recently added a dependency on `meta.RESTMapper`, which can be used more effectively than relying on `UnsafeGuessKindToResource` since it takes in account API server registered resources.

GVRs seems to make sense since the user is always referring to resources in the API server.
