### ISSUE TITLE
ServiceBindingProjection support

### ISSUE THREAD

**Issue by johnpoth** [redhat-developer/service-binding-operator#716]
The Service Binding specification allows [custom projections](https://github.com/k8s-service-bindings/spec#custom-projection) through ServiceBindingProjection, it would be cool to support that. This would be useful when an application's Deployment is maintained by an Operator and shouldn't be modified by the Service Binding Operator. Thanks!

**Comment by Avni-Sharma** [comment]
Hi @johnpoth Thanks for the issue. 
Currently, in Service Binding we do support a scenario wherein the app isn't modified by the SB controller. If we skip mentioning `application` in the SB CR(application is an `optional` field) then we have only the service in the SB CR , that hints the controller that the secret created by the controller should not be injected in any deployment. Accordingly, the status of the service binding is updated 
`CollectionReady` - Data from respective backing services has been collected in an intermediate secret.
`InjectionReady` - If the app is not specified in the SB CR, then this status condition becomes False. If the injection does happen, i.e an app has been specified in the SB CR, then this condition is set as True.

**Comment by sbose78** [comment]
So, technically, if you skip the `spec.application` section, there isn't any application workload that the service binding operator is aware of, hence nothing would be modified.

**Comment by baijum** [comment]
> So, technically, if you skip the `spec.application` section, there isn't any application workload that the service binding operator is aware of, hence nothing would be modified.

The issue description mentioned "an Operator."  How will the operator get to know about the `Secret` resource created by Service Binding Operator? I mean, what is the discoverability pattern we are recommending?  BTW, I am not sure watching for `Secret` resources is a good choice based on this text (  https://kubernetes.io/docs/concepts/configuration/secret/#clients-that-use-the-secret-api ):

>   For these reasons "watch" and "list" requests for secrets within a namespace are extremely powerful capabilities and should be avoided, since listing secrets allows the clients to inspect the values of all secrets that are in that namespace. The ability to "watch" and "list" all secrets in a cluster should be reserved for only the most privileged, system-level components.

So the second choice would be to explicitly specify the  `Secret` from the "other Operator" custom resource.  We should have some guidelines about this problem.

In the case of the spec, discovering the `Secret` is not an issue. Also, there is a single source of truth where the final projection is happening.

**Comment by sbose78** [comment]
> BTW, I am not sure watching for Secret resources

Aren't controllers already watching secrets ? ( our controller already watches them, almost every operator watches secrets https://github.com/operator-framework/community-operators/tree/master/community-operators/ )

> I mean, what is the discoverability pattern we are recommending?

* The binding secret name could be same as that of the `ServiceBinding` that owns it.
* The binding secret name could have an annotation with the name of the `ServiceBinding` that created it.
* The `ServiceBinding` could have a field to let the user explicitly specify the name/pattern of the secret ( just like `generateName` )

**Comment by sbose78** [comment]
@johnpoth would you be able highlight your use case in more details?

**Comment by johnpoth** [comment]
Thanks @Avni-Sharma I'll look into not specifying `spec.application`. If I understand correctly, it will be up to my Operator to fetch the secret once `CollectionReady` is set on the SB and inject it on the Deployment resource. Hopefully the secret's name will be the same as the SB or will be indicated in the SB? I haven't noticed this in the [Spec](https://github.com/k8s-service-bindings/spec) so I'll have to check how portable this solution is.

@sbose78 My use case is pretty simple. We have an Operator called [camel-k](https://github.com/apache/camel-k) which creates integrations. These integrations are created by the Operator in the form of a Deployment, Knative Service or Cron Jobs depending on the situation. 

My first idea was to just have the SBO inject the info directly into the Deployment but that didn't fit well with camel-k's reconciliation loop which just reverted the changes as it wasn't the "desired" state. The Deployment resource is an intermediary resource and not really part of the API. It also becomes a little complicated on who would be allowed to change the Deployment resource etc...

My second idea is currently to rely on the custom projection so that camel-k will keep full ownership of these intermediary resources and modify the deployment itself (which requires a bit more work). Also maybe setting the number of replicas to 0 until the info is injected to avoid unnecessary scheduling. 

Thanks again for the feedback!

**Comment by sbose78** [comment]
Gotcha, thank you!

The secret name is going to be the same as that of the name of ServiceBinding object. 

Alternatively, the ServiceBinding's spec.status contains the name of the generated secret too!

This should work for your use case.

**Comment by baijum** [comment]
> Also, there is a single source of truth where the final projection is happening.

Let me elaborate this little more.  In the spec case, all the binding related configuration will be there in the `ServiceBinding` resource.  Whereas, in the case of SBO, the configuration will be split into two resources that belong to different operators.

SBO resource:

```
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: example-servicebinding
spec:
  services:
  - name: pg-instance
    group: postgresql.example.dev
    kind: Database
    version: v1alpha1
...
```

Resource from the other operator:

```
apiVersion: operators.example.com/v1alpha1
kind: ApplicationOperator
metadata:
  name: example-application
spec:
  sboSecret: example-servicebinding
  application:
    name: nodejs-rest-http-crud
    group: apps
    version: v1
    resource: deployments
...
```

If someone else creates another operator, they need to create another CRD with application projection details.

If Apache Camel K is unique and there are no other alternatives, the SBO solution might be sufficient.

**Comment by johnpoth** [comment]
Hi @baijum, @Avni-Sharma @sbose78,

Thanks for your reply. I've created an SB as we discussed, omitting `spec.application`:
```
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: binding-request
spec:
  services:
  - group: postgresql.baiju.dev
    version: v1alpha1
    kind: Database
    name: db-demo
```
I was expecting for a secret to be created containing the connection details to the Database however the generated secret seems to contain no data:

```
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2020-10-13T13:27:33Z"
  name: binding-request
  namespace: service-binding
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    controller: true
    kind: ServiceBinding
    name: binding-request
    uid: e2ae43cb-694b-4a51-a195-2c596a5f0dff
  resourceVersion: "3463403"
  selfLink: /api/v1/namespaces/service-binding/secrets/binding-request
  uid: 5e2fc664-492d-48af-a146-a3089a95f9f1
type: Opaque
```
I ran the Operator locally using `make local` on the project. Looking at the Operator [logs](https://gist.github.com/johnpoth/1895b4036dd2b190aa268fe581b8e015) it seems the Operator is having some issues.

This raises the question of *how* the Operator inspects a `Provisioned Service` (in this case a Database) and how it determines what information to expose in the intermediate Secret. The [Specification](https://github.com/k8s-service-bindings/spec#provisioned-service) mentions `.status.binding.name` pointing to a secret. But the Database in question does not specify it and yet the Operator still manages to extract relevant information and inject it in the Deployment (when specified in the SB). I assume this is done to make adoption easier.

**Comment by sbose78** [comment]
I think you bumped into the old annotation format :) New changes have gone in very recently https://github.com/operator-backing-service-samples/postgresql-operator/commit/ffa2481e9c15d1f8f776cb416a50b75a114b62c2

Here's the annotation guide https://github.com/redhat-developer/service-binding-operator/blob/master/docs/annotations.md

cc @baijum @Avni-Sharma

**Comment by sbose78** [comment]
Note, a provisioned service may 
*Either, have a .status.binding.name
*Or, have descriptors/annotations.

The second option is there because my expectation is that most service providers wouldn't be too willing to modify their CRDs/APIs, they would feel comfortable decorating what they have :)

**Comment by johnpoth** [comment]
Hi @sbose78 thanks! When running both projects from `master`, intermediary secret is generated correctly as follows:

```
$oc get secret binding-request -o yaml
apiVersion: v1
data:
  DATABASE_DB_HOST: MTcyLjMwLjUwLjIwNg==
  DATABASE_DB_NAME: ZGItZGVtbw==
  DATABASE_DB_PASSWORD: cGFzc3dvcmQ=
  DATABASE_DB_PORT: NTQzMg==
  DATABASE_DB_USER: cG9zdGdyZXM=
  DATABASE_DBCONNECTIONIP: MTcyLjMwLjUwLjIwNg==
  DATABASE_DBCONNECTIONPORT: NTQzMg==
  DATABASE_DBNAME: ZGItZGVtbw==
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: "2020-10-14T14:11:16Z"
  name: binding-request
  namespace: service-binding
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    controller: true
    kind: ServiceBinding
    name: binding-request
    uid: 1723eb9e-bd98-40bd-9d67-0da5434d48a2
  resourceVersion: "3583939"
  selfLink: /api/v1/namespaces/service-binding/secrets/binding-request
  uid: ee447b2a-891b-4076-90e7-82d288c78294
type: Opaque
```
Do you know if there are plans to make the database connection details standard ? e.g having the database host name always stored on key `DATABASE_DB_HOST`.  This could help make applications more portable and be able to easily switch between database providers. This point holds not only for databases but for different services.

I'll opt for this approach (relying on the intermediary secret) when integrating with the camel-k operator and maybe switch to `ServiceBindingProjection` eventually. I think we can close this issue and iterate somewhere else if need be.

Thanks everyone for all the help!

**Comment by jasperchui** [comment]
Closing.
