### ISSUE TITLE
Community Meeting - October 15, 2020

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#721]

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/issues/723
https://github.com/redhat-developer/service-binding-operator/issues/686

**Comment by dharmit** [comment]
#727

**Comment by cdlliuy** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/681

**Comment by dharmit** [comment]
#722
