### ISSUE TITLE
Can SBO link two Deployments?

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/service-binding-operator#722]
In odo, we're using SBO to link a component (Deployment in k8s lingo) with an Operator backed service. We need to provide users with the ability to link components (Deployments) with each other. I don't see any example related to this in SBO docs. Is it possible to do this with SBO?

To give some context, in odo v1, we used to do linking by injecting a secret into the component (in odo v1, we used to create Deployment Configs instead of Deployments). For example:
1. I have two components - comp-1 and comp-2 - that I have pushed to the OpenShift cluster.
    1. Every pushed component would have a corresponding secret on the cluster
1. I want to link comp-1 with comp-2 so that from the pod of comp-1, I can communicate with comp-2.
    1. I could do `odo link comp-2` from the component directory (directory containing `.odo` directory and odo config file) of comp-1.
1. Doing `odo link comp-2` would inject the secret into the pod spec of comp-1.

In the CRD spec for SBO, I read about custom env vars. Is it possible to use SBO to inject env vars stored in a secret into a target application? Note that in this case, there's no requirement of linking a component with a service so, the `services` array in the SBO spec would remain empty. Would that be OK or would creating a service binding fail if `services` array were to remain empty?

We would like to know the possibility for both the versions:  v0.1.1-364  & v0.3.0.

Related issue: https://github.com/openshift/odo/issues/3423

**Comment by Avni-Sharma** [comment]
services is a `required` field, so it can't be left empty

**Comment by dharmit** [comment]
So linking a "Deployment" type to another is not really possible using SBO? What about the secrets part I mentioned in the description? Not possible to inject/link a secret using it, right?

**Comment by dharmit** [comment]
@sbose78 is there an example yaml I can take a look at to understand this further? I couldn't find one under `examples` dir.

**Comment by baijum** [comment]
One option could be this spec idea: https://github.com/k8s-service-bindings/spec#direct-secret-reference

**Comment by sbose78** [comment]
Yeah we did have this working :-) https://github.com/redhat-developer/service-binding-operator/issues/611
We should see if it has broken along the way.

**Comment by sbose78** [comment]
It could also be binding a `deployment` with a `route` or ( route + secret )

https://github.com/redhat-developer/service-binding-operator/blob/master/examples/route_k8s_resource/README.md

**Comment by pedjak** [comment]
@dharmit can you please paste here how service deployment and application should look like and where the data to be injected are? Binding secret as service is supported, just want to understand more how the resources look like.

**Comment by dharmit** [comment]
@pedjak It's more about linking two `Deployment`s each created for one odo component. Say, for example, a user wants to connect a frontend component (maybe nodejs) to a backend component (maybe java).

Based on what I got from @sbose78, I think SBO already supports this. But on odo side, we haven't yet got a chance to implement this functionality. IMO, it's OK to close this issue and I'll re-open it if I'm stuck while implementing things.

**Comment by pedjak** [comment]
Thanks @dharmit , closing it then.
