### ISSUE TITLE
Make SBO available on OperatorHub.io

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/service-binding-operator#727]
Presently, Service Binding Operator is not available to install via the catalog source corresponding to https://operatorhub.io/. I think the Operators mentioned on that link are (almost?) same as those in https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators.

Asking for this because it would help install Service Binding Operator on a minikube cluster quite easily after enabling the olm addon via: `minikube addons enable olm`.

**Comment by baijum** [comment]
This is a good idea.

**Comment by sbose78** [comment]
Yeah, I've been tracking it here as well
https://github.com/redhat-developer/service-binding-operator/issues/623

Had pinged on slack a couple of times to check if @qibobo and team could take care of it :)

**Comment by Avni-Sharma** [comment]
SBO is now available on operatorHub https://operatorhub.io/operator/service-binding-operator
