### ISSUE TITLE
Add acceptance test to show update to a single annotation

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#734]
Refer: https://github.com/redhat-developer/service-binding-operator/pull/730#discussion_r507424063

This project has acceptance test to show addition of a new annotation to the existing list but we do not have any acceptance test to show **update of an existing annotation**.

Example:

Old Annotation:

`service.binding/ready: path={.status.ready}`

Updated annotation name:

`service.binding/readyFirst: path={.status.ready}`

OR Updated annotation path:

`service.binding/ready: path={.status.host}`

**Comment by Avni-Sharma** [comment]
It is related to https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/features/bindAppToService.feature#L809

**Comment by pedjak** [comment]
Obsolete by https://github.com/redhat-developer/service-binding-operator/issues/896
