### ISSUE TITLE
Community Meeting - Oct 29, 2020

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#737]
- Please add a topic in this thread and add a link to the Github issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/681

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/726

**Comment by Avni-Sharma** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/742 - Discussed in the community call :rocket:
