### ISSUE TITLE
Prevent the requirement of Clusterrole

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#739]
Currently, if we try to install SBO on minikube without proper clusterrole and clusterrolebindings I get a log output as 
```{"level":"error","ts":1603779779.0474563,"logger":"mapper","msg":"listing SBRs","Object.Namespace":"sbo-demo","Object.Name":"service-binding-operator-lock","error":"servicebindings.operators.coreos.com is forbidden: User \"system:serviceaccount:sbo-demo:service-binding-operator\" cannot list resource \"servicebindings\" in API group \"operators.coreos.com\" at the cluster scope","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/redhat-developer/service-binding-operator/pkg/log.(*Log).Error\n\t/go/src/github.com/redhat-developer/service-binding-operator/pkg/log/log.go:35\ngithub.com/redhat-developer/service-binding-operator/pkg/controller/servicebinding.(*sbrRequestMapper).Map\n\t/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebinding/mapper.go:150\nsigs.k8s.io/controller-runtime/pkg/handler.(*EnqueueRequestsFromMapFunc).mapAndEnqueue\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue_mapped.go:67\nsigs.k8s.io/controller-runtime/pkg/handler.(*EnqueueRequestsFromMapFunc).Create\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue_mapped.go:47\nsigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnAdd\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go:74\nk8s.io/client-go/tools/cache.(*processorListener).run.func1.1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292\nk8s.io/client-go/tools/cache.(*processorListener).run.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nk8s.io/client-go/tools/cache.(*processorListener).run\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71"}```

It seems it is caused due to https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebinding/mapper.go#L150 meaning we are trying to list SBR instances from all namespaces.

**Comment by pedjak** [comment]
It should be fixed with https://github.com/redhat-developer/service-binding-operator/issues/799

**Comment by Avni-Sharma** [comment]
We indeed need to watch on all the SBs in the cluster. Hence we need to add clusterrole for achieving this on minikube. OpenShift I think we never encounter that logged message in OLM cluster is because the roles are in csvs and the csv is installed in one ns but copied in all other ns.

**Comment by sbose78** [comment]
That is fine, we should have docs on the rbac requirements of the service account in a way that folks are aware why specific clusterrolebindings are required, and if they can be removed optionally.

**Comment by Avni-Sharma** [comment]
Incorporating clusterrole and binding in the release.yaml artifact.
