### ISSUE TITLE
Service Binding Operator should be available on operatorhub.io

### ISSUE THREAD

**Issue by kadel** [redhat-developer/service-binding-operator#772]
In order to make this available for more users and to the wider Kubernetes community, the SBO should be available on operatorhub.io.
This means that the SBO container images should be accessible by anyone (Red Hat login should not be required)

**Comment by DhritiShikhar** [comment]
@kadel 

According to https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#where-to-contribute

A PR has to be raised to https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators for Service Binding Operator to be available on operatorhub.io

**Comment by DhritiShikhar** [comment]
This is where SBO manifests lie -> https://github.com/redhat-developer/service-binding-operator-manifests

**Comment by DhritiShikhar** [comment]
@Avni-Sharma is already working on this issue.

Refer:
https://github.com/operator-framework/community-operators/issues/2742

**Comment by Avni-Sharma** [comment]
https://operatorhub.io/operator/service-binding-operator  . SBO is now available on operatorHub
