### ISSUE TITLE
Documentation of an installation process on Windows

### ISSUE THREAD

**Issue by kadel** [redhat-developer/service-binding-operator#773]
Running on Windows I can't execute the bash install script https://raw.githubusercontent.com/redhat-developer/service-binding-operator/master/install.sh. Documentation should provide a way to install this operator even for someone not using Linux or macOS.
We also want application developers to use this. 45% of developers  use Windows (https://insights.stackoverflow.com/survey/2020#technology-developers-primary-operating-systems)

**Comment by isutton** [comment]
Thanks for the request for documentation!

I personally use Docker for Desktop on Windows with the `openshift-ci/Dockerfile.tools` Dockerfile to perform the Makefile tasks; would this approach suit your needs?

**Comment by pedjak** [comment]
Meanwhile, our instructions follow official OperatorHub instructions: https://operatorhub.io/operator/service-binding-operator

Please reopen if it still does not fit usage on Windows.
