### ISSUE TITLE
December 3, 2020

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#776]
- Please add a topic in this thread and add a link to the Github issue/PR associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on Github before coming into the meeting

**Comment by kadel** [comment]
**Topic proposal:** Service Binding Operator should be available on operatorhub.io #772

**Comment by qibobo** [comment]
https://github.com/redhat-developer/service-binding-operator/issues/790
