### ISSUE TITLE
Can not rerun the continuous-integration/travis-ci/pr job

### ISSUE THREAD

**Issue by qibobo** [redhat-developer/service-binding-operator#779]
When the job `continuous-integration/travis-ci/pr`, I can not rerun it. There is no restart button in the travis page, nor a comment like `/test 4.6-acceptance` can work.

**Comment by pedjak** [comment]
Travis jobs are started on each push to PR. Only member of redhat-developer organization can restart jobs directly on the Travis page. Alternatively, you can run tests locally, following the steps listed in .travis.yaml

**Comment by Avni-Sharma** [comment]
@qibobo You might have got an email invitation as part of https://github.com/redhat-developer/service-binding-operator/pull/742 . can you PTAL in ur emails inbox
