### ISSUE TITLE
Create converter for spec CR

### ISSUE THREAD

**Issue by arthurdm** [redhat-developer/service-binding-operator#780]
This issue will track the creation of a converter in SBO that will watch for `ServiceBinding` resources from the [Service Binding Specification](https://github.com/k8s-service-bindings/spec#resource-type-schema-1) (with apiVersion `service.binding/v1alpha2`) and will automatically create SBO's `ServiceBinding` (with apiVersion `operators.coreos.com/v1alpha1`).  

The synchronization is only one-way, from spec to SBO resources.  

First pass should be just the spec's core, and later issues would bring in support for extensions.

**Comment by arthurdm** [comment]
cc @sbose78 @arturdzm

**Comment by arturdzm** [comment]
There are couple things I would like to clarify @sbose78 

1. In this case who would be responsible for providing spec CRD in the cluster, will it be installed together with  SBO or has to be manually installed by the user? Installing it through OLM CVS I think is not an option as it would confuse user in the OpenShift UI. Maybe operator can install the CRD on the start

2. The conversion can be achieved two ways, either through simple controller that would be part of SBO or mutating webhook that would intercept spec kind creation and produce the SBO kind.

3. SBO CR created by converter can be owned by spec controller which would allow one way sync, and prevent from user modifying the converted CR directly.

4. Will this converter be always on or should it be controlled with a flag / env var

5. Looks like the spec CR api group and name could be changing in the future if adopted into k8s sig

**Comment by sbose78** [comment]
I apologize for the late response :)

> In this case who would be responsible for providing spec CRD in the cluster, will it be installed together with SBO or has to be manually installed by the user? Installing it through OLM CVS I think is not an option as it would confuse user in the OpenShift UI. Maybe operator can install the CRD on the start

Fair concerns, I would want to deliver it the same way we do today. Till the implementation is stable, there's a way to annotate CRDs to hide it.

> The conversion can be achieved two ways, either through simple controller that would be part of SBO or mutating webhook that would intercept spec kind creation and produce the SBO kind.

I would prefer the controller approach since webhooks are expensive/invasive.

> SBO CR created by converter can be owned by spec controller which would allow one way sync, and prevent from user modifying the converted CR directly.

My suggestion ( not a very strong one though ) would be to start with _convert & forget_ initially to keep things light and simple. I would try to find out more about the reasoning behind (an advanced?) a user who chose to not update the spec’s ServiceBinding,  consciously.


> Will this converter be always on or should it be controlled with a flag / env var

Good idea, let's have an env var for it.

> Looks like the spec CR api group and name could be changing in the future if adopted into k8s sig

Sure, I'm aware. thanks for mentioning anyway!

**Comment by pedjak** [comment]
Spec API support got added by #985
