### ISSUE TITLE
Creating invalid binding is not posting status updates

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#783]
Creating as minor improvements rather than bug as this seems to be common for many operators. 

When binding is created operator seems to ending up with the endless loop of processing invald data.
I do not see any status change in the backing service CR and operator constantly reconciling values. 

Creating valid binding is not properly processed afterwards. The solution is to remove and install operator again (with cleared bindings)
Inspecting operator log gives us proper error message (although I would expect that being not available fo regular users

**Comment by DhritiShikhar** [comment]
@wtrocki 

Would you be able to share the invalid binding that you created?

**Comment by wtrocki** [comment]
Steps to reproduce are here:

https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql

If we follow the guide and misplace service version or group or name (anything wrong about service)

```
  - group: postgresql.baiju.dev
    version: `v1alpha1` => `v1`
    kind: Database
    name: db-demo
```

**Comment by DhritiShikhar** [comment]
Thanks @wtrocki

**Comment by wtrocki** [comment]
This is gone. Thank you so much @pedjak and team!
