### ISSUE TITLE
Operator loops over the same namespace again and again

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#785]
Service Binding Operator watches for resources in different namespace.

The operator log never halts. 

Refer: https://youtu.be/aY0Wss4iUgo

**Comment by Avni-Sharma** [comment]
What happens when you apply a sbr resource?

**Comment by pedjak** [comment]
What is the issue we would like to solve here?

**Comment by DhritiShikhar** [comment]
> Service Binding Operator watches for resources in different namespace.

This is expected from SBO to watch for resources in different namespace.

This is not an issue.
