### ISSUE TITLE
Run Spring PetClinic Sample Application

### ISSUE THREAD

**Issue by baijum** [redhat-developer/service-binding-operator#805]
Ref. https://github.com/spring-projects/spring-petclinic

**Comment by pedjak** [comment]
@baijum there is already a kubernetes based incarnation of the application:

https://github.com/spring-petclinic/spring-petclinic-cloud

IMHO, it could be used as the base.

**Comment by pmacik** [comment]
SBO quickstart now (#1085) uses this sample application
