### ISSUE TITLE
Map param names from service's secret to deployment

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/service-binding-operator#81]
We need a way to map param names from producer side (the service secret) to consumer side (the application).

Let me walk through an example, using the current model in the ServiceCatalog, but should be good starting point for describing the problem I see.

[MongoDB template](https://github.com/openshift/library/blob/master/official/mariadb/templates/mariadb-ephemeral.json) has 2 set of generated variables. The [credentials](https://github.com/openshift/library/blob/master/official/mariadb/templates/mariadb-ephemeral.json#L27-L30) and the [uri](https://github.com/openshift/library/blob/master/official/mariadb/templates/mariadb-ephemeral.json#L46). These have defined names in the generated ServiceBinding as: `database_name`, `password`, `root_password`, `username` and `uri`. This will always be named the same for any ServiceBinding created by this template.

When consuming the application, the author creator might have named his variables as: `DB_NAME`, `PWD`, `ADMIN_PWD`, `USER` and `JDBC_CONNECT_STRING`. This naming, of course, can be changed, but there's a lot of legacy applications that shouldn't need to be modified.

We need a way to say:
- Inject database_name from ServiceBinding secret into DB_NAME env in deployment
- Inject password from ServiceBinding secret into PWD env in deployment
- Inject database_name from ServiceBinding secret into DB_NAME env in deployment
- and so forth

And also, we need a way to say:
- Inject into JDBC_CONNECT_STRING the value: mysql://{USER}:{PWD}@{SERVICE_NAME}:{SERVICE_PORT}/{DB_NAME} 
As the URI my application requires is not in the same format the URI is provided in the ServiceBinding, cause every language (Python, Java,...) might need a URI in a different way.

These mappings should be done in the ServiceBindingRequest that this operator is defining, so any application can consume any service and don't require any code change or any changes to the Deployment definition. As the ServiceBindingRequest is the link between the Deployment and the consumed service.

Also, a developer might want to change from one service provider (template) to a different one (operator from ISV1) to yet another (operator from ISV2), and these might have also defined the names in different ways. The developer should not need to change his code (or the deployment) to adapt to how the service is naming these parameters.

Does it make sense what I say?

**Comment by sbose78** [comment]
+1 
We need this. This will be triaged and prioritized.

**Comment by sbose78** [comment]
Being implemented in https://jira.coreos.com/browse/ODC-1422

**Comment by ron1** [comment]
Is this related to https://github.com/redhat-developer/service-binding-operator/issues/88?
