### ISSUE TITLE
OpenShift Dedicated Support

### ISSUE THREAD

**Issue by pedjak** [redhat-developer/service-binding-operator#811]
The operator should be compatible with [OpenShift Dedicated](https://www.openshift.com/products/dedicated/). In order to verify that our acceptance tests should pass on OSD.

**Comment by Avni-Sharma** [comment]
Part of the GH issue is to find out any additional requirements, that might be missing currently and are needed for OpenShift Dedicated?

**Comment by DhritiShikhar** [comment]
As per @jasperchui 's suggestion 

I will be exploring this issue - what are the requirements to complete this issue.

**Comment by DhritiShikhar** [comment]
@pedjak @Avni-Sharma We would need an acoount on Openshift Dedicated to test and check if SBO is compatible.

**Comment by DhritiShikhar** [comment]
@sbose78 @pedjak @jasperchui 

I was able to very very partially test SBO on Openshift Dedicated.

Here is a video to demonstrate that -> https://youtu.be/2Ky8FOSPBdY

Once I get kubeadmin permissions on the cluster, I will be able to add/edit CRD with Service Binding annotations and properly test SBO with actual data injected in the application pods.

**Comment by Avni-Sharma** [comment]
I think we can also try `make test-acceptance`

**Comment by pedjak** [comment]
> I think we can also try make test-acceptance

Right, and eventually when they pass, we can claim that OSD is supported.

**Comment by DhritiShikhar** [comment]
Yup

**Comment by sbose78** [comment]
Thank you @DhritiShikhar , how did you install it?

**Comment by DhritiShikhar** [comment]
@sbose78 Initially @dewan-ahmed installed SBO operator for me... because I didn't have permissions.

**Comment by dewan-ahmed** [comment]
> @sbose78 @pedjak @jasperchui @Avni-Sharma
> 
> I was able to very very partially test SBO on Openshift Dedicated.
> 
> Here is a video to demonstrate that -> https://youtu.be/2Ky8FOSPBdY
> 
> Once I get kubeadmin permissions on the cluster, I will be able to add/edit CRD with Service Binding annotations and properly test SBO with actual data injected in the application pods.

What we've been told by the SRE team is OSD clusters deployed via CCS model won't give kubeadmin access. Instead, we have something called dedicated-admins that have reduced access level. I'm working with @DhritiShikhar and the SRE team to find workarounds to create/edit CRD/catalogsources with the dedicated-admin access we have.

**Comment by sbose78** [comment]
Sounds good to me Dhriti and Dewan.

Any chance we can use an existing operator in operatorhub?

**Comment by sbose78** [comment]
Or also try annotating CRs.

**Comment by jasperchui** [comment]
Closing as this is no longer needed. Thanks.

**Comment by sbose78** [comment]
🤔  Are we never planning to support binding on OSD ? 
Also, we've done some scale testing on this, I suppose? We should point to relevant details here.
