### ISSUE TITLE
Update CRD from v1beta1 to v1

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#813]
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; 
We should use apiextensions.k8s.io/v1 CustomResourceDefinition.
Operator-sdk latest version v1.3.0 still supports v1 by default and will also support v1beta1 as well. https://github.com/operator-framework/operator-sdk/releases/tag/v1.3.0. Tracking this here so that we don't miss out on this.

**Comment by pedjak** [comment]
Done in #848
