### ISSUE TITLE
Outputname is not honoured in mapFromDataFieldDefinition

### ISSUE THREAD

**Issue by johnpoth** [redhat-developer/service-binding-operator#817]
Example CRD annotation:

**service.binding/host: path={.status.dbConfigMap},objectType=ConfigMap,sourceValue=db.host**

**expected output:**
HOST: MTcyLjMwLjMuMTQ1

**actual output:**
DB_HOST: MTcyLjMwLjMuMTQ1

I can open a PR, thanks !

**Comment by sbose78** [comment]
Thank you a for the report, a PR would be great! <3
