### ISSUE TITLE
Add stronger assertion in updateVolumes(...) and removeVolumes(...) method

### ISSUE THREAD

**Issue by DhritiShikhar** [redhat-developer/service-binding-operator#821]
In [updateVolumes(...) method](https://github.com/redhat-developer/service-binding-operator/blob/master/pkg/controller/servicebinding/binder.go#L169), we type assert interface{} to map[string]interface{} 

We should add stronger types wherever possible like corev1.Volume in this case.

Similar suggestion for `removeVolumes(...)` and `extractSpecVolumes`

**Comment by pedjak** [comment]
@DhritiShikhar is this issue still relevant?

**Comment by DhritiShikhar** [comment]
This issue is being addressed in #750 PR
