### ISSUE TITLE
Allow constant values in service.binding/name annotations in CRD

### ISSUE THREAD

**Issue by johnpoth** [redhat-developer/service-binding-operator#843]
It would be cool to allow constant values in annotations so something like 

`service.binding/provider: postgresql`

For example, the `provider` and `type` entries are [recommended](https://github.com/k8s-service-bindings/spec#well-known-secret-entries) and can be the same across all underlying CR which warrants them to be constants. This also facilitates ad-hoc fixes. Thanks !

**Comment by pedjak** [comment]
We follow the annotation format defined [here](https://github.com/k8s-service-bindings/spec#non-olm-operator-and-resource-annotations), and it does not support something like this at the moment. Perhaps worth proposing it?

In the meantime, we can achieve the same result by defining [a mapping](https://github.com/redhat-developer/service-binding-operator/blob/master/docs/User_Guide.md#compose-custom-binding-variables):

```yaml
mappings:
   - name: provider
     value: postgresql    
```

**Comment by johnpoth** [comment]
Thanks @pedjak for the workaround! Proposed the [enhancement](https://github.com/k8s-service-bindings/spec/issues/140)

**Comment by pedjak** [comment]
Also, with #985 it is possible to specify `.type` and `.provider` directly on service binding resource.
