### ISSUE TITLE
Respect casing in service.binding/name annotations

### ISSUE THREAD

**Issue by johnpoth** [redhat-developer/service-binding-operator#844]
It seems all generated secret properties are uppercase so:

`service.binding/database: path...`

will result in a property named `DATABASE` and not `database`. It would be nice to respect the casing defined in the annotation or have a way to control it because some runtimes (e.g Quarkus) search for [properties](https://github.com/quarkusio/quarkus/blob/master/extensions/jdbc/jdbc-postgresql/runtime/src/main/java/io/quarkus/jdbc/postgresql/runtime/PostgreSqlServiceBindingConverter.java#L28) in a case sensitive way. Thanks!

**Comment by pedjak** [comment]
@johnpoth we are aware of it, #845 is going to address it (work in progress)

**Comment by johnpoth** [comment]
@pedjak thanks! Closing #844 in favor of #845
