### ISSUE TITLE
Support for flexible/pass-through binding naming strategy

### ISSUE THREAD

**Issue by akashshinde** [redhat-developer/service-binding-operator#845]
At the moment, binding names declared through annotations or CSV descriptors are processed before injected into the application according to the following strategy:

- names are upper-cased
- service resource kind is upper-cased and prepended to the name
For example, if the service is of kind Database and the binding name is host, then environment variable injected into the application is DATABASE_HOST.

The current approach is not flexible and make impossible for many applications to bind without changing them. We should openup a possibility to apply some other naming strategy, or none if needed, for example:

- none
- upercasing ( service kind + binding name)
- naming template (fully customizable approach)

"none" should be default if bindAsFile: true, otherwise "uppercassing"

**Comment by akashshinde** [comment]
Raised draft PR: https://github.com/redhat-developer/service-binding-operator/pull/835

**Comment by pedjak** [comment]
Implemented by #835
