### ISSUE TITLE
Support Strimzi

### ISSUE THREAD

**Issue by johnpoth** [redhat-developer/service-binding-operator#847]
As discussed with @pedjak, it would be cool to add support for the strimzi kafka operator:

https://github.com/strimzi/strimzi-kafka-operator/pull/2753

Thanks!

**Comment by pedjak** [comment]
the PR got moved here: https://github.com/strimzi/proposals/pull/38

**Comment by baijum** [comment]
> Updated proposal created: [strimzi/proposals#43](https://github.com/strimzi/proposals/pull/43)

I think we can close the issue as the proposal implementation is available here: https://github.com/strimzi/kafka-access-operator

**Comment by katheris** [comment]
JIRA issue: https://issues.redhat.com/browse/ENTMQST-3868

**Comment by sadlerap** [comment]
Marking as closed.  If there are any further issues, please re-open.
