### ISSUE TITLE
feature Request: Copy labels from ServiceBinding to intermediary Secret

### ISSUE THREAD

**Issue by johnpoth** [redhat-developer/service-binding-operator#852]
It would be cool to copy the labels from the ServiceBinding to the intermediary Secret.

Use case: the camel-k operator currently watches ServiceBindings to update it's integrations. The problem is that for this to happen correctly the Service Binding Operator needs to be installed before the Camel-k operator is started. One way to work around this is to watch Secrets filtered with camel-k labels.

Thanks !

**Comment by pedjak** [comment]
interesting idea - but coul you sketch a bit more the workflow.. once camel-k operator detects the secret, what happens then? how is that secret used? could the service binding operator inject that secretRef somewhere directly?

**Comment by baijum** [comment]
As discussed in today's meeting Custom projection would be an alternative (more complex?) solution: https://github.com/k8s-service-bindings/spec#custom-projection

**Comment by johnpoth** [comment]
As the intermediary Secret approach will be removed in the feature, I think we can close this issue
