### ISSUE TITLE
Extract key from json object in a Secret

### ISSUE THREAD

**Issue by haf-tech** [redhat-developer/service-binding-operator#853]
Enhancement
Provide the capability to extract a key/field from a json object which is stored in a Secret resource object

Example
```
kind: Secret
data
   connection: base64-encoded-string
```
The base64-encoded-string contains a JSON string, like
```
{
  "postgres": {
      "auth": {
          "user": "blub",
          "pass": "pass",
          "method": "direct"
      },
      "host": "example.com",
      "tls": {

      }
  }
}
```

Objective is, that SBO only inject/bind a specific field from the JSON, e.g. `postgres.auth.user` and `postgres.auth.pass` etc. in the resulting Secret in separate keys.

Probably, this is possible with the new go-template support in the mapping?

**Comment by sbose78** [comment]
cc @redhat-developer/service-binding

**Comment by baijum** [comment]
We could handle this as part of the Mapping Extension in the spec: https://github.com/servicebinding/spec/issues/145

**Comment by pmacik** [comment]
@haf-tech Closing the issue now, if you are still interested feel free to re-open.
