### ISSUE TITLE
Use ubi minimal in Dockerfile

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#856]
Why not use registry.access.redhat.com/ubi8/ubi-minimal instead of https://github.com/redhat-developer/service-binding-operator/blob/master/Dockerfile#L16 (gcr.io/distroless/static:nonroot).

Refer https://sdk.operatorframework.io/docs/building-operators/golang/migration/#operator-image

**Comment by pedjak** [comment]
What is the issue we would solve with this change? operator-sdk recommends using `gcr.io/distroless/static:nonroot`

**Comment by Avni-Sharma** [comment]
No issue as such, as a practice as mentioned https://github.com/redhat-developer/service-binding-operator/pull/316

**Comment by pedjak** [comment]
operator-sdk now recommends using `gcr.io/distroless/static:nonroot`, hence closing the issue.
