### ISSUE TITLE
Updating SBO metadata in CRD breaks existing Service binding configurations 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#860]
When new version of the operator is installed with different CRD/metadata existing service bindings will break and will never finalize. I think documentation should mention that metadata is considered part of the API version and should not be changed or something similar.

**Comment by pedjak** [comment]
It would interesting to see the log of service binding operator, are you able to provide it?

**Comment by wtrocki** [comment]
I woud close this one. It is more information/docs thing. I cannot pinpoint anything in my logs (log is huge and has lot of errors)
