### ISSUE TITLE
Using SBO to bind application running in one cluster with operator managed service running in other cluster

### ISSUE THREAD

**Issue by Jitesh817** [redhat-developer/service-binding-operator#869]
Hi,
I would to know if service binding operator can be used to bind an application running in one cluster to an operator managed backing service instance running in a separate cluster. This use case came up for us beacuse of way we do things with kubernetes platform  i.e. we have Application specific clusters for app devs to deploy and then Service specific clusters where all the service instances are managed. If this has been explored already then it would really helpful if i could be pointed in that direction like any doc/tutorial.

**Comment by sbose78** [comment]
Hey,

Would you be able to create a representation of the service on which the app lives?

**Comment by Jitesh817** [comment]
Hi,
by representation do you mean something that can reside within the app cluster or something else?

**Comment by baijum** [comment]
[Service Endpoint Definition](https://github.com/redhat-developer/service-endpoint-definition) could be one solution.

**Comment by baijum** [comment]
[Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference) can be used to connect to a service in another cluster.
