### ISSUE TITLE
SBO mounts binding information of multiple services under same directory

### ISSUE THREAD

**Issue by yharish991** [redhat-developer/service-binding-operator#874]
When I bind multiple services to an application using a single ServiceBinding CR, SBO mounts the binding information of both the services under the same directory. This can create confusion for application developers and for frameworks to build libraries for service binding(inside application perspective of service binding) as they won't be able to recognize which file belongs to which service when parsing the directory if the binding information of all services is in one directory. 

For example, [this](https://github.com/spring-cloud/spring-cloud-bindings) library parses all the directories under the `SERVICE_BINDING_ROOT` directory and identifies the binding type based on the `type` file in the binding directory, and maps the contents of the files in that directory to spring boot properties.

Is this the side effect of deviating from the k8s-service-bindings spec and supporting binding of multiple services in one CR?

One way to fix this is to create multiple intermediate secrets, one for each service and mount them, and the secret name can be something like this`${bindingName}_${id}`, where `id` is the id of the service mentioned in the CR.

**Comment by sbose78** [comment]
Thank you for the report!

If the service resources contain identical keys, they are to be better used in distinct ServiceBinding CRs. 

A list of Service resources in a single SBR are to be used *only* when we need to aggregate information from multiple service resources.

> One way to fix this is to create multiple intermediate secrets, one for each service and mount them, and the secret name can be something like this${bindingName}_${id}, where id is the id of the service mentioned in the CR.

I did consider this, but this might defeat the purpose of $SERVICE_BINDING_ROOT being a well-known env var to look up the root path?

**Comment by yharish991** [comment]
Thanks for the quick reply :)
> Thank you for the report!
> 
> If the service resources contain identical keys, they are to be better used in distinct ServiceBinding CRs.
> 
> A list of Service resources in a single SBR are to be used _only_ when we need to aggregate information from multiple service resources.
> 
Is this mentioned in the documentation? I don't remember seeing it, but I think it's important to warn the developers of using a single CR for binding multiple services.
> > One way to fix this is to create multiple intermediate secrets, one for each service and mount them, and the secret name can be something like this${bindingName}_${id}, where id is the id of the service mentioned in the CR.
> 
> I did consider this, but this might defeat the purpose of $SERVICE_BINDING_ROOT being a well-known env var to look up the root path?

What do you mean by defeating the purpose of `$SERVICE_BINDING_ROOT`? Let's say we have two services in one CR with name `binding-request` and ids of services as `postgres` and `mysql` , then the generated secrets could be something like `binding-request-postgres` and `binding-request-mysql` and mount them under $SERVICE_BINDING_ROOT directory, so let's say the if the $SERVICE_BINDING_ROOT is set to `/etc/secrets` then the directory structure could look something like this
```
 /etc/secrets
 ├──binding-request-postgres
 |        ├── type
 │        ├── uri
 ├──binding-request-mysql
 |        ├── type
 │        ├── uri

```

**Comment by sbose78** [comment]
I see, this definitely looks like a great approach to me. @pedjak what do you think?


> Is this mentioned in the documentation? I don't remember seeing it, but I think it's important to warn the developers of using a single CR for binding multiple services.

+1 Will need to check

**Comment by pedjak** [comment]
> Is this the side effect of deviating from the k8s-service-bindings spec and supporting binding of multiple services in one CR?

Yes, you are correct. cc @slemeur

> One way to fix this is to create multiple intermediate secrets, one for each service and mount them, and the secret name can be something like this${bindingName}_${id}, where id is the id of the service mentioned in the CR.

That might work in some cases, but through service binding one can create synthetic binding (`.spec.mappings`) that are also injected into application context. Having multiple secrets, the question would be where to put them? In all secrets, or just some of them?

**Comment by pedjak** [comment]
We do not recommend binding to multiple services within a single service binding. Ability to specify multiple service resource makes sense only if all these resources are actually containing some binding data belonging to the same physical service, so that the operator can collect them and project them into the application.

Please reopen if needed.
