### ISSUE TITLE
bindAsFile not functional on 0.5.0

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#886]
Hi

I seen relase notes but documentation still mentions bind as file:
https://github.com/redhat-developer/service-binding-operator/blob/master/docs/User_Guide.md

> This would generate a binding secret and inject it into the workload as an environment variable or a file based on bindAsFile flag in the ServiceBinding resource.

When I use `bindAsFile` option I still see env var injected and no /bindings folder.
I see environment variables used by default no matter if flag is there.

**Comment by pedjak** [comment]
We have a number of tests covering `bindAsFiles`: https://github.com/redhat-developer/service-binding-operator/blob/master/test/acceptance/features/injectBindingsAsFiles.feature and they are all passing atm. Can you share the service binding you are trying to apply?
