### ISSUE TITLE
sbo should by default bind as env and files

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#887]
Many extensions rely on sbo as files (quarkus sbo plugin etc.).
 When creating sbo using topology view in openshift there is no way to create sbo object with bind as files. As result, this spec-compliant way to binding is not enabled 
on happy path for regular users of Red Hat tooling

## Proposal

SBO should bind by default as env and files. This will give developers options to use different toolings to create binding and be backward compatible.

## Implementation

sbo could have 2 flags set
```
bindAsFiles: true
bindingAsEnv: true
```

Users can control those values if needed to bind only env or files

**Comment by wtrocki** [comment]
See also: https://github.com/openshift/odo/issues/4469

**Comment by sbose78** [comment]
+1

**Comment by baijum** [comment]
`bindAsFiles` flag is part of the `ServiceBinding` resource.
