### ISSUE TITLE
Sample integration tests application should provide more advanced use cases

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#888]
Sample application used in tests should add more use cases like:
https://github.com/redhat-developer/service-binding-operator/tree/master/test

Needed:
- Nested arguments
annotations:
    service.binding/bootstrapServer: 'path={.status.bootstrapServer.host}'
- Mapping secret values

**Comment by pedjak** [comment]
@pmacik can you take a look and see if some tests can be added?

**Comment by pmacik** [comment]
The nested arguments scenario as suggested in the description was not covered so I added it in #888.
However, mapping secret values is already covered by:

**Comment by wtrocki** [comment]
Thx
