### ISSUE TITLE
Feedback: Make ApplicationSelector optional to support Client App Operators which use ServiceBindingRequest Status Secret directly

### ISSUE THREAD

**Issue by ron1** [redhat-developer/service-binding-operator#89]
A client app operator that implements complex secret transforms such as converting an elastic-cloud operator Elasticsearch http server pem-formatted CA into a JKS truststore or builds a strimzi-kafka-operator Kafka consumer properties file based on multiple annotated backing service properties, will likely want to directly use the ServiceBindingRequest Status Secret as its complex secret transform source. This is in lieu of having the service-binding-operator directly inject its secret into the Deployment of the client app it manages. This allows a client app operator to treat the secret created by the service-binding-operator as an "intermediate" secret which it can then further transform if needed before it itself integrates the "final transformed" secret into the client app Deployment. When a client app operator is responsible for managing the client app Deployment, it is quite unnatural for the service-binding-operator to bypass the client app operator and directly inject secrets into the client app Deployment.

**Comment by ron1** [comment]
The Client App Operator will likely want to the secret mounted to its own deployment, So, simply let the ApplicationSelector reference the Deployment of the Client App Operator itself.

**Comment by sbose78** [comment]
> The Client App Operator will likely want the secret mounted to its own deployment, So, simply let the ApplicationSelector reference the Deployment of the Client App Operator itself.

Agreed!
