### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#891]
I was looking to feature SBO on slides. Do you have any project logo that can be used?

**Comment by pedjak** [comment]
Not yet.

**Comment by Avni-Sharma** [comment]
Making recommendation 1 for logo.
The database is those circular disks(inspired by flowchart symbols)
The rectangle is for process, any application, kafka, nodejs etc(inspired by flowchart symbol for process)
The spiral is like the spiral binding we have in books
![SBO_logo1](https://user-images.githubusercontent.com/18097007/112473020-d8169680-8d93-11eb-9e59-25db25a3ef43.jpeg)

**Comment by wtrocki** [comment]
Love it!

**Comment by sunilmalagi** [comment]
Hi,
I had worked on few logo options for 'SBO' based on the inputs from Baiju and Avni, here is the marvel link: https://marvelapp.com/prototype/14b5jgbj
I had placed those 5 variations on the context, please check all the 10 slides and get back to me with any feedback..

**Comment by Avni-Sharma** [comment]
Thanks a ton  @sunilmalagi for curating logos :tada:  I find slide 4/10 also good. :D

**Comment by slemeur** [comment]
Thank you @sunilmalagi for proposing those options.
I'm concerned that the icon is not going to look so nice when scale into a smaller place. Also, I'm wondering about having the label being only "SB" for Service Binding, not sure we need to mention "O" for Operator as we'd like to deliver the tools in different forms.
Keeping @Avni-Sharma initial idea, would it be possible to simplify it to be:
- one service, one process
- making the "connection arrow" a bit more styled (maybe that connection shape should be drawing an S and a B together?)

**Comment by sunilmalagi** [comment]
Thank you @slemeur for your inputs.. I tried creating few more SB logo's, let me know what you guys think about the new ones..
![Service_Binding_Logo_Options](https://user-images.githubusercontent.com/25147584/113843185-fecfc680-97b0-11eb-9b6d-b0506aa200a0.png)

**Comment by Srivaralakshmi** [comment]
I like the 7th one (the one before the last one). S and B slightly apart but coming together with the red ring connections. The red rings also symbolize Red Hat :) Feels perfect!!

**Comment by pmacik** [comment]
Hi all I also had an idea for a service binding logo. What about something like this - conceptually in color and colorless and with and without the letters?

![image](https://user-images.githubusercontent.com/3263627/113848970-4e09fd00-9799-11eb-8c00-a7b7de136c1f.png)

**Comment by pmacik** [comment]
and in a small icons...
![image](https://user-images.githubusercontent.com/3263627/113849609-f8822000-9799-11eb-8706-e8280e287c98.png)

**Comment by pedjak** [comment]
> Hi, what about something like this? Conceptually in color and colorless, with and without the letters.

Hey, @pmacik - great idea!

**Comment by slemeur** [comment]
+1 @pmacik

**Comment by wtrocki** [comment]
@pmacik Amazing logo. If you want to make it amazing you can use one of the colors approved by our brand (there is green color there) 

https://www.redhat.com/en/about/brand/standards/color

**Comment by pmacik** [comment]
Thanks all!

@wtrocki thanks for the suggestion about the "approved" color - I've looked and picked the "yellow-green" which is the closest and compared:
![image](https://user-images.githubusercontent.com/3263627/114022360-f7242680-9871-11eb-9b9c-c2550f7985b1.png)

**Comment by pmacik** [comment]
Based on feedback from @mmulholla I've increesed the slid between blocks to make it less "green blob" when rendered small:
![image](https://user-images.githubusercontent.com/3263627/114041637-ff399180-9884-11eb-847c-4637b26f845e.png)

**Comment by kpiwko** [comment]
@pmacik Cool!

**Comment by wtrocki** [comment]
I think we also missing another type of visualization ;)

![Screenshot 2021-04-09 at 11 53 28](https://user-images.githubusercontent.com/981838/114170025-39a93a00-992a-11eb-95b3-aa56c93259b1.png)

**Comment by slemeur** [comment]
lol =)
