### ISSUE TITLE
Spec Alignment

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#892]
Goals
A public specification for Service Binding have been authored by multiple actors from the community:

https://github.com/k8s-service-bindings/spec

We have been taking part of the specification effort, but there are some subtilities and API details that our current implementation is not aligned with.

We want to reconcile with the specification.

Compliance: Support the specification at API level
* Drive community awareness of Service Binding
* Bring more values for partners to support the spec, and support other K8s distribution
* Can collaborate with other vendors to get more interested partners - we can’t do that alone
* Rationalization: Leverage the opportunity to hardened our implementation.

Support for the spec API will be added along to the existing API, deprecating our own at some point or keeping it further as a playground for functionalities that might end up in some future version of the spec.

**Comment by Avni-Sharma** [comment]
Is this in the GA milestone?
