### ISSUE TITLE
Drop support for rebinding at data binding changes

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#895]
Reference EPIC #892 
Use case:

Rebinding at data binding changes

Reasons:

If binding definitions declared in ClusterServiceVersion, CustomResourceDefinition, or service itself change, the operator would need to rebind the affected applications, injecting into them the fresh binding data. In order to achieve this, the operator needs to watch for a huge number of events:

Watch for changes on all ClusterServiceVersions
Watch for changes on all CustomResourceDefinitions
Watch for changes on all resource kind defined by the above CustomResourceDefinitions
Watch for changes on all secret
Watch for changes on all configmaps
Production clusters might contain a good number of operators/CRDs/secrets/configmaps. OpenShift updates a number of secrets/configmaps on a regular basis. All this leads to a huge number of events that land into the operator queue. In most cases, processing of such an event does not lead to any rebinding, but consumes CPU and memory, crashing the node where the operator runs.
It should be investigated how often such rebind is really desired. Binding data are typically immutable and do not change after service has been provisioned. It is also questionable if changing binding definitions on ClusterServiceVersion and/or CustomResource is desired, and should be considered as API breakage.

**Comment by pedjak** [comment]
Fixed in https://github.com/redhat-developer/service-binding-operator/pull/903
