### ISSUE TITLE
Make Successful Service Binding Resource Immutable

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#896]
Reference EPIC #892 

Service Binding resources should be immutable.

**Comment by Avni-Sharma** [comment]
if SB resource is immutable then why do we need a reconcile?
we can have a kustomise flow to just apply resources and reapply
and if we have to collect info from annotations etc, we can have probably a CLI
 The fact that we have a Reconcile means to act on changes of the resource and take from the actual state to the desired state
making Service Binding resource immutable will not justify for us to have a whole reconcile logic for it

**Comment by pedjak** [comment]
We should act is service binding create/delete but not on update. cc @slemeur

**Comment by Avni-Sharma** [comment]
As we discussed, We would also allow patching/updates only SB that were failing before(i.e which had `Ready`: False), if SB was successful, then we could treat it as immutable.
This is in addition to the SB create/delete as mentioned above

**Comment by Avni-Sharma** [comment]
In a GitOps use cae the previous resources from the previous deployment are not removed. I.e if my git repo has an erroneous yaml and I apply it, and then if I push again to the git repo with the corrected yaml, then the SBO will not reconcile, in case of immutable SB resources. This happens with the GitOps operator as the GitOps operator does not remove previous resources from the previous deployment. the namespaces are not cleaned up before applying resources.

To support rebinding on a failing Ready condition we should allow Service Binding to reconcile. Therefore if the `Ready:False`. i.e if the Service Binding was unsuccessful we should allow reapplying of the Service Binding Resource. If the Service Binding was successful `Ready:true` then we should prohibit Reconcile() to be triggered and the new resource will not be configured.

Design is implementable
Implement a admission validating webhook for updates on SBR
Operator-sdk support for creating admission webhooks https://v1-0-x.sdk.operatorframework.io/docs/building-operators/golang/webhooks/
The webhook should validate the update event on the Service Binding resource and only allow the requests when Status condition for `Ready : False`.

**Comment by Avni-Sharma** [comment]
https://sso.jboss.org/login?service=https%3A%2F%2Fissues.redhat.com%2Flogin.jsp%3FpermissionViolation%3Dtrue%26os_destination%3D%252Fbrowse%252FAPPSVC-845%26page_caps%3D%26user_role%3D cc @jasperchui

**Comment by jasperchui** [comment]
Completed.

**Comment by pedjak** [comment]
reopening - the referred PR is still not merged.
