### ISSUE TITLE
Drop Support binding N services to application using single ServiceBinding resource

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#898]
Reference EPIC #892 

Use Case:

ServiceBinding resource allows declaring multiple services.

Reasons:

Although this looks at first as a handy shortcut, using this might cause a few issues:

A binding item from one service can be shadowed by another from another service (when binding keys are the same). Likelihood is very high, given that expected key names are username/password/url/… The issue can be worked around by introducing binding key prefixes or some custom naming conventions so that the keys become unique, but then it might be that such bindings cannot be consumed by application, i.e. it needs to be modified to support that
Unbind operation becomes all or nothing, i.e. it is not possible to unbind single service
What about updating/editing impact? I want to edit one service’s binding resources, how does it impact the applications that are consuming it?

Requirements:

Update samples: 
[SB] Binding a workload with a non-CR-based PostgrersDB: The service resources involved are (1)Route/Service to Postgres (2)Secret containing DB credentials.
[SB] Binding a workload with keycloak. The service resources involved are (1) Keycloak CR (2) KeycloakUser CR

**Comment by pedjak** [comment]
This case is contained in https://github.com/redhat-developer/service-binding-operator/issues/899 - by solved it, this is will be addressed as well. Hence closing.
