### ISSUE TITLE
Update Spec API Group name

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#920]
EPIC: #892 
Update group name once discussion https://github.com/k8s-service-bindings/spec/issues/113 is complete.

**Comment by DhritiShikhar** [comment]
There is still a discussion going on -> k8s-service-bindings/spec#113 
This can be groomed when the discussion has come to a conclusion.

**Comment by pedjak** [comment]
Done in https://github.com/redhat-developer/service-binding-operator/pull/1027
