### ISSUE TITLE
Support  Workload Resource Mapping 

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#927]
#985 is missing support for `ClusterApplicationResourceMapping`. See [spec](https://github.com/k8s-service-bindings/spec#application-resource-mapping) for the expected behavior.

**Comment by johnpoth** [comment]
Thanks @jasperchui , at the moment we would need this to upgrade past v.0.8.0 since #897 was dropped

**Comment by baijum** [comment]
> Thanks @jasperchui , at the moment we would need this to upgrade past v.0.8.0 since #897 was dropped

Most likely there will be some change in the spec related to the "Application Resource Mapping" feature. See this discussion:
https://github.com/k8s-service-bindings/spec/issues/177

We can wait for some more time to implement that feature.

**Comment by heiko-braun** [comment]
Hi @baijum, do you have a rough estimate for this one?

**Comment by baijum** [comment]
> Hi @baijum, do you have a rough estimate for this one?

There is PR in the spec under review: https://github.com/k8s-service-bindings/spec/pull/183
Once that PR is merged, we can start the work immediately.

**Comment by baijum** [comment]
PR #1086 address this issue.
