### ISSUE TITLE
Reconcile Conditions definition

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#932]
EPIC #892 
Spec defines
status:
  binding:
    name: prod-account
  conditions:
  - type:   Ready
    status: 'True'

Current behaviour: 
status:
 secret: prod-account-72ddc0c540ab3a290e138726940591debf14c581
 conditions:
  - lastTransitionTime: "2021-03-04T10:15:10Z"
    message: ""
    reason: BindingInjected
    status: "True"
    type: CollectionReady
  - lastTransitionTime: "2021-03-04T10:15:10Z"
    message: ""
    reason: BindingInjected
    status: "True"
    type: InjectionReady
  - lastTransitionTime: "2021-03-04T10:15:10Z"
    message: ""
    reason: BindingInjected
    status: "True"
    type: Ready

**Comment by pedjak** [comment]
This got changed with https://github.com/redhat-developer/service-binding-operator/pull/919 we post Ready condition, but along that we add two more conditions. Spec does not forbid that.
