### ISSUE TITLE
Secret projection into application behaviour

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#934]
EPIC #892 
Clarify expected secret projection.
Spec defines
A Service Binding resource SHOULD reflect the secret projected into the application as .status.binding.name

Current behaviour is:
ServiceBinding resource reflects the secret projected into the application as .status.secret

**Comment by DhritiShikhar** [comment]
Since, binding secret name is same as the ServiceBinding CR's name. Why is this change necessary?

**Comment by jasperchui** [comment]
Closing as it will be handled in another Issue.
