### ISSUE TITLE
Handling Binding Secret Name

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#935]
EPIC #892 
Resolve Binding Secret Name
Spec defines Binding Secret name is same as Service Binding name.
Example:
prod-account

Current behaviour is: 
Binding Secret name format is `name of Service Binding` + `-` + `sha1 hash of the secret content`.Example:prod-account-72ddc0c540ab3a290e138726940591debf14c581

**Comment by pedjak** [comment]
@jasperchui can you point to the part of spec stating that? I cannot find it  - only thing what is there is the following:

```
A Service Binding resource SHOULD reflect the secret projected into the application as .status.binding.name.
```

**Comment by jasperchui** [comment]
Closing as no longer applicable
