### ISSUE TITLE
Binding secret as files behaviour

### ISSUE THREAD

**Issue by jasperchui** [redhat-developer/service-binding-operator#936]
EPIC #892 
Spec defines by default, it injects binding secret as files.

Current behaviour is to by default, it injects binding secret as environment variables.

ServiceBinding injects binding secrets as files by setting an additional field `bindAsFiles` as `true`

spec:
  bindAsFiles: true

**Comment by wtrocki** [comment]
@jasperchui  this can be closed :)

**Comment by DhritiShikhar** [comment]
@wtrocki 

There are two parts to it:
1. By default injecting secrets as files.
2. Removing the `bindAsFiles` field.

The first one has been achieved by setting `bindAsFiles: true` by default.
The second part is yet to be done.

So, we could update the story instead of closing it.

**Comment by wtrocki** [comment]
What would be reason to remove bindAsFIles? Seems like breaking change that can be easily avoided by deprecation

**Comment by pedjak** [comment]
I agree here with @wtrocki here. Out current API is a superset of spec API - at some point we are going to support spec API along our own API, and there we are going to have only features specified by the spec.
