### ISSUE TITLE
Release 0.7.0 breaks selection of multiple services

### ISSUE THREAD

**Issue by nastacio** [redhat-developer/service-binding-operator#944]
### What is the environment (Minikube, Openshift)?
OpenShift 4.6.22, on IBM Cloud

### What is the SBO version used?
0.7.0

(this example was working in 0.6.0 and stopped working in 0.7.0)

### What are the steps to reproduce this issue?
  1. Create one application and two services
  2. Create a service binding request between the application and the two services
  3. Reference the service fields in the `mappings` section of the binding request
  4. Apply the resulting YAML to the cluster

```
oc new project sbo
oc new-app https://github.com/openshift/ruby-hello-world#beta4 -n sbo
oc apply sb-original.yaml
oc apply sb-reverse.yaml
```

### What is the expected behaviour?
All mapped values should be present in the final `Secret` objects created from the binding.

### What is the actual behaviour?
Only the mapped values from the one of the services (last in file?) appear in the secrets.
The mapped values from the other services are empty.

See two outputs:

```
oc get secret binding-original-f999dd17  -n sbo -o jsonpath='{.data.env\.json}' | base64 -d | jq .
{
  "Values": [
    {
      "HOST": "ruby-hello-world.sbo.svc.cluster.local",
      "SOURCE": "<no value>"
    }
  ]
}
root@6d37c76e5d2e:/tools/scripts# oc get secret binding-reverse-18a1300e   -n sbo -o jsonpath='{.data.env\.json}' | base64 -d | jq .
{
  "Values": [
    {
      "HOST": "<no value>.<no value>.svc.cluster.local",
      "SOURCE": "beta4"
    }
  ]
}
```

### Service Binding Operator Logs
[operator-logs.txt](https://github.com/redhat-developer/service-binding-operator/files/6287237/operator-logs.txt)

### Additional Information (Screenshots, etc)

[sb-example-archive.zip](https://github.com/redhat-developer/service-binding-operator/files/6304356/sb-example-archive.zip)
(contains `sb-reverse.yaml` and `sb-original.yaml`)

I rolled back the operator to 0.6.0 and saw the correct results again:

```
 oc get secret binding-original-6f93c924eb98fbd528c74b610b632229352734c1  -n sbo -o jsonpath='{.data.env\.json}' | base64 -d | jq .
{
  "Values": [
    {
      "HOST": "ruby-hello-world.sbo.svc.cluster.local",
      "SOURCE": "beta4"
    }
  ]
}

oc get secret binding-reverse-6f93c924eb98fbd528c74b610b632229352734c1 -n sbo -o jsonpath='{.data.env\.json}' | base64 -d | jq .
{
  "Values": [
    {
      "HOST": "ruby-hello-world.sbo.svc.cluster.local",
      "SOURCE": "beta4"
    }
  ]
}

```

**Comment by pedjak** [comment]
thanks for the report, I am looking for `sb-reverse.yaml` and `sb-original.yaml` but it seems they are not attached?

**Comment by nastacio** [comment]
> thanks for the report, I am looking for `sb-reverse.yaml` and `sb-original.yaml` but it seems they are not attached?

My mistake, ugh, apologies.

I just attached an archive file containing both.
