### ISSUE TITLE
Regression/Breaking changes in 0.7.0

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#945]
## Different 

It looks like sbo binds files by default in openshift console.

0.6.0 release
``` 
sh-4.2$ ls /bindings/nodejs-sample-d-ajay-test-akc/
clientsecret user password type clientid
```
After 0.7.0
```
 sh-4.2$ ls /bindings/nodejs-sample-d-ajay-test-akc/
KAFKACONNECTION_BOOTSTRAPSERVERS  KAFKACONNECTION_CLIENTSECRET  KAFKACONNECTION_PROVIDER       KAFKACONNECTION_SECURITYPROTOCOL  KAFKACONNECTION_USER
KAFKACONNECTION_CLIENTID          KAFKACONNECTION_PASSWORD      KAFKACONNECTION_SASLMECHANISM  KAFKACONNECTION_TYPE
```
0.7.0 is not aligned with how spec does it.

**Comment by pedjak** [comment]
hm, our tests https://github.com/redhat-developer/service-binding-operator/blob/80e6434a78eb1310ca714b0e6477516443c059d3/test/acceptance/features/injectBindingsAsFiles.feature#L12 verify that the behavior is according to the spec. Can you share you service binding you try to apply?

**Comment by wtrocki** [comment]
Not sure if service binding is the issue as it is being created by OpenShift Topology as in our summit guides.
Maybe problem is in the spec:

https://github.com/redhat-developer/app-services-operator/blob/main/olm/olm-template/manifests/rhoas-operator.kafkaconnections.crd.yaml#L7-L21

**Comment by pedjak** [comment]
I can confirm the issue. #949 is going to fix it. Until then, setting `spec.namingStrategy: none` can work around the issue.
