### ISSUE TITLE
0.7.0 - What is the way to create environment based bindings

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#947]
Creating service bindings using operator binds as files by default. 
 Was that expected? How to get environment var bindings

**Comment by pedjak** [comment]
yes, we flipped default behavior - use `bindAsFiles: false` to project bindings as env vars.

**Comment by wtrocki** [comment]
Can we swapped to documentation bug
https://github.com/redhat-developer/service-binding-operator/blob/master/docs/User_Guide.md is missing that info

**Comment by pedjak** [comment]
the documentation has been updated in #949
