### ISSUE TITLE
Deletion of the servicebinding keeps volumes still attached

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/service-binding-operator#948]
Clarification needed if deletion of the service binding should remove volumes (currently it doesn't) which leaves pods in the state where there is no traceability of where volume came from. On the other hand this can be seen as a feature.

**Comment by pedjak** [comment]
is it possible to remove binding? is the binding secret removed?

**Comment by wtrocki** [comment]
Yes. How what will be the name of binding secret in this case?

**Comment by wtrocki** [comment]
Yes. Binding is removed properly. How what will be the name of binding secret in this case?

**Comment by wtrocki** [comment]
I see that binding is removed but secret stays there as well as volume
