### ISSUE TITLE
New Blog Post

### ISSUE THREAD

**Issue by Avni-Sharma** [redhat-developer/service-binding-operator#952]
The old blog post currently viewed in all operator versions is obsolete, i.e it uses deprecated APIs, annotation format https://developers.redhat.com/blog/2019/12/19/introducing-the-service-binding-operator/ 

A new blog post is required to showcase new capabilities(mountable files, namingStrategy) and the associated new API, new annotation format.
Also to highlight what we not fully support, like a case of managed binding
```
Note that in addition to the initial sharing of binding information, the binding is also “managed” by the Service Binding Operator. This statement means that, if credentials or URLs undergo modification by the backing service operator, those changes are automatically reflected in the application.
```
We support initial binding but reflecting modifications is not supported.

**Comment by pedjak** [comment]
Before doing blog post, we should update/consolidate userdoc.

**Comment by pedjak** [comment]
Closing since there are two blog posts available:

* https://developers.redhat.com/articles/2021/11/03/how-use-service-binding-rabbitmq by @sadlerap 
* https://developers.redhat.com/articles/2021/10/27/announcing-service-binding-operator-10-ga by @slemeur
