### ISSUE TITLE
Feedback: Generalize BackingServiceSelector to select multiple resources including OLM-annotated CRs as well as ConfigMaps and Secrets

### ISSUE THREAD

**Issue by ron1** [redhat-developer/service-binding-operator#96]
Backing service operators such as mongodb-enterprise-operator and strimzi-kafka-operator have distinct CRs for the service itself and its individual users. In order for an application to bind to such services as a specific user, the ServiceBindingRequest backingServiceSelector should support the selection of multiple CRs, in this case a service CR and a specific user CR. The OLM annotations associated with each of these CRs can be used to extract fields that are subsequently aggregated into a single secret.

A similar approach can be used to support backing services that do not yet have OLM-annotated descriptors. In these cases, the backingServiceSelector could be defined to select a set of ConfigMaps and/or Secrets. The service-binding-operator would aggregate the fields of the selected ConfigMaps and/or Secrets into a single secret. A list of JSON Secret Transforms defined in the ServiceBindingRequest (based on the SecretTransform type defined for ServiceBindings/AppBindings) could be used to transform the aggregated secret into a form ready for injection via the ApplicationSelector.

Support for binding to external services could also leverage a backingServiceSelector defined to select a manually-populated ConfigMap and/or Secret. Again, the aggregated, transformed secret would then presumably be ready for injection via the ApplicationSelector.

**Comment by otaviof** [comment]
@ron1 thanks for the feedback, that's a use-case that we haven't dealt with. And we might need to change the approach to mimic `kubectl`, on checking first the resources from the API Server, and only then search for backing-service related CR.

> Backing service operators such as mongodb-enterprise-operator and strimzi-kafka-operator have distinct CRs for the service itself and its individual users. In order for an application to bind to such services as a specific user, the ServiceBindingRequest backingServiceSelector should support the selection of multiple CRs, in this case a service CR and a specific user CR. The OLM annotations associated with each of these CRs are used to extract fields that are subsequently aggregated into a single secret.

**Comment by ron1** [comment]
As part of such a change, would it make sense to rename backingServiceSelector to the more generalized backingServiceResourcesSelector?

Do you have any comments about also supporting ConfigMaps and Secrets as backing service resources that could be selected by a backingServiceResourcesSelector?

Finally, do you have any comments about the feedback I provided in issues https://github.com/redhat-developer/service-binding-operator/issues/88 and https://github.com/redhat-developer/service-binding-operator/issues/89? We have implemented an ansible-based  bindable-user-operator that watches AppBinding custom resources (https://github.com/kmodules/custom-resources/blob/master/apis/appcatalog/v1alpha1/appbinding_types.go) and relies upon backing service-specific ansible roles to generate AppBinding secrets. The drawback here is that custom ansible roles must be developed for each backing service Group/Kind which is quite heavyweight. The binding-service-operator approach of using a selector and OLM descriptor annotations to generate an intermediate binding secret is much preferred. However, the binding-service-operator in its current form is not usable for us. Does a design document or roadmap exist for the binding-service-operator that might provide insight into the future direction of the project? I suspect if if the issue tracker for the project was publicly available that would help.

Thanks again for the feedback.

**Comment by sbose78** [comment]
> would it make sense to rename backingServiceSelector to the more generalized backingServiceResourcesSelector?

It actually does. Wondering if we could use a shorter name as well? 


> Do you have any comments about also supporting ConfigMaps and Secrets as backing service resources that could be selected by a backingServiceResourcesSelector?

Typically, would you expect that everything in one or more such resources would be managed in binding secret, and everything in the configmap/secret would be be _bound_ . Furthermore, in simplistic terms, would it help support binding to a route/service/deployment as well ? If someone tries to bind to a deployment, we look up for an associate route or service and bind to it.

**Comment by ron1** [comment]
> It actually does. Wondering if we could use a shorter name as well?
How about backingSvcResSelectors?

> Typically, would you expect that everything in one or more such resources would be managed in binding secret, and everything in the configmap/secret would be bound?
Yes. In the corresponding preSecretAggregation transforms, removeKey transforms could be used to filter out irrelevant keys from the generated secret.

> Furthermore, in simplistic terms, would it help support binding to a route/service/deployment as well ? If someone tries to bind to a deployment, we look up for an associate route or service and bind to it.
Not sure I completely understand the current behavior. Would you describe it in a bit more detail?

**Comment by isutton** [comment]
> > It actually does. Wondering if we could use a shorter name as well?
> 
> How about backingSvcResSelectors?

Wouldn't `resourceSelector` be enough in this case?

**Comment by ron1** [comment]
> would it help support binding to a route/service/deployment as well ?

I envisioned the only selectable resources being OLM-annotated CRDs, ConfigMaps, and Secrets. All of these present as simple key-value structures which dramatically simplifies the aggregations and transformations needed to generate a final binding secret.

> Wouldn't resourceSelector be enough in this case?

Sure, resourceSelectors plural works.

**Comment by isutton** [comment]
> All of these present as simple key-value structures which dramatically simplifies the aggregations and transformations needed to generate the desired final binding secret.

Wouldn't be the case that, ultimately, any document is a simple key-value structured with paths instead of keys? If this is indeed true, then what do you see as benefit on limiting the scope with those object types only?

**Comment by ron1** [comment]
@isutton OLM-annotations handle the mapping to keys for CRDs. ConfigMaps and Secrets require no mapping. Introducing an additional mechanism to map source resource paths to secret keys adds extra complexity. Most binding use cases of which I am aware can be implemented using only CRs, ConfigMaps, and Secrets. If OLM annotations are the preferred mapping method, why introduce an additional path-based scheme if not needed?

**Comment by pedjak** [comment]
Closing, please reopen if still relevant.
