### ISSUE TITLE
Documentation of the operator-backing-service-samples/postgresql-operator is not up to date 

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/service-binding-operator#969]
## Documentation issue

The README page of the [postgresql](https://github.com/operator-backing-service-samples/postgresql-operator) operator that we can use as example is not up to date as the `operator-sdk` commands reported to build the image, run it are not longer available

To build the image
```
operator-sdk build quay.io/cmoulliard/postgresql-operator:11
Error: unknown command "build" for "operator-sdk"
Run 'operator-sdk --help' for usage.
FATA[0000] unknown command "build" for "operator-sdk"
```

## Versions
```
operator-sdk version
operator-sdk version: "v1.7.2", commit: "6db9787d4e9ff63f344e23bfa387133112bda56b", kubernetes version: "v1.19.4", go version: "go1.16.3", GOOS: "darwin", GOARCH: "amd64"
```

**Comment by DhritiShikhar** [comment]
Makefile also has `operator-sdk build` command ->https://github.com/operator-backing-service-samples/postgresql-operator/blob/master/Makefile#L45

This needs to be updated.

**Comment by pedjak** [comment]
Closing, because #1034 removed this example.
