### ISSUE TITLE
Example scenarios should use real world Operators

### ISSUE THREAD

**Issue by kadel** [redhat-developer/service-binding-operator#990]
Every PostgreSQL example that is in https://github.com/redhat-developer/service-binding-operator#example-scenarios uses custom operator that was purposely designed to play nice with SBO. 
This makes for nice demos, but it doesn't help user understand how to set up ServiceBinding for real work applications.

It would be much better if the examples in SBO docs use Operators that are commonly used for real world applications. 

https://operatorhub.io/operator/postgresql
https://operatorhub.io/operator/percona-xtradb-cluster-operator
https://operatorhub.io/operator/redis-enterprise

**Comment by pedjak** [comment]
Related #1034

**Comment by pedjak** [comment]
Closing, please reopen if still relevant.
